### ISSUE TITLE
No confirmation/warning message for cancelling Scroll of Enchantment

### ISSUE THREAD

**Issue by omfgtora** [00-Evan/shattered-pixel-dungeon#1004]
On any other scroll, if you attempt to cancel it will provide a message asking if you are sure you want to cancel the scroll use because the scroll will still be consumed. I inadvertently hit the cancel button and it just immediately cancelled without warning and I lost the scroll.

**Comment by 00-Evan** [comment]
In this case the warning is contained in the window itself, it states "Cancelling will still consume the scroll."

The popup you're mentioning is used for unidentified scrolls/potions, and is used when you try to cancel selecting an item or similar, at a time where the item normally wouldn't be consumed if it were identified.

**Comment by omfgtora** [comment]
Would it not be possible to add this existing feature to the cancel button which is unfortunately close to choosing options?

**Comment by omfgtora** [comment]
Are you unwilling to discuss this to improve the UX?

**Comment by 00-Evan** [comment]
Generally I don't want to put extra 'are you sure you want to do this?' warnings into the game unless absolutely necessary. For example pits have a warning because on some level layouts it is extremely easy to mistap into them, the same isn't true for traps. In this case seeing as the window description states the scroll will be lost anyway, I don't think it's needed to have a separate confirmation window. A separate window does exist for unidentified items because they only circumstantially disappear when you cancel the effect.

**Comment by omfgtora** [comment]
The reasoning for the confirmation on pits due to a mistap being extremely easy is the exact reasoning I believe this should be added for this scenario as well. In my case, I was trying to get information on the last choice and incidentally clicked the cancel option.

Additionally, the UI is a communication between the app and the user. If you establish that confirmation screens happen under essentially the same scenario for other scrolls then it would be perfectly reasonable for the user to expect it under this scenario.

Another option would be to add a gap between the last option and the cancel button.
