### ISSUE TITLE
Could you release the ios build on the github (an .ipa file)

### ISSUE THREAD

**Issue by trollo2** [00-Evan/shattered-pixel-dungeon#1008]

**Comment by 00-Evan** [comment]
Unfortunately I am not allowed to publicly distribute Shattered IPAs outside of Apple's services, as per Apple's developer agreements. The best I can do is make the source available so that others can build personal or unofficial versions.

Here is the relevant agreement, distribution is covered on page 1, paragraph 2 under 'purpose', and further clarified in Section 3.2(g) on page 16: https://developer.apple.com/support/downloads/terms/apple-developer-program/Apple-Developer-Program-License-Agreement-20220606-English.pdf
