### ISSUE TITLE
[Feature Request] Pixel Perfect graphics mode

### ISSUE THREAD

**Issue by Solitudocultor** [00-Evan/shattered-pixel-dungeon#1018]
Some people may not like rotating upscaled pixels. By Pixel Perfect, I mean 1x resolution rendering (including rotating pixels) and then integer upscaling.

**Comment by 00-Evan** [comment]
Implementing this would require a significant amount of graphics work for something that would only occur in specific scenarios (e.g. throwing items).

The game unfortunately also depends on sub-pixels for several details such as text rendering. Forcing a 1x resolution and them upscaling would make most text illegible, and would also ruin the intended visual motion of most particle effects. As it is the game requires a minimum of 2x res because of these things, and even then it can get pretty grainy/choppy.
