### ISSUE TITLE
[Feature Request] Game replays

### ISSUE THREAD

**Issue by Solitudocultor** [00-Evan/shattered-pixel-dungeon#1019]
Saving run records with the ability to view the replay from the record list or the Hall of Fame.

**Comment by 00-Evan** [comment]
Unfortunately the game is not built with replay functionality in mind, there is no way to store a record of game state changes without an entire save game's worth of data for every action, which would be extremely slow to replace and take up a prohibitive amount of storage space. Implementing proper rewinding of game state is possible but would requite a huge amount of work that I would rather spend on gameplay additions.

**Comment by Tiger-Tom** [comment]
A potential idea for this that I had comes from a game project that I abandoned a while ago. In the game, I would have made it so that the save is literally just a recording of all of the player's actions with the timing of each action (unnecessary for PD), stored as a delta, as well as the random seed of the game. For instance, using letters A-Z, a-z, as well as numbers, you can represent a number up to 62 in one byte. Using that, you could have move up as "b", pick up item as "C", and use item as "2". Then, the string "bC207" would move up one space, pick up the item in that space, then use the item in bag 0 (regular inventory), slot 7. The actions "move up (b)" and "pickup item (C)" would take one byte, and "use item (2)" would take up 3 bytes (second byte for bag, third for slot). This could be optimized using Zlib deflate quite easily, and it might be unnecessary to use full bytes (second byte of "use item" could be 3 bits for bag and 5 for the slot, for instance). This string would be run in the game engine. The only problem would be if the game updates, the recording may break. Another problem would be parts of turns (ring of haste, furor, slow/fast weapons, etc.) which would be harder to store, perhaps requiring some special prefix, or having the first few bits be used for the fraction of the turn. Like you said, this probably wouldn't be easy or really useful to add, but I thought it was a neat idea.
