### ISSUE TITLE
No food in 0.4 (after update)

### ISSUE THREAD

**Issue by broiniac** [00-Evan/shattered-pixel-dungeon#103]
I believe there is no way to obtain food in v0.4. I've been playing it for few hours now and every game ended by starvation. Food can't be found anywhere, neighter bought in shops.

Bug or feature? I have to admit - game is much more harder right now.

**Comment by 00-Evan** [comment]
Do you have the 'on diet' challenge enabled by chance?

**Comment by broiniac** [comment]
Yes, what is weird, because I don't have challenges unlocked yet.

**Comment by 00-Evan** [comment]
That is odd, are you able to disable the challenge and play as normal?

**Comment by broiniac** [comment]
No. On character selection page I was informed that I need to complete game first. Challenges were visible, but not editable during game through.

**Comment by 00-Evan** [comment]
That's very odd, the only way to change the challenge data is to either use that UI or edit the game's save data directly.

Do you have root?

**Comment by broiniac** [comment]
Yes, I have root. I didn't mess with game's properties within any file, but since no one else complained about it, I think it's safe to assume, that' it is something on my side.

**Comment by 00-Evan** [comment]
Yeah it's possible that it was caused by a IO error or similar.

Regardless, if you have root you can fix this by:
- force-quit shattered
- find shattered's data files in /data/data/com.shatteredpixel.shatteredpixeldungeon
- Look for the preferences file
- Find the key "challenges", currently its value should be set 1 for you, which is the constant for the no food challenge
- set the value to 0 instead.
- All new runs should now be without the challenge.

**Comment by broiniac** [comment]
Thank You so much for help and quick response!
Also good work with latest update :)
