### ISSUE TITLE
Crash on neighbour's kid death

### ISSUE THREAD

**Issue by SlooowAndFurious** [00-Evan/shattered-pixel-dungeon#1043]
Hello.
I was (hopelessly) attempting a pharmacophobia run and got poisoned in a stupid way. When I've got 1 HP and 8 turns of poison left, I committed suicide by dragging myself with the ethereal chains right to a chasm. And then, this showed up to me :
![image](https://user-images.githubusercontent.com/46223749/180324163-e291dc07-573b-438f-b120-a312b6ea4936.png)
After reading the error (but not the code), I think, as the hero died of poison while committing suicide, that the next floor was not generated (and thus, was null) but was required for the game over screen.

**Comment by 00-Evan** [comment]
This is occurring because the hero going over the chasm triggers the game to start the falling logic, which includes changing the game scene to the level transition scene. So then after that the game over logic tries to trigger and we get this crash when it assumes the game scene is still active. I'll add a check in that display logic to make sure the game scene is present.

**Comment by 00-Evan** [comment]
fixed in commit 401a0701e70e172cd9cbc12391327cd1f9598448
