### ISSUE TITLE
challenge concept: Money makes the world go round

### ISSUE THREAD

**Issue by Eonfge** [00-Evan/shattered-pixel-dungeon#1062]
Hey,

It has been some time since I shared feedback, but while playing in the train, I got a new idea for a challenge: Monsters, chests, and the floor don't contain any items. Instead, you only get money that you can then spend in the store.

Some things that are left open to discuss;
- How should this interact with other challenges?
- Should the stores be larger (or more frequent) to supply additional items?
- What about progression items, like SoU and PoS?

**Comment by 00-Evan** [comment]
This sounds more like an alternate game mode instead of a challenge, a sort of 'draft mode' instead of the usual finding items in the dungeon.

New game modes (or even separate dungeons entirely) are something that might be interesting to concept, but I'd rather focus on other content first (e.g. quest reworks, new heroes).
