### ISSUE TITLE
(Funny) Tengu throws infinite throwing stars if you "sleep" in front of him instantly killing you

### ISSUE THREAD

**Issue by tiw-gpidev** [00-Evan/shattered-pixel-dungeon#107]
It was a straight line of shuriken in my face from off the screen

**Comment by 00-Evan** [comment]
This is sort of a tradeoff, Tengu's shots do not pause game logic when being fired to make it more convenient when you're fighting him in his arena. Would you prefer having to pause and wait for every show he fires to complete?

**Comment by tiw-gpidev** [comment]
What I figured was inconsistent was that I thought it would do the thing where if you "slept" in front of a monster you wouldn't wake up until it hits you, but it just rolls all the hits at the same time.

**Comment by tiw-gpidev** [comment]
I realize this is "is the player stupid enough to do this" material, but a lot of times I am indeed that stupid.

**Comment by 00-Evan** [comment]
The hits are all rolled so quickly because of the specific logic of tengu's ranged attacks. Most range attacks essentially pause all game logic until their visual elements resolve, but I opted not to do this for Tengu because it would make chasing hims down very tedious.

In specific cases where the player loses control (e.g. sleeping, paralysis) this will cause tengu to attack many times very quickly, because the game isn't waiting for his first attack to resolve, and he's the only entity that gets to act.

I could fix this by putting in a check to disable resting when Tengu initiates an attack, or possibly by switching him to the standard ranged attack logic, but make his attack projectile move significantly faster.

**Comment by 00-Evan** [comment]
fixed in commit 18cc801eb20df6a044b6af331d08af6afcebc314
