### ISSUE TITLE
Cancelling using a Scroll of Enchantment loses it.

### ISSUE THREAD

**Issue by jchown** [00-Evan/shattered-pixel-dungeon#1078]
If you go to use a Scroll of Enchantment (maybe other exotics too?) and cancelling the choice of armour/weapon (i.e. to double-check something) causes it to disappear, even if it is identified.

There's no are-you-sure like there is when you first use an unidentified upgrade or remove curse scroll.

**Comment by 00-Evan** [comment]
Just double checked this and it seems to be working as intended.

Cancelling the scroll before selecting weapon/armor works exactly the same as upgrade scrolls. The scroll if preserved if you have it IDed, otherwise you will get a warning.

If you have already selected an item, cancelling always consumes the scroll. The selection window warns about this. The reason for this is that you've already seen what enchants/glyphs the scroll is offering you, so getting the scroll back at that point would let players manipulate the effect.

**Comment by jchown** [comment]
Just to clarify, you lose the scroll if it is IDed, with no warning. I will try and record a video to show the issue.

**Comment by jchown** [comment]
Here's a video that demonstrates the bug (twice on the bounce!)

[Video of bug](https://www.dropbox.com/s/isd0h9l26bfbm86/Screen_Recording_20220915_234040.mp4?dl=0)

**Comment by 00-Evan** [comment]
Please re-read my message, and fully read the window that pops up after you select an item to use the scroll on.

**Comment by jchown** [comment]
Ah, I see what you mean. I evidently read your message with the same diligence as I read the in-game pop-up.

I do hope that you consider adding an "are you sure?" to the cancel option, if only to stop myopic fools like myself from harassing you in future.

**Comment by 00-Evan** [comment]
Generally I try not to put too many 'are you sure?' sort of prompts in the game. Players have also often asked for a confirmation before stepping on traps. In this case it felt unnecessary as the window itself already warns about cancelling, and the player has to directly press the cancel button to close the window.
