### ISSUE TITLE
no fire animation with ring of haste

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#1085]
I had a ring of haste and caught on fire.  The fire never showed visually.  This bug didn't happen normally but I'm not sure what made this occurrence unique.
![Screenshot_20220921-012555](https://user-images.githubusercontent.com/8593007/192121900-6a6a791e-deaa-4540-b414-228d81c028b2.png)

**Comment by chorby-short** [comment]
Another issue that is often annoying is that fire and caustic acid are only cured at the end of a turn, so if you pass through water but step out again in before the turn ends (due to haste), you will not be cured of the debuff. It essentially forces you to wait a turn, and if you don't know about this not-at-all obvious quirk, it can lead to injury and death. Perhaps your issue is related to that?

**Comment by 00-Evan** [comment]
Particles for buffs/debuffs not apeparing on the player is an older bug that I have not been able to reproduce. It is extremely rare and likely due to a race condition. Unfortunately your movement speed is almost certainely not related to the bug, as it's purely visual, separate from gameplay logic.

@chorby-short it is unrelated. I appreciate that can be annoying, but it is intended that the player has to spend a turn in water to cleanse the debuff.
