### ISSUE TITLE
Missing available languages in the Steam store page

### ISSUE THREAD

**Issue by galaipa** [00-Evan/shattered-pixel-dungeon#1093]
Recently Steam [added](https://store.steampowered.com/news/group/4145017/view/3325361214990632478) a bunch of new languages to select when indicating which languages do the games support. The updated list of available languages can be found [here](https://partner.steamgames.com/doc/store/localization/languages).

It might sound like a small thing, but this is very important for languages like Basque were only a few games are available. That's why I would like to kindly ask you to update the supported languages list.

Currently Shattered Pixel Dungeon has the following languages listed in the Steam page: English, French, Italian, German, Spanish-Spain, Czech, Finnish, Greek, Hungarian, Japanese, Korean, Portuguese-Portugal, Russian, SImplified Chinese, Turkish, Ukranian

By checking  Shattered Pixel Dungeon's [source code](https://github.com/00-Evan/shattered-pixel-dungeon/blob/4f32d906a05a3b56a60d34d6e835a53c50280a01/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/messages/Languages.java) (I might be looking in the wrong place?) I assume the following ones are missing: Korean, Polish, Indonesian, Dutch, Finnish, Greek, Catalan (?), Galician, and Basque.

I also see Esperanto in the list, but if I'm not mistaken that one is not available in Steam.

Thank you in advance

**Comment by 00-Evan** [comment]
These languages were not included in the game's store page because they (at the time of last updating the store page) weren't close to fully translated. At the moment I would say Polish is close enough to be added. Indonesian, Dutch, Catalan, Galician, and Basque are all below 90% translated. Catalan in particular is below 70% and was removed from the game entirely. Korean, Finnish, and Greek were already shown as supported.

**Comment by galaipa** [comment]
Understood. Thank you for your time.
