### ISSUE TITLE
Failed Surprise Attack Bug??

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1106]
I haven't really noticed this outside of a fairly specific situation. Allow me to describe.

I usually brew some shrouding fogs for the Yog fight to have an easier go of it when the eye is vulnerable; it allows me to avoid fighting the adds while focusing on getting the fists to spawn. I'll take the opportunity to kill deathgazes/scorpios when they spawn (if I can spare the time) &, only occasionally, the surprise attack will miss. In my memory, this happens only when using a reach weapon from a tile away while both chars are in the fog. I think this is likelier if the add just spawned but I cannot consistently reproduce it. Anyway, I'll keep an eye on this (NPI) & post again if I find out more about this possible bug.

**Comment by 00-Evan** [comment]
This is likely occurring from attacking an enemy when they just spawn. This is an unfortunate quirk of the way the game's AI works. because they have not acted yet, they haven't had a chance to update their vision and not see you, and so the game assumes you are visible to them unless you're invisible.
