### ISSUE TITLE
Feature Req: Safer Move Continuation

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1114]
I believe this issue was originally raised in #272 where you (Evan) hinted it would be addressed in UI changes when shifting to a desktop release. It was raised again in #651. I see it's still an issue in the current build & was curious if you're planning anything w/ it. I've lost a few heroes over the years to it & recently suffered some pretty heinous HP loss to it. The main culprits are ranged attackers & projecting champs from outside vision. I appreciate being able to move thru DOT's but losing a run or most of your HP before you can react isn't very fun. Having a pause exception for the above cases or a check for losing a significant portion of HP (~20%) would go a long way in solving this.

**Comment by 00-Evan** [comment]
Please comment in existing issues instead of creating duplicates. I get notified about it either way. This is also, as I mentioned before, how continue moving is intended to work currently.

As for reconsidering the functionality, the answer is that it's still on the list but not a high priority. It's also tricky to consider given that continue moving has worked the current way for a very long time, and is intended to provide value for players who don't want to have to keep tapping to get somewhere. I also generally dislike adding complex conditional logic to basic game actions, as their behavior should be as direct and straightforward as possible. This is why pathfinding always picks the shortest valid route to a destination, even in cases where that route may not be ideal for other reasons.
