### ISSUE TITLE
Build jni libs from source.

### ISSUE THREAD

**Issue by krt16s** [00-Evan/shattered-pixel-dungeon#113]
Source code includes two `.so` files. Could you wire gradle to build them as well? Or provide the source and build instructions?

**Comment by 00-Evan** [comment]
These .so files are there to provide java hooks for two openGL calls not present in android 2.2 (see java file here for comments explaining this: https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/SPD-classes/src/main/java/com/watabou/glwrap/FroyoGLES20Fix.java)

Source for those files wasn't provided so that the android NDK wouldn't be necessary to compile the project. Given the nature of F-Droid wanting to ensure 100% FOSS I totally understand why you'd want the source regardless of this. I'll add the source for these files in a manner that makes building them optional. Would creating a new directory in SPD-Classes called jniSources, with the .c and .mk files be sufficient? They would not be picked up by gradle, but could be built as a separate step prior to the main build process.

Also, as another option, for the purposes of F-Droid not including these binaries should have no ill-effect, as it seems that F-Droid requires api level 10 anyway. These .so files are only ever used on api level 8.

**Comment by krt16s** [comment]
Thanks for clarifying. I enable the build with the removed so files, adding the source file is fair enough for me. You dont even have to wire it up in gradle, a simple shell script we can execute before building is fine, too.

**Comment by 00-Evan** [comment]
Source files added in commit bd12b7003de1aca4ac5ca43e0e8d292884e96a5b
Gradle task added in commit 0688896113884ca5104ab3093c612ba1ed27a24b

F-Droid should now be able to build the JNI library by running the gradle task SPD-classes:ndkBuild prior to assemble.

I've created a merge request on the F-Droid repository to change the metadata both for the latest update (0.4.2b) and to compile the JNI libs from source: https://gitlab.com/fdroid/fdroiddata/merge_requests/1694
