### ISSUE TITLE
Seems Like Too Many Doors

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1140]
![Screenshot_20221028-210824](https://user-images.githubusercontent.com/91638992/198856724-6b6004dd-23dd-4ece-a722-ff45fa31efc8.png)

This isn't a bug report or feature request but seemed worthy of posting. I believe you've done some recent work on streamlining levelgen's use of extraneous doors based on my experience in recent runs but this, in my memory, is 1 of the most egregious examples I've ever come across: 10 doors are able to fit in 1 screen @ my phone's default setting (1 in upper left, mostly concealed by the portrait), 3 of which were secret (3rd from the left, 2nd from the top, & 3rd from the right). I found another secret door connected to the garden room @ the top during ascension but that was just outside of being able to fit w/ all the others. This wasn't even a secrets depth but over 1/3 of the doors in a relatively small area were secret!

Not only is it nonsensical for there to be secret doors single tiles away from normal doors, it makes it tedious to get a good exploration score. I make this thread primarily so the image above can be used as a reference for improving levelgen.

1 idea I have is for there to be a proximity check before placing a secret door. Is there a normal door within a couple of tiles?? Place a normal door instead & look elsewhere to put the secret.

Another idea I have is for there to be an accessibility check for rooms joined by open space. Conjoined rooms appear as 1 large room but will almost always have redundant entrances to that space, usually in the form of a wraparound hallway that has a couple of doors in quick succession. Would it be possible to implement some logic for joining redundant doors when rooms are??

No need for a detailed response here but I hope you can make use of the above image & that it gets your noggin joggin'.

P.S.: This is from depth 12 of the daily from 2022-10-29, v1.4.2.

**Comment by Pr0methean** [comment]
The algorithm to solve this probably involves connected and/or biconnected components in a graph, with either rooms and corridors or individual floor tiles as vertices.

**Comment by 00-Evan** [comment]
Levelgen actually hasn't significantly changed since v0.9.1

It it intentional that the game can generate some highly compact and interconnected levels, the caves generally contain the most prominent examples of this. I'd rather not put in a check to limit the number of doors or secret doors, especially given that would lead to players meta-gaming. "I have found X doors on this floor, there can't possibly be another one."

While I do appreciate that maxing exploration score can be annoying (the same goes for boss score as well, as we discussed previously), this is also somewhat intended. I really want to avoid players being able to get consistent max scores (as if they can then score starts to love meaning), and so getting a max score should not be a smooth process.
