### ISSUE TITLE
[Feedback/Balance issue] Weird difficulty spike on 4th level - dwarven city

### ISSUE THREAD

**Issue by vahaala** [00-Evan/shattered-pixel-dungeon#1154]
First of all - I'm not sure if this is the correct place for feedback on balance, if it isn't - please let me know where I can post it properly. Also, it regards the mobile version in case the Steam one is different in any way balance/content wise.

Anyways, I'd like to ask about the balance inbetween 3 and 4rd level - transition from the mines to dwarven city. Despite doing more than okay in the mines, going through them rather comfortably and somewhat easily, with good gear and occasional heal here and there, everytime when I enter dwarven mines, I get absolutely steamrolled and obliterated within the first 2-3 floors of that level. I remember one time as an example - plate armor +4, good enchant on it (I think it was that stone enchant, which changes evasion to damage blocking), a nice weapon, 3 blessed ankhs, a bunch of potions of healing, ring of magic damage reduction and I think of fortitude as well, the one that reduces physical damage the closer you get to death. All that, 3 ankhs, 5+ pots of healing, gone before I got to 3rd floor of the city.

Normally, I would put it down to bad RNG, or hate of the RNGesus if you will, since I had died a lot of times even in the very first floor of the sewers. But with dwarven city it happens way too consistently, and I never seem to gather any gear that would be "good enough" for those dwarves. I think the issue is mainly the abundance of ranged mages, they hit really hard from a distance, debuff you in various ways, and there's only limited ways in which you can deal with the magic damage they deal.

I get it, this is a level pretty far in the game, it is supposed to be hard, but I can't shake off the feeling that there's this big difficulty spike still, even when compared to previous one.

**Comment by 00-Evan** [comment]
The game does get harder as it progresses obviously, and ultimately this can end up feeling like a difficulty spike if your average run starts running out of gas at a certain point. I do track gameplay data over all players who have beaten the game at least once, and the game's overall difficulty curve is quite smooth (death % steadily goes down after spiking in the sewers). There's a little bump on floors 11 and 16 (as weakened players get finished off after the boss), but otherwise the city has a slightly lower % kill rate than the caves.
