### ISSUE TITLE
Trammeled Sungrass

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1160]
This may be related to the fix made in #1115.

I threw a sungrass seed, used the hourglass, & trampled past the plant:

![Screenshot_20221114-154321](https://user-images.githubusercontent.com/91638992/201798073-e8c783fe-800d-457a-9353-15a64395c7cd.png)

I see @ least 2 issues here:

1) Sungrass didn't give herbal healing even tho I'm playing warden.
2) Rejuvenating Steps proc'd but no furrowed grass appeared in place of the sungrass.

The orange 1st aid symbol is from elixir of might's buff. Herbal healing grants a white 1st aid symbol, conspicuously missing in the screenshot above.

Here, sungrass' description says it should benefit the warden if she walks away after trampling:

![Screenshot_20221114-154301](https://user-images.githubusercontent.com/91638992/201798930-7621433b-cd20-4ab8-8b94-1535b5e28555.png)

Here's a screenshot of the description of Rejuvenating Steps just after trampling normal grass during a time freeze:

![Screenshot_20221114-155745](https://user-images.githubusercontent.com/91638992/201799280-d16c5b37-e650-4751-9997-f2ea69ddc73f.png)

I should've taken another w/out the box but this @ least lets you compare the cooldown to the 1st pic. Currently, Rejuvenating Steps will proc during time freeze & immediately generate furrowed grass but it seemingly doesn't if there's a plant in the way.

I imagine these issues apply to several warden/plant interactions during time freezes, destroying plants for no benefit (in some cases) & leaving no furrowed grass despite Rejuvenating Steps going on cooldown.

**Comment by 00-Evan** [comment]
The first one is intended. The plant is not trampled, and does not give its effect, until time freeze ends. Once time freeze ended you were no longer standing on the plant. It's not so much that the plant's effect is failing to travel with you as it is that you weren't there at all when the plant activated.

The second one looks like it's happening because the game is processing a second step where the plant is after time freeze ends, which causes the grass to trample. Will look into having time freeze directly trigger traps/plants instead of doing an entire step effect.

**Comment by 00-Evan** [comment]
fixed in commit ac77531603d9af7a87fc53583c22f53f344b31ae
