### ISSUE TITLE
Strange Freeze

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1193]
![Screenshot_20221209-222827](https://user-images.githubusercontent.com/91638992/206877739-fc6a430a-22bf-4d88-849c-60c701273572.png)

There's a lot going on here but the main thing is the neverending turn clock. It just kept spinning although I was able to tap on the hero's status effects & access the menus. I quit to the main menu, reloaded the game, & was able to continue after that. 1 strange thing was that it wasn't the hero's turn on reload; I don't believe I've ever seen that in my history w/ this game.

I entered the room from the east. A shaman became visible & launched a magic bolt. I blinded him by throwing a torch & took another magic bolt to the face from outside vision to the west as I was closing w/ the 1st shaman. I kept closing, using the shaman as cover to block shots coming from behind him. By the time I got in front of the shaman, more enemies had appeared (6 in total; hard to see but there's a bat flying in the web) & the DM-200 dropped a toxic cloud on me. I decided it was time for a tactical retreat. I spent a turn in the cloud throwing a stone of aggression @ the berserker & then stepped out diagonally. This is when the game froze & I snapped the pic. On reloading, the berserker took some dmg from his friends but I don't think the cloud expanded because I was able to move away orthogonally w/out taking dmg during my retreat. I wish I'd had the presence of mind to take another pic but alas.

My theory is that some sort of pathing conflict caused the freeze, possibly complicated by the stone of aggression &/or the web. This seems like a rare incident & I'm unsure of how it might be reproduced but thought I should report it anyway in hopes you'd find something useful here. Researching for this report I found 2 similar issues that might be related to this 1: #390 & #1141.

**Comment by 00-Evan** [comment]
When animations play the game pauses user input and waits for the animations to complete. This occurs in rare cases where signals get mixed up and the game never resumes accepting input. There are other instances of this popping up (as you mention) but they likely have completely unrelated causes. tracking this sort of issue down is extremely difficult, especially because it is basically impossible to reproduce.

However, there are some oddities with spinner webbing animations that I am already fixing in development. There's a good chance that will correct this specific freeze case incidentally.
