### ISSUE TITLE
Alchemist's Toolkit only remembers "best" potion combination

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#12]
When trying to work out the Alchemist's Toolkit potion combination, its description only remembers what it considers the "best" potion combination, even though other attempts may have provided additional information.  For instance, if you try potions A, B, and C, and get "one right and in the right place", and then try D, E, and F and get "one right but in the wrong place", you now know more information, but the toolkit only remembers A, B, and C.

Perhaps you could keep a log of attempts ("You make a note of the result."), and provide a "NOTES" action on the toolkit listing the attempted combinations and results?

**Comment by 00-Evan** [comment]
This is intentional. Part of the design of the toolkit is that the best strategy involves manually remembering past attempts. I like the idea of more experienced players deciding to keep notes on combinations themselves, rather than providing that information to everyone. It makes leveling the item more challenging, and better rewards experienced players.
