### ISSUE TITLE
Game randomly gets stuck during gameplay

### ISSUE THREAD

**Issue by 133794m3r** [00-Evan/shattered-pixel-dungeon#120]
I am on version 0.42a since f-droid isn't building 0.42b but since that hotfix was just for a crash(which i've experienced) I think that this is something different. 

Basically you can't do any more turns in teh game, the menus etc. still work, you can go back to main menu, open up menu things but you can't move and the swirling hour-glass "wait" icon is shown and the game is just stuck in the loop. If there's a debug log flag or if it does write logs that can be read via alogcat i'll try to post the logs from it.

**Comment by 00-Evan** [comment]
This is infact fixed in 0.4.2b, see commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/c6d86f42abcf026478b6b3424b7d46d93ffb24e8

It's looking like it makes the most sense to build 0.4.2b on F-droid using the same method as 0.4.2a (killing compatibility with android 2.2 by not building the native libs) and giving a full build with native libs another try with 0.4.3.
