### ISSUE TITLE
Enemies turned into wraiths don't drop thrown weapons

### ISSUE THREAD

**Issue by ResCXsention** [00-Evan/shattered-pixel-dungeon#1216]
I'm not entirely sure what happened, but I lost a dart after using it on a soul marked enemy. It converted into a wraith when it was hit with the dart, and I never saw it again.

I did search the current floor and the one below, in case the wraith died over a chasm and dropped it. I think it should've let go of the weapon before converting instead of voiding it.

**Comment by 00-Evan** [comment]
That talent doesn't actually turn enemies into wraiths, it spawns a separate wraith after the enemy dies.

Did you throw more than one tipped dart at that enemy? Currently there are rare cases where runs with extra dart durability can lose a tipped dart in specific cases, this is already fixed in development.

**Comment by ResCXsention** [comment]
Ah, I suppose I might have made a mistake somewhere.

Also no, it was a regular dart fired from a crossbow.
