### ISSUE TITLE
HiDPI devices keep zoom setting in portrait mode.

### ISSUE THREAD

**Issue by 133794m3r** [00-Evan/shattered-pixel-dungeon#122]
The UI scale slider works in portrait but in landscape the buttons are barely pressable especially the corner buttons IE the settings one with a case on your phone.

I don't know how you handle it atm, but the scale in portrait is fine, but landscape seems to be using something way smaller.

![screenshot_2016-10-06-18-28-43](https://cloud.githubusercontent.com/assets/599849/19173038/25935576-8bf3-11e6-9a68-3af793fed37b.png)

Now then, it doesn't look it in the screenshot but that settings button is damnd near impsosible to press. Now then from the main menu the Display Scale is set at 5x I don't know if that scale is also usd in portrait or not bu tit doesn't feel like it. I feel like portrait just uses 4x scale and doesn't give you the option to set it to use 5x.

**Comment by 00-Evan** [comment]
what device do you have?

**Comment by 133794m3r** [comment]
Moto X I noticed it first on the rest of the UI isn't scaling up right I am backing up my galaxy nexus or I'd check there too but i don't believe it's keeping the scaling factor.

**Comment by 00-Evan** [comment]
So the Moto X and Galaxy Nexus both have a 720x1280 screen (1280x720 in landscape).

The minimum internal resolution for Shattered is 135x225 in portrait, and 240x160 in landscape. The game also needs to run at at least 2x scale because some UI elements (such as text) require the extra detail.

So based on this your phone would be able to manage 5x scale in portrait, and 4x scale in landscape. 5x scale would be impossible in landscape as your device would need a resolution of at least 1200x800. Sounds like this is working as intended, landscape is also primarily designed for tablets.

I am however working on a new setting called 'power saver' which will be available in 0.4.3, which renders the game at a reduced resolution and scales it up to fit your screen. There is a loss in visual fidelity, but this would increase the size of the UI in your case.

**Comment by 133794m3r** [comment]
Welll that's something I didn't realize before when settng the scale, do you do any sort of post processing at all on the sprites? Ala billinear filtering or bicubic? also that battery saver sounds nice and since the sprites are so tiny already i can't see the loss in fidelity being that great.

**Comment by 00-Evan** [comment]
There is anti-aliasing applied to the rendered font (android handles this for me and spits out a texture which the game uses), but other than that shattered doesn't do much aside from display textures on quads with some tinting.

The loss in fidelity somewhat varies by device. It's most notable on very old phones with resolutions like 480x800. At 720x1280 it will be noticeable but probably not that severe. On very high density phones (1080p and higher) it's very hard to tell any difference.

**Comment by 133794m3r** [comment]
Also One thing that I'd say about batery saver, think about reducing the framerate or at least capping it at 30, since it's a turn based game I seriously doubt the difference between 30, 35, 45 etc will be that great for a vast majority of players. I know your last update I think you said most people were getting at least 25fps and in some cases 30fps.

**Comment by 00-Evan** [comment]
I don't want to make a framerate limiter a necessary part of power saver as for a lot of people it would seriously hinder the game experience, far more than some blurriness which isn't even noticeably on high end devices. Power saver also allows some very low-end phones to reach 60 fps when they otherwise couldn't.

At the moment almost every device gets 60 fps (and could easily push more), very old phones with gpus like the Adreno 200 are getting between 35 and 60 fps depending on resolution.

A framerate limiter could definitely happen but I would want it to be a separate feature.
