### ISSUE TITLE
You break the GPL with the beta release.

### ISSUE THREAD

**Issue by TadaCZE** [00-Evan/shattered-pixel-dungeon#1237]
You released the recent beta without accompanying source code, which violates the GPL. This would be okay if you had all the copyright to it, but it is based on watabou's code. So what you did is illegal.

You should release the code for it.

**Comment by 00-Evan** [comment]
I'm afraid I have no plans to release the code.

In the past beta code was released and it led to other developer taking half-finished features from Shattered before they were released to the live game. I then got accused of copying from them. I withhold the source code for the duration of the beta as a means of protecting myself and ensuring that code from half-finished buggy updates isn't propagated by other developers.

If Watabou has any issue with this I would be happy to discuss it with him, but frankly I would think it would be a waste of his time. Consider that simply releasing the game on the App Store (there is precedent) and probably Google Play (no precedent that I am aware of) is also in violation of the GPL license, yet Wataou is clearly fine with those.

**Comment by TadaCZE** [comment]
Well, I kinda understand.

But just because someone else does a bad thing and gets away with it doesn't mean that it isn't a bad thing. And, simply releasing it on app stores is _not_ a violation, releasing it without providing source code is.

**Comment by 00-Evan** [comment]
Releasing the source is not the only requirement of the GPL:

```Some devices are designed to deny users access to install or run modified versions of the software inside them, although the manufacturer can do so. This is fundamentally incompatible with the aim of protecting users' freedom to change the software.```

written later again in legalese:

```"Installation Information" for a User Product means any methods, procedures, authorization keys, or other information required to install and execute modified versions of a covered work in that User Product from a modified version of its Corresponding Source. The information must suffice to ensure that the continued functioning of the modified object code is in no case prevented or interfered with solely because modification has been made.```

In short, any distribution of Shattered which is not 'user modifiable' is in violation of the GPL. Both Android and iOS use mechanisms for this (security keys on Android, developer certificates on iOS), and are therefore in violation of the GPL unless I provide those keys/certificates. I am not going to provide those keys for obvious security reasons, as well as due to Google/Apple developer ToS.

Basically, following the letter of the GPL means that pretty much every PD version is in violation of it.

**Comment by TadaCZE** [comment]
Once again, that is just not true. That clause is there to prevent what Stallman would call "Tivoization", a practice where some _device manufacturers_ use GPL software in their firmware. On android just using a different key and reinstalling the app is enough to bypass the restrictions (the GPL says _required to install and execute_ and that is not required) and there is precedent for releasing GPL'd apps on Google Play for much the same reasons. Even the inclusion of the proproetary Google Play Services would be okay, as it is a system library and you don't distribute it and as such falls under the system library exception.

So all android versions are fine. In regards to iOS, that is a gray area and as App Store applies additional licensing restrictions incompatible with the GPL it is in fact illegal. But it is probably okay to just compile the app for the iOS target and publishing here as any user that manages to install it must necessairly have a device set up in a way to allow installation of third party code.

Well, anyway, if apple knew about this, they would probably take it down. But I'm not going to spoil the fun by reporting it, it's not much of a problem anyways.

Well anyway you are almost GPL compliant, just make the extra step and release the code.

**Comment by 00-Evan** [comment]
Firstly, apologies for talking down to you regarding the license. I'm no GPL expert, but am used to talking with people who's understanding ends at the requirement to distribute source.

I would argue that clause never states that it applies to any particular type of software, and that on Android the modified code is at least interfered with. The requirement to uninstall/reinstall is more than an inconvenience, it also deletes user data for that application. That clearly is a barrier to installing the modified code, if unmodified code has previously been installed. Regardless, the iOS case is more relevant and there are examples of apps being taken down from the iOS AppStore simply for being GPL (VLC, most famously). It's why libraries like mobiVM distribute binaries under Apache 2, so that they can actually be used by iOS developers.

I have an agreement with Watabou separate from the GPL which allows me to legally distribute the game on iOS. I didn't seek this agreement specifically because of how I do betas, but rather so that the game could be on iOS at all. If Watabou wants me to stop releasing betas in this way I will obviously comply, but I'm not willing to release partially completed source code, so it would just mean that nobody gets beta releases.

**Comment by TadaCZE** [comment]
Well, if you have an agreement about it with him, I guess I cannot complain.

**Comment by TadaCZE** [comment]
And it makes sense to take down VLC under their terms. It's made by many people who individually own parts of the copyright and nobody owns the whole thing, so nobody can sign a licensing agreement with Apple which they require.

**Comment by TadaCZE** [comment]
And whether the android security model

**Comment by TadaCZE** [comment]
And for example I installed a Magisk module which allows me to bypass signature verification and downgrade prevention while installing apps. Does this make me a person to whom distributing is legal and to others not? No that is ridiculous and a court would probably not interpret it like that. Aside from that, there are a lot of apps under the GPL distributed for Android and I have found no instance of anyone complaining ever.
