### ISSUE TITLE
Duelist still locked for existing players with a win

### ISSUE THREAD

**Issue by wknoben** [00-Evan/shattered-pixel-dungeon#1271]
I'm on 52/315 successful runs but cannot immediately start a new game with the duelist. Restarting does not change this. 

This is on v2.0.0 on Android, obtained through Google Play (updating my old install). 

Not a big deal but I figured it might help knowing about this.

![Screenshot_20230313-115420](https://user-images.githubusercontent.com/45757529/224787524-78c7a813-a2aa-4700-be6c-f05f612ad9e7.jpg)
![Screenshot_20230313-115429](https://user-images.githubusercontent.com/45757529/224787548-1c635e95-a453-4a92-8acd-0e614357e490.jpg)

**Comment by 00-Evan** [comment]
Can I see a screenshot of your badges? The game doesn't check for a win in the rankings specifically, but whether you have the 'victory' badge.

**Comment by wknoben** [comment]
Here you go:

![Screenshot_20230313-121830](https://user-images.githubusercontent.com/45757529/224793909-01544a2a-89b6-4bed-84ff-9402d6ce5ec3.jpg)

**Comment by 00-Evan** [comment]
Hmm, will look into this and see if I can reproduce it and fix for v2.01, though I imagine by that point many people will have unlocked her normally.

**Comment by mmacura311** [comment]
had the same issue. On my phone finished the game as a warrior, huntress and a rogue, The "victory" badge is there. But still was unable to select the Duelist character.

**Comment by wknoben** [comment]
@mmacura311 As a workaround, the normal unlock (equip a tier 2 weapon) worked for me.

**Comment by LeahLuong** [comment]
Same thing for me: Android phone, SPD update obtained from Play Store. Was stoked to try the new class but blocked @ the hero selection screen despite having many more than 1 successful run on my game.

Don't really feel like starting a run I don't intend to finish just so I can do something the "Changes" notes I should already be able to do. Guess I'm waiting on the fix for this . . . 

![Screenshot_20230319-161622](https://user-images.githubusercontent.com/91638992/226220690-d0f7ef9b-ea91-44f7-9514-0c4af135d25b.png)

![Screenshot_20230319-161558](https://user-images.githubusercontent.com/91638992/226221252-c0e4641d-681e-42fc-b847-2668f0c38a91.png)

![Screenshot_20230319-173549](https://user-images.githubusercontent.com/91638992/226221269-c8e41060-0044-4574-9bad-90897339df05.png)

Might the badge system have something to do w/ this bug?? There's a new 1 for unlocking the duelist & perhaps that's taking priority from automatically unlocking for vets.

**Comment by 00-Evan** [comment]
fixed in commit 1804551ceb720859ec071f71d518df297f802b66
