### ISSUE TITLE
No 2.0.0 on F-Droid

### ISSUE THREAD

**Issue by Lodger-test** [00-Evan/shattered-pixel-dungeon#1272]
There were no 2.0.0 betas, no 2.0.0 release on F-Droid. Is there another trouble with the build?

**Comment by 00-Evan** [comment]
I have no control over how F-droid distributes updates. They are usually on a delay of a couple days or more, and do not distribute beta builds.

**Comment by zacchiro** [comment]
@00-Evan I completely understand it's not your responsibility to update the f-droid package.
Still, suggestions on what's the best workaround to install 2.0 for users that previously installed an f-droid version of Shattered Pixel Dungeon would be *super nice* to have.
What I've tried (to no avail):
1. upgrade via f-droid: obviously not working as the [last version there](https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/) is currently 1.4.3
2. install via play store: doesn't work as play store just offer an "open" button rather than the ability to override the previous f-droid install with a newer version from play store
3. manually installing the .apk from github releases: doesn't work either, as the package installer reports that the package "conflicts" with another installed one
4. uninstalling the f-droid version and installing the play store version: I haven't actually *tried* that, because I suspect it's going to erase all previously saved data (if that is *not* the case, this could be the best workaround)

Any suggestion?

Thanks a lot for Shattered Pixel Dungeon, it's an amazing game.

**Comment by 00-Evan** [comment]
@zacchiro sadly that last option is the only one, and you will lose save data unless you have root and can manually copy it. I really don't want to do something like ask the F-droid people put up a warning, or ask for the app's removal entirely, but I do really dislike how F-Droid users basically end up 'trapped' on a version that sometimes takes more than 2 weeks to receive a major update.

**Comment by 00-Evan** [comment]
@Lodger-test Shattered does not have a 3rd party repo, and I have no interest in investing the time into officially supporting F-Droid at this point.

**Comment by Lodger-test** [comment]
@00-Evan, that's why there is no link to F-Droid on the Shattered site?

**Comment by 00-Evan** [comment]
@Lodger-test Yes, take a look at https://github.com/00-Evan/shattered-pixel-dungeon/issues/479 for more context as to when/why I came to that decision.
