### ISSUE TITLE
steam version crashes immediately on launch on M2 macbook air

### ISSUE THREAD

**Issue by eScribMac** [00-Evan/shattered-pixel-dungeon#1291]
happy to help debug/build on my computer if it can help address this issue

Here is the crash log: 

https://pastebin.com/xB7emcuq

**Comment by 00-Evan** [comment]
Code signing errors are usually caused by something misconfigured on the user machine. Try making sure your system clock is correct, restarting your computer, and updating to the latest macOS if possible.

**Comment by eScribMac** [comment]
I tried restarting, and my system clock is correct. Does this game only work with MacOS Ventura? I'm on the latest version of Monterey, and I tried on another computer running Monterey and the same thing happened.

**Comment by 00-Evan** [comment]
The game should work on much older macOS versions, although the only device I have for direct testing is using macOS 13, which is why it's the reccomended OS version to use. 

A few questions:
- Is that other device also using an M2 processor?
- did prior versions of Shattered (before v2.0.1) run fine on either device?
- Does the v2.0.1 .app distribution here on github work on either device?
