### ISSUE TITLE
Modernize Shattered's Android Backup Handling

### ISSUE THREAD

**Issue by EmberHeartshine** [00-Evan/shattered-pixel-dungeon#1294]
Per #226 it appears that adb backups have been implemented for SPD, but I recently tried to fetch the file to move to a new device and I didn't get anything. Was the allowBackup flag re-set to false? This is quite a bummer since I use the F-Droid version of the game and can't transfer anything through Google Play Games.

**Edit:** Also the origin device in question, a Samsung Galaxy S20 5G (US variant), cannot be rooted by any known method.

(EDIT: see here for actionable part of issue report: https://github.com/00-Evan/shattered-pixel-dungeon/issues/1294#issuecomment-1496382628)

**Comment by TheYsconator** [comment]
Looking at the code, I wouldn't say the flag has been re-set. Note that runs-in-progress are not included in backups. Per [AndroidBackupHandler.java ](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/android/src/main/java/com/shatteredpixel/shatteredpixeldungeon/android/AndroidBackupHandler.java), only rankings, badges and the journal are included.

Are you not even able to restore these three things?

**Comment by EmberHeartshine** [comment]
Nothing at all. I don't have the source device on-hand but I can in a few hours.

**Comment by 00-Evan** [comment]
Unfortunately ADB backup is deprecated by Google, I'm not sure how well it works on more modern android versions. I also think that ADB backups are dependent on the security key of the application, and so the F-Droid and official versions of Shattered may not be interoperable in that way either. There's nothing that Shattered itself can do about that.

**Comment by EmberHeartshine** [comment]
> Unfortunately ADB backup is deprecated by Google, I'm not sure how well it works on more modern android versions.

It isn't, though? I can't find anything in the Android documentation about that. (Also, of note, other apps and games worked just fine on these origin and target devices.)

> I also think that ADB backups are dependent on the security key of the application, and so the F-Droid and official versions of Shattered may not be interoperable in that way either. There's nothing that Shattered itself can do about that.

They aren't, as long as the package name matches the backup and restore will work.

> 00-Evan closed this as not planned

So, what, you're telling me that I'm completely SOL? Because I had the gall to upgrade to a newer device, I've lost 400+ runs? There are *no* other ways to retrieve this data if I don't have root? That's extremely user-hostile.

**Comment by TheYsconator** [comment]
Did using Google One backup, or the Samsung backup system? Those did work for me, and I believe they are generally the recommended way for backing up up and restoring on Android.

**Comment by EmberHeartshine** [comment]
Google services are not available for my devices, so no. And the new device is not Samsung, so that's also out.

It's just weird that pretty much all of my other apps ether have a built-in backup system (Mindustry, NewPipe, K9 Mail, et.c etc. etc.) or function perfectly well with ADB backup, but the one with a progression curve most strongly related to just time spent in-game does not have *anything* I can use.

**Comment by TheYsconator** [comment]
Oof, that's rough. I'm out of ideas; sorry.

**Comment by 00-Evan** [comment]
ADB backup has been marked deprecated since Android 10: https://issuetracker.google.com/issues/37130390?pli=1#comment29

After a tiny bit of digging, this might be the main culprit: https://developer.android.com/about/versions/12/behavior-changes-12#adb-backup-restriction.

I am not willing to put an import/export function into Shattered itself because it would be trivially easy to use it to cheat. I mentioned security keys in particular because some other users who were experimenting with ADB backup due to F-Droid's delay of the latest release noticed that it did work for the F-Droid version only, but not for F-Droid -> Official.

I closed the issue as there's nothing to be done about it in the code for Shattered, though you're welcome to keep discussing this, of course.

**Comment by EmberHeartshine** [comment]
If the import/export function for Shattered only includes past records, then how can that be used to cheat? As far as I know the leaderboards don't read those records and only update at the conclusion of an active run. If the leaderboard function *does* read old records, well... that's something that might need to be corrected.

That being said... you might want to clue in Noodlecake (Punch Quest), Ninja Kiwi (Bloons TD 5), Anuken (Mindustry), and Dino Polo Club (Mini Metro) because I was able to successfully either use the built-in backup or ADB backup to transfer their files from the origin to the new device.

**Comment by 00-Evan** [comment]
My main concern would be a newer player seeing there's an export/import button, Googling some save data, and importing it in order to instantly unlock all badges and journal entries. There would be ways to reduce the effectiveness of that but it would be a losing arms race. Obviously I can't prevent all cheaters, but where possible I'd like the user to at least have to be entirely out of the game to do it.

I took at a look at the source code for mindustry briefly, which led me to realize that it seems Android has, of course, completely changed the mechanisms for declaring backup files at least twice since Shattered's backup handler was implemented. I will look into those mechanisms as an enhancement, but I can't give any assurance that adding that functionality will cause ADB backups to start working for Shattered, especially seeing as, per google's own documentation, ADB backup no longer works for app data on Android 12+.

**Comment by 00-Evan** [comment]
I've now run some more tests on this, and have opted to not make changes to the game's backup code right now.

I ran two tests, using the Android 13 SDK on my Android 12 device:
- ADB backup produced an empty backup when running the production version of the app, and worked correctly for backup/restore when using the debug version of the app. This is consistent with the documentation here: https://developer.android.com/about/versions/12/behavior-changes-12#adb-backup-restriction.
- BMGR (utility for google cloud backups) correctly backed up and restored the production version of Shattered Pixel Dungeon.

Based on this, it doesn't seem like moving to the more modern XML-based backup definitions will change anything aside from potentially introducing bugs in logic that really needs to work correctly. I'm sorry that ADB backup isn't working for you, but based on my testing that's happening because Google has killed it.

It does absolutely suck that there doesn't seem to be a utility that allows for backup/restore within plain android that doesn't involve root though. If there is a way to accomplish such a thing that doesn't involve Shattered just saving its own data to user storage, then I'd be happy to look into it.
