### ISSUE TITLE
Typo in message: "Welcome back to the level N of Pixel Dungeon!"

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#13]
The "the" shouldn't be there.

**Comment by 00-Evan** [comment]
While I completely agree this is grammatically incorrect, I made the decision to leave a few of these in the game. They have been around since the beginning and many players have a certain sentimental attachment to them. I will correct any typos from the source that obscure information or readability though, obviously.
