### ISSUE TITLE
Lethal Haste 2 Grants More Than 3 Turns

### ISSUE THREAD

**Issue by LeahLuong** [00-Evan/shattered-pixel-dungeon#1303]
![Screenshot_20230412-172436](https://user-images.githubusercontent.com/91638992/231624105-77805048-5716-4804-a555-b3741e62cbe7.png)

I couldn't find any synergy w/ other talents that'd explain the extra haste. My hero was wearing a +1 ring of energy but I don't think that's the culprit. I slew several enemies & checked the bonus for the same result ea. time. Perhaps this is working as intended but seems like a disrepancy to me.

By the way, duelist is quite fun to play. She may be slightly overpowered right now but I don't think she outstrips the huntress. The wording on some of her subclass talents is a little ambiguous & I need to test some stuff out before I think I understand it. 1 thing that struck me is the quick weapon swapping talent feels like a waste if 1 ends up choosing the champion subclass; champion can freely switch betw/ primary & 2ndary & the talent only comes into play if 1 plans on using a 3rd weapon ability.

**Comment by 00-Evan** [comment]
This is due to some oddities in buff duration display, the actual effective duration of haste is 3 turns, you will get 9 moves worth of it.

This occurs because buffs expire at 0 duration after the hero acts, but having a buff display "0 turns remaining" is odd, so the game quietly adds 1 turn. This then gets even more awkward when the hero is moving based on partial turns.
