### ISSUE TITLE
Charmed and ward wand

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1330]
Ward's damage will not reduce the time of charmed

**Comment by 00-Evan** [comment]
This is intended if the charm effect originates from a wand of transfusion of the transfusion elemental blast effect.

**Comment by Lyx0527** [comment]
I can't understand why it's so designed. Charmed can even be cancelled due to hunger damage,  deferred damage and allies attack, but cannot be cancelled by magic damage from ward. 
Do you want to have better coordination between transfusion and ward

**Comment by 00-Evan** [comment]
Yes it's intended so that using transfusion to charm enemies can be more useful while you also have allies present.

**Comment by SujayDalai02** [comment]
@00-Evan I have never seen an instance where charm on myself getting cancelled due to hunger damage or deferred damage though. Is it possible?

If it is, it can be helpful while dealing with succubus.Their charm is real annoying.

Also, while charmed by succubus, I can't melee her, but ranged(thrown or spririt bow) and wand damage on the same succubus works fine. Is it intended?
