### ISSUE TITLE
F-Droid recommends to immediately remove Shattered Pixel Dungeon due to known security vulnerability

### ISSUE THREAD

**Issue by f45tb00t** [00-Evan/shattered-pixel-dungeon#1392]
Hi,

I would like to get to know why F-Droid recommends recently to remove the game immediately?

https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/

```
    This app has a weak security signature
    This app contains a known security vulnerability
```

Reference: https://f-droid.org/en/packages/com.shatteredpixel.shatteredpixeldungeon/

**Comment by 00-Evan** [comment]
See #1390 and #1391

This is the second time this has happened to Shattered, it is a detection error on F-Droid's end which I have received no warning about and have no real recourse against. F-Droid is not an official distribution of the game, largely because of bullshit like this. Personally I recommend that you uninstall the F-Droid version and download the game from this repository's releases page.
