### ISSUE TITLE
More Music?

### ISSUE THREAD

**Issue by TheShadowOfHassen** [00-Evan/shattered-pixel-dungeon#1412]
I play the game on mute because after a few hours of playing in each level the music gets old. I play Shovel Knight dig and was starting to have the same problem with their first stage. However, recently they added another track and it fixed it.

So I was wondering maybe you could a page from their book and have a couple tracks for each level and have one chosen on random to play throughout the stage. I saw somewhere that someone wanted the original pixel dungeon music back and you could even add something to make that play 1/10 of the time or something.

If your curious. The demon halls is the only music that hasn't gotten old.

**Comment by 00-Evan** [comment]
This is actually something I'm been talking a bit about with Shattered's composer, as he recently finished a bunch of work on Black Reliquary and has some spare time now. No promises but more runtime for the region tracks is a strong possibility.

Also, part of the reason the game's current tracks are relatively short is due to a limit imposed by Google Play. Their 'instant app' functionality requires a game's download size to be no more than 15mb, a limit Shattered is currently rubbing right against. Instant app users are an increasingly tiny portion of Shattered's playerbase though (and can always just download the game normally if they choose), so I'm less concerned about the limit now than I have been before.

Closing this as the question was answered, in future you might want to email me with queries like this.
