### ISSUE TITLE
Missing key for locked room

### ISSUE THREAD

**Issue by spxdd** [00-Evan/shattered-pixel-dungeon#146]
This happens to me almost every game, I cannot enter the room because I cant find the key.

I verified this is a bug many times by searching every wall for a hidden room that may contain a key but not finding one. Sometimes I use a scroll to reveal hidden rooms to again find out the only hidden room is the locked room.

Once, I had ethereal chains and I was able to enter the locked room and inside was the key to enter that same locked room. Also there was an empty well, don't know what that means.

Apart from this, sometimes I find a key but no locked door to use it on. I'm not sure if these were my mistake or there was another bug

**Comment by 00-Evan** [comment]
This is intended. Look for a way to enter these room from above.

**Comment by spxdd** [comment]
I didn't really understand, could you clarify?

So if there is a locked door and the only key in the level to open that door is inside that same locked room, how do I find a way to enter this room? I only managed to enter it once and that was by using ethereal chains. In that case I found the key inside the room and I opened the locked door from inside

**Comment by 00-Evan** [comment]
Look for a suspicious looking pit on the floor above. That empty well is a hint for this as well.

**Comment by OffifialMITX** [comment]
Are there otge

**Comment by 00-Evan** [comment]
On the floor above the one with the room that's impossible to enter, look for a room with a broken floor. In the empty space where the floor is broken, you should be able to make out a well in the darkness. Try jumping into the empty space.

**Comment by OffifialMITX** [comment]
I've noticed that already, that's not what I meant - said that it's *as well* one of the hints so I wanted to know of there are other hints too.

**Comment by 00-Evan** [comment]
Oh, sorry, I misinterpreted your question.

The well in the darkness is the only significant hint, although it is more direct if examined: "You can just make out a well in the depths below, perhaps there is something down there?"

**Comment by NickEckardt** [comment]
After reading the comments in this thread, I'm making the assumption that the mechanic is that I'm supposed to fall into the well such that I reach the lower room without taking damage. However I couldn't get this to work. I tried:
1) Float above the well and wait for the effect to wear off. This landed me in the room with the well, but not in it. I assumed the well would catch me. 
2) When the well was directly next to solid ground, I walked off the cliff and into the well. Again, I landed next to the well rather than in it. 

Am I still missing something?

**Comment by 00-Evan** [comment]
> 
> 
> After reading the comments in this thread, I'm making the assumption that the mechanic is that I'm supposed to fall into the well such that I reach the lower room without taking damage. However I couldn't get this to work. I tried:
> 
>     1. Float above the well and wait for the effect to wear off. This landed me in the room with the well, but not in it. I assumed the well would catch me.
> 
>     2. When the well was directly next to solid ground, I walked off the cliff and into the well. Again, I landed next to the well rather than in it.
> 
> 
> Am I still missing something?

The well is just in there as a visual hint so that players can better understand that's the way to enter that locked room. You are intended to take falling damage when jumping down.

**Comment by NickEckardt** [comment]
Thanks for the quick response!

I don't think I would have figured out that this is intended behavior, I'm wondering whether that's just me or if other players are similarly confused. If it is the case that others are confused by this, maybe it would be possible to add a few more hints or change the functionality a bit? I'm nowhere near a game dev, but here are a few rough ideas I have:

1) Provide additional hints on the lower floor. An example would be changing the well to a fountain, and then providing text such as "You can hear water splashing". If this text is visible both to the player when they're in the room above and when they try to open the locked door below they're much more likely to draw the connection. Also, a fountain normally isn't deep enough to break ones' fall, so players should be less likely to make my mistake. 

2) Go with the approach where the well catches your fall. I think this would be best with the mechanic of finding a potion of levitation on the same floor. When you fly up to the well it could give you some text like "It's a long way down, but it you can just make out a well which may break your fall". Players would have to use the potion of levitation to fly over to the well first. 

Thank you for listening to my suggestions. Other than getting stuck on this for the last few hours, I've been loving the game so far. 

Thanks for all your work!

**Comment by TheYsconator** [comment]
I'd vote against making the wells more obvious, and against allowing players to get down safely.

For making them more obvious (to players that don't know the trick of having to jump down there); there's quite a lot of little tricks in the game that. Once you know some of them, they will help you get further in the game, for the rest of your games. Some tricks are quite obvious (the dew vial always drops on the first floor, on floors 2-4 there's a 'quest', special rooms can require a potion to solve..., ...which can help you identify the potion, and many others), whereas others are way less obvious (which I will not mention to prevent spoilers). Point is; in my opinion, this 'you gotta jump down in that room' is just another 'trick to be learned'. Some players may figure it out in their tenth game, whilst others may be a bit slower. Evan simply spoiling these tricks (this one included) would have ruined a significant part of discovering the game for me.

As for allowing players to jump down without taking damage; I consider the locked-room-with-well a 'mid-level' trick, and in my opinion a 'high risk, high reward' goes quite well (hehe) with it. Those rooms can contain quite valuable treasures, but no one (except, perhaps, the 'floor completionist' in you) is pushing you to grab its rewards.

I'd prefer keeping this like it is, because changing it like suggested would make this yet another 'low-level trick'.

**Comment by OffifialMITX** [comment]
Personally, I can't remember being confused that you were intended to jump fown the pit, and floading over the well never crossed my mind. The latter may be because I already noticed that the floors' layout foesn't physically vorrespond to each other.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
