### ISSUE TITLE
Rendering issues on S22 Ultra (v2.1.4)

### ISSUE THREAD

**Issue by darkraiN2** [00-Evan/shattered-pixel-dungeon#1469]
I recently switched from my old Huawei P30 Pro to a Samsung S22 Ultra (Exynos 2200) and I am encountering rendering issues frequently. Switchting to landscape mode and back seems to re-render the tiles and fixes the issue temporarily, but as soon as new areas are rendered it almost certainly happens again.

Screenshots:
![Screenshot_20230830-183646](https://github.com/00-Evan/shattered-pixel-dungeon/assets/143638664/11d28aa5-3e2e-417b-8c33-25fa2d374e8b)

![Screenshot_20230830-183702](https://github.com/00-Evan/shattered-pixel-dungeon/assets/143638664/38206c34-db6b-4f46-9553-8526e5761284)

**Comment by 00-Evan** [comment]
It doesn't look like you're playing an official release of Shattered Pixel Dungeon. See how the version code at the top right says 'v2.1.4-indev'? That means someone else built the ShatteredPD source code and incorrectly set the build configuration to debug instead of release.

I'm afraid I can't really provide support for versions of the game built by other developers, as they may contain code changes that cause errors like this.

**Comment by darkraiN2** [comment]
Huh, that's really weird. I migrated all my apps from my old phone. I'll re-download it from the app store now and check if this issue still occurs. Thank you very much for your fast reply.

**Comment by darkraiN2** [comment]
I downloaded ShatteredPD directly from the Google Play Store now. Seems like it happens with the official release version too. It occurs every now and then and kinda makes it unplayable. I need to tap around on every single tile to find the staircase down to the next level for example. Also switching to landscape mode does not fix it every time.

Screenshots:
![Screenshot_20230831-045748](https://github.com/00-Evan/shattered-pixel-dungeon/assets/143638664/7ea517a3-3ee3-4c7e-a4b7-2ea44028e61d)
![Screenshot_20230831-045808](https://github.com/00-Evan/shattered-pixel-dungeon/assets/143638664/759160f2-99d2-42e7-86ff-982b0e8ff17f)

**Comment by 00-Evan** [comment]
Okay then, so it's definitely not being caused by some modification to the game's code.

By the looks of things something is corrupting the graphics on the game's tile maps, but only up to a certain point, and then they render normally. That's quite odd, especially in the last two screenshots where there seem to be some texture mapping errors and not just missing visuals. The correct texture is being used there still, but the way it's being mapped to the tiles is completely incorrect. And then, just a couple tiles down, the exact same tile visual is being mapped correctly.

The game doesn't actually skip rendering any of the tile regions when they aren't visible, it just draws blackness on top of them. I assume that the glitched regions are ones that are not actually on your screen at all when you do things like switch device orientation. Does zooming the game's map out improve this at all? Doing that would mean that more of the map is on your screen at one time, even if it's obscured by darkness.

Unfortunately this is probably an error that's specific to your device. Graphics corruptions like this usually mean that something is interfering with the game's ability to render its graphics, usually a hardware defect or some extra piece of software that's interfering with things. The S22 ultra is a reasonably popular device (snapdragon and exynos versions), and I have received no other reports of issues like this.
