### ISSUE TITLE
transmutation itself

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1474]
https://github.com/00-Evan/shattered-pixel-dungeon/assets/118305192/3dab950e-909a-45af-9649-05bf4779a59e

**Comment by chorby-short** [comment]
Isn't that doing what its supposed to? Transmutation turning a scroll into another scroll?

That being said though, this was a terrible change. We already have the recycle spell which does the same thing but better, and there are often situations where the ability to transmute a scroll into its exotic form without worrying about an alchemy pot was useful. There were even a few rare scenarios where transmuting a exotic back into its regular form was a good idea; I stumbled across one such scenario the same day the beta dropped. This change was unnecessary and annoying in general.

**Comment by 00-Evan** [comment]
@chorby-short the scroll shouldn't be able to be cast on itself when it is also being consumed by being used. That's the bug here.

Regarding the change to transmute functionality, I made transmute this way way back when alchemy was being introduced and exotics were more awkward to create. It was completely counter to how transmutation worked on every other item, and was never mentioned anywhere in the game. Now scrolls of transmutation convert to 8 alchemical energy, which is enough to exotify two potions or 1 scroll with 2 energy left, which makes using the scroll directly for this rather pointless. I decided it was better to remove this overly specific and undocumented function.

**Comment by Lyx0527** [comment]
> 

Even retaining this setting is not meaningless. In a critical moment, unable to find the alchemy pot, transmuting a potion to its exotified mode may save lives. Although this may seem like a significant loss

To distinguish it from spells, you can try to enhance the effect of transmute scroll or potion. For example, call up a window similar to intuition rune and choose a scroll or potion to oriented transmutation.

**Comment by 00-Evan** [comment]
fixed in BETA-0.4
