### ISSUE TITLE
Feature request: Stepless zoom

### ISSUE THREAD

**Issue by theFireProject** [00-Evan/shattered-pixel-dungeon#1493]
## Problem description

I'm playing Shattered PD on Windows on a 15" laptop with touch screen. The zoom behaviour on large touch screens **and** on Windows is kind of annoying.

1. There are not enough zoom steps for large screens. On a big screen you usually zoom out more than on a small screen. But if you zoom out to the point where it's comfortable, you cannot zoom very precisely because the steps are not small enough.

2. The zoom behavior on Windows is a little different to Android (it's less intuitive):
    - On Android the game scales smoothly while you zoom with the fingers on the screen. When you take your fingers off the touch screen, it locks to the nearest step.
    - On Windows the world doesn't scale smoothly. Not even while you touch the screen. So you move your fingers (and you don't know how far you have to go) and suddenly the game locks to the next step and becomes smaller/bigger without a transition. Often I want to zoom only one step, but it's hard to estimate how much you have to zoom with the fingers because you don't get a "live preview".

https://github.com/00-Evan/shattered-pixel-dungeon/assets/61639215/b469b23a-ed3b-4ea4-a288-0b7a376c149e

<sup>At the beginning I try to zoom in but the image size locks to the previous zoom step. It works on the third try.</sup>

https://github.com/00-Evan/shattered-pixel-dungeon/assets/61639215/3eb79ba5-4ecb-4f12-8e45-9cdd7f665ddc

<sup>The mouse pointer only shows the left finger movement</sup>

## Feature request

On Android I get a live feedback while touching the screen when I'm zooming. The image scales smoothly without steps while my fingers touch the screen. I want that on Windows too.

When I take my fingers off the screen, the image size jumps to the nearest fixed zoom step. Instead I want it to stay exactly at the size it has when I take my fingers of the screen.

## Justification

- I think this feature would improve the Windows user experience because you need to zoom and move the camera a lot during gameplay. The current zoom behavior feels inconvenient and outdated.
- Stepless zoom would be a small improvement for smartphone users, too.

But the main benefit would be for Windows users and I know there are probably not a lot of people who play the game on Windows **and** have a touch screen.

**Comment by 00-Evan** [comment]
The reason for this is that the game's internal scaling needs to be a whole number, otherwise the graphics will look quite wonky. Stepless zoom is simply not possible to implement because of how pixel art works.

Smoother scaling is possible on mobile platforms because the game can allow a non-integer scale temporarily as long as the player is holding the pinch-to-zoom gesture, and then snap to a whole number when they're finished. Such a thing doesn't happen on desktop, as the game has no way of knowing if the player intents to continue scrolling to zoom or not.

Mobile devices also tend to play at higher scaling levels because of their higher PPI screens, which both means that the glitches of a temporarily non-integer scale are less noticeable, and that there are more integer steps available to zoom to.
