### ISSUE TITLE
[Feature Request] Sync functionality

### ISSUE THREAD

**Issue by Henry-Hiles** [00-Evan/shattered-pixel-dungeon#1494]
Hello! I was wondering if you would consider implementing accounts/sync so that I can keep my progress between my Android phone and Linux phone and Linux desktop, thanks!

**Comment by Henry-Hiles** [comment]
You could do this by having google login on both a phone and desktop for instance.

**Comment by Jak2k** [comment]
A file export would be great to begin with.

**Comment by Henry-Hiles** [comment]
> A file export would be great to begin with.

In another issue the Dev said this would be clunky, and make cheating too easy.

**Comment by Jak2k** [comment]
The game is an open source singleplayer game. When I want to cheat, I would fork the game and change the code.

**Comment by 00-Evan** [comment]
I'm afraid there's no real way for me to add syncing between platforms without writing my own server software, which would include account management, security, etc. It's just not feasible for me to do that unfortunately. Services like Google Play Games sync or Steam cloud sync only work within their respective platforms.

I also don't want to add import/export because, as mentioned, it would be trivially easy to cheat. Obviously I can't prevent cheating, but I want to at least not make it easy to do within the game itself.
