### ISSUE TITLE
Auto targeting worked with magic missile but failed with corrosion wand

### ISSUE THREAD

**Issue by hosve** [00-Evan/shattered-pixel-dungeon#1498]
![Screenshot_20230920-105938](https://github.com/00-Evan/shattered-pixel-dungeon/assets/39941745/3a5c8388-3fb7-4967-ba9a-b32aceca49a2)
What happened:
I auto target the full HP ghoul with magic missile. It hits. The damaged ghoul doesn't move (because it can't see me).
I auto target the damaged ghoul with corrosion wand. It hits the wall when it should hit the damaged ghoul. The damaged ghoul doesn't move.
I did not move throughout this.

**Comment by 00-Evan** [comment]
This is because the two wands use different targeting logic. Magic missile will stop at the first solid thing it hits, which makes it possible to bank the shot a bit to hit the ghoul but not the wall by aiming behind it. Corrosion always tries to detonate exactly where you aim it though, it goes through characters, and so banking the shot doesn't work.
