### ISSUE TITLE
Quality of Life - Hotbar target selection

### ISSUE THREAD

**Issue by jagprog5** [00-Evan/shattered-pixel-dungeon#1510]
When using a ranged weapon from the hotbar, if there are any visible enemies then one of them is randomly selected with a cross hair.

By "random", I'm guessing it just picks the first visible enemy from the list of enemies. So not true randomness, but it's unknown from the pov of the player (and it will choose the same enemy until it is dead).

I don't think this should be random. I propose a few ideas, if not all:

- Prioritize awake enemies. The rational is that asleep enemies will remain asleep for a few turns longer, allowing the awake enemies to be dealt with first.

- Prioritize closer enemies.

- Prioritize the enemy that was previously shot by the player.

**Comment by 00-Evan** [comment]
I would rather not have the targeting AI make strategic decisions for the player. This will only lead to more confusion when it incorrectly guesses what the player wants. Currently targeting prioritized like this:

1. enemy recently attacked or otherwise manually targeted
2. enemy already auto-targeted (i.e. first enemy seen)
3. enemy closest to the hero
