### ISSUE TITLE
Fleeing enemies can't flee into fog of war. (Might be intentional idk)

### ISSUE THREAD

**Issue by Howdidibreakit** [00-Evan/shattered-pixel-dungeon#1537]
I was chasing a crazy thief and he couldn't run anymore because he tried to go into a hallway that i had never gone into. Considering that enemies can navigate and move around in fog of war I this is probably intentional, but you never know.

**Comment by 00-Evan** [comment]
Enemies can see the whole map, and so the thief may have known there was a dead end ahead and chose to face you. There isn't much I can do without more details about the situation anyway, such as a screenshot or the dungeon seed.

**Comment by Howdidibreakit** [comment]
![image](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118551559/394b5b3d-9269-447e-a1d8-59991858f493)
that's a recreation of it. I might've just remembered it as being correct but I could be an idiot idk.

**Comment by 00-Evan** [comment]
I can't find any level layouts that match your drawing from that seed. I'm going to close this as the most likely scenario is that the thief stopped retreating because the tunnel ended in a locked door, or a tiny room. Smarter fleeing enemies look ahead several tiles and will stop bothering to retreat if they know they are about to be cornered.
