### ISSUE TITLE
backup?

### ISSUE THREAD

**Issue by Svetov1d** [00-Evan/shattered-pixel-dungeon#1547]
Hi,
Is there a way to make a backup of game and transfer it to another phone? I don't wan't to lose my badges and progress.

**Comment by 00-Evan** [comment]
Unfortunately I don't plan to add a built-in backup feature to Shattered, because it will be extremely easy to use it to cheat. Shattered supports cloud sync via Google Play Games, backups using Google's Android backup/restore functionality, and used to support ADB backup before Google killed it with the release of Android 12.

**Comment by Jak2k** [comment]
Google is evil and should not be the only backup option in an open source game.

When I want to cheat, I can do so by forking. It's easy too.

**Comment by Jak2k** [comment]
What about a hash?

**Comment by 00-Evan** [comment]
I'm not entirely sure what you mean by that. If you mean including some sort of checksum in the file, that does complicate direct modification but does nothing to stop file sharing. It also accomplishes about the same thing as compressing the file, which I'd do anyway. If you mean an external checksum, that substantially complicates good use-cases (move this file and also write down this code), and the checksum can just be shared with the file anyway.

**Comment by 00-Evan** [comment]
As I already said, my goal is not to make cheating impossible, just not easy and not facilitated by the game itself. Downloading a separate application is obviously not within the game itself anymore, even if that application is just a cheat fork. Root file access is also entirely external to the game (also trying to prevent cheating when the player can just access the core files is obviously pointless).

This isn't some arms race to make any sort of cheating impossible at the expense of users. This is my attempt to prevent the reasonably common situation of someone googling 'Shattered Pixel Dungeon help' or similar and getting a file download that immediately unlocks everything for them within the unmodified game.

**Comment by Jak2k** [comment]
But why should a user be not allowed to do this in the "official build"? For me, downloading a cheat apk and a cheat backup is basically the same.

**Comment by Svetov1d** [comment]
> @Jak2k @Svetov1d I've spent a bit more time thinking on this over the last couple of days, and have a potential solution. If I enable debugging on the open-source Android release build of Shattered, that should make ADB backup work again according to Google's documentation. I'd need to make sure there aren't any undesirable tack-on effects to this, but the primary difference (being able to inspect the running app process) isn't really a problem given that the game is open-source anyway.
> 
> Would that solution work for you?

ADB command would be `adb backup -apk` right?
That would work in termux to?

**Comment by 00-Evan** [comment]
ADB is a command line tool that requires a computer plugged into your phone, there are versions for windows, mac, and linux. Accessing ADB commands and tools should be possible on the device directly, but I don't believe it's officially supported.

**Comment by 00-Evan** [comment]
I haven't used ADB backup in a while, but I think you would use this command to backup Shattered's data:
`ADB backup <filename> -apk com.shatteredpixel.shatteredpixeldungeon`

And this command to restore:
`ADB restore <filename>`

While this is extremely easy on my end to implement, I've also been in contact with other users who have complained about backups, and using ADB backup isn't ideal for them either. It used to be that this was the accepted way to backup and restore app data but it seems many people have forgotten about it now that Google has restricted it so heavily.

I am considering just biting the bullet and adding a simple export/import function, but only make it available to open source Android users. While that is not idea for the reasons I mentioned above, it would at least not expose the easy cheating vector to the vast majority of the playerbase (who use google for backup/restore anyway).

**Comment by fabbaf** [comment]
Hello !

I'm not very confortable with adb, but I do have an open source /e/ OS Android 11 set up on my phone !

So step by step ;
- Download Plateform tools and set up ADB and Fastboot on my computer
- Open Terminal 
- Paste : `ADB backup <filename> -apk com.shatteredpixel.shatteredpixeldungeon`

Right ?

Some questions about that : 
- Do I have to put something else instead of <filename> ?
- Where the file will be store?

Thank you very much for your help ; I don't want to cheat, but just don't want to loose the achievments without using Google services :)

**Comment by Kerobyte** [comment]
> I am considering just biting the bullet and adding a simple export/import function, but only make it available to open source Android users

Hello,

I came across your comment while looking for a way to export my save data. I recently switched to a new phone and, since I don't use Google Play services, I'm unable to import my save data. Are you still considering implementing the export/import feature? It would be incredibly helpful for me, as I’d like to avoid starting my stats over. 

I have some reservations about using ADB backup, especially since I've been using my new phone for a while now. It seems that ADB backup doesn't allow for backing up specific apps, such as Shattered Pixel Dungeon, but rather every app that is on the device. I'm concerned it might overwrite other apps I've been using.

Thank you for your attention to this matter!

**Comment by 00-Evan** [comment]
@Kerobyte ADB backup unfortunately isn't a very viable solution these days, Google heavily restricted it in Android 12 such that it's essentially useless. If you're not using Google, you are presumably using a custom or AOSP-based ROM, and so I'd suggest looking into backup solutions that your ROM maker may provide, such as seedvault: https://github.com/seedvault-app/seedvault

I'm still very much on the fence about this, as I've mentioned a save import/export function is going to be used for cheating more than it will be used to transfer progress. If custom backup providers like seedvault keep gaining prominence then this problem will be solved for me though.

**Comment by Holbormon** [comment]
Hello @00-Evan, just chiming in to hopefully help you "hop the fence". As a fellow Android dev *and* roguelike enjoyer who has also read your posts on the topic, I can appreciate your reasons. 

And while I do agree that permadeath is an integral part of what makes the game excellent, I think every player has a different notion of what constitutes a worthy experience in such a complex and modular game. To some, it will simply be getting to the Amulet, and forgetting about it. To others, it will be maximising the score, or getting all the achievements. To yet another audience, it will be about religiously learning all of its intricate mechanics and making sure all interactions between all items and entities has been discovered.

To me, however, an enjoyable playthrough is *one I can safekeep*. Being a bit of a data hoarder, I preserve as much data as I can from the games I fell in love with and really treasure (which, as you may have understood by now, this project fully qualifies as). Without the ability to control the data I get out of playing, the game clearly loses value in my eyes. 

Of course this is one opinion in a sea of equally valid ones, but I'm hoping it gives you another way to view the export feature than as "Democratising cheating".

Thank you for your work, it easily fits within my favourite open-source projects ever.

**Comment by 00-Evan** [comment]
@Holbormon I don't think I've ever tried to suggest that a backup feature would be exclusively used for cheating, the problem is that it makes cheating very easy, and I see that as a dealbreaker. If I were to add an export/import directly into the game it would have to be done in such a way that prevents a player from seeing it and realizing they can just Google "Shattered Pixel Dungeon safe files" and instantly have a 100% profile, and I don't really think there's a way to do that which isn't extremely cumbersome for the users who just want a backup.

**Comment by Holbormon** [comment]
> [@Holbormon](https://github.com/Holbormon) I don't think I've ever tried to suggest that a backup feature would be exclusively used for cheating [...]

Neither did I, but you do seem to suggest that a basic export feature brings more harm than help, which is the point I was trying to challenge.

> I am considering just biting the bullet and adding a simple export/import function, but only make it available to open source Android users. 

Has your opinion changed on this ? You could also add a deterrent message when opening the export menu, saying that importing saves you did not produce isn't how you intend the game to be played.

That being said, I believe that trying to manage (and narrow) to such a degree people's experience of your software might be an uphill battle, one which may even contradict the open-source nature of this project: if the code is to be shared, why not the data produced by it ? 

Maybe this further justifies obfuscating save data only for Google Play users.

**Comment by 00-Evan** [comment]
> Has your opinion changed on this ? You could also add a deterrent message when opening the export menu, saying that importing saves you did not produce isn't how you intend the game to be played.

Yes, non-google built-in backup solutions such as seedvault (on lineageOS) are becoming more prominent, which is solving that problem for me. Adding a warning would only make it more obvious that cheating is an option, it's pretty obvious that it isn't the intended way to play the game.

> one which may even contradict the open-source nature of this project: if the code is to be shared, why not the data produced by it ?

I resent this comment. The availability of the source and how the game handles save data are two entirely separate things, and it's hard to not read this as "If your open source program doesn't also produce freely modifiable data then it isn't really open source".

**Comment by Jak2k** [comment]
It's of course still open source but not being able to port data to a fork is still limiting that openness a bit.

**Comment by Holbormon** [comment]
> Yes, non-google built-in backup solutions such as seedvault (on lineageOS) are becoming more prominent, which is solving that problem for me. Adding a warning would only make it more obvious that cheating is an option, it's pretty obvious that it isn't the intended way to play the game.

Seedvault may be non-google, but it relies on internal Android APIs which may become deprecated any time Google decides so (just like `adb backup` was). I also wouldn't call a solution exclusive to custom ROMs "prominent" (at least, not in the sense of wide availability), especially given that [it's being abandoned by its first adopters.](https://x.com/GrapheneOS/status/1507745283131781121)

> I resent this comment. The availability of the source and how the game handles save data are two entirely separate things, and it's hard to not read this as "If your open source program doesn't also produce freely modifiable data then it isn't really open source".

What I meant is: "If you seek to impose on the users of your FOSS* program a specific way to run said FOSS program (e.g. by dictating which inputs the user is allowed to run it with), you hurt the [first essential freedom of free software](https://en.wikipedia.org/wiki/The_Free_Software_Definition#The_Four_Essential_Freedoms_of_Free_Software)". Ultimately, I admit the distinction is more philosophical than technical, since your project is — commendably — GPLv3 licensed which of course imposes nothing on the program's outputs.

> It's of course still open source but not being able to port data to a fork is still limiting that openness a bit.

To a fork, or even to the same software running on a different platform. For Yog's sake, let me finish my run on a larger screen ! :)


(*Apologies to Mr. Stallman for using "open-source" and "free" interchangeably in my earlier post.)

**Comment by 00-Evan** [comment]
Alright this issue is turning into OSS purity arguments more than useful discussion, I'm locking it.

I will be happy to consider any local backup solution that:
- Enables users to persist their save data outside of their current device
- Does not make cheating easy using the game's own tools (either using your own data or data from the internet)
- Is not overly cumbersome to use

Disallowing the export of runs in progress makes cheating with your own data pretty much impossible, but then it only lets the user persist 'some' of their save data. Perhaps that's a reasonable compromise.

So far I have not seen a solution that exists which would prevent cheating by downloading files from the internet that isn't also overly cumbersome. Keep in mind that when seeds were added users made freely available tools to 'cheat' by mass-searching seeds for favorable ones, which was something I knew was likely when I added seeds. I have no doubt that if save import/export were added someone would create a website or tool to generate custom save profiles.

I care so much about this because, being a Roguelike, the temptation to cheat out of frustration can be extremely high, and once a user has done so they have permanently robbed themselves of the satisfaction of their first win.
