### ISSUE TITLE
Google Play Store is trying to replace SPD v2.3.0 github with SPD v2.3.0 Play store (android14)

### ISSUE THREAD

**Issue by robovoice1** [00-Evan/shattered-pixel-dungeon#1607]
I installed Shattered PD with the apk file from github.
For updating the game and other apps i use the app obtainium.
Now the Google Play Store shows an update and wants to replace the installed version with the PD v.2.3.0 play store version.

Maybe raising the version number for the github/fdroid version could solve this ?!

![Screenshot_20240125-204749](https://github.com/00-Evan/shattered-pixel-dungeon/assets/92784377/5b29b1f5-48a4-48a8-a2a5-07466a2d7dac)
![Screenshot_20240125-204653](https://github.com/00-Evan/shattered-pixel-dungeon/assets/92784377/251473a3-fc18-46b8-979b-cab35c21b5fd)

Google Pixel 6 pro
Android14 GrapheneOS 
UQ1A.240105.002.2024011600 (alpha channel)

Google Play store
version 39.3.33-29 [0] [PR] 599690833
(Latest alpha channel release)

Thanks for this outstanding game :-)

**Comment by 00-Evan** [comment]
This is, sort of, intended. The google play version is currently one version number ahead due to a hotfik needed to resolve an error with Google play games (new players were forced to log in, as pressing cancel would just re-show the prompt). I plan to release v2.3.1 soon which will put both platforms back onto the same version number.
