### ISSUE TITLE
Swarm intelligence not working in 2.4.0-BETA-3

### ISSUE THREAD

**Issue by sp0nj** [00-Evan/shattered-pixel-dungeon#1701]
Playing with swarm intelligence on, and noticing that a lot of enemies are sleeping through combat where they would normally be alerted due to swarm intelligence. Example screenshot below: I killed 2 fish in this room and the third remains asleep despite being close to where the other 2 were alerted and involved in combat.

![Screenshot_20240509-161327](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118607635/413dd6b4-cc43-47cc-a751-487a50d963ae)

**Comment by sp0nj** [comment]
You can see I'm running with all challenges on in the screenshot.

**Comment by 00-Evan** [comment]
Was this just piranhas? They aren't affected by swarm intelligence much because of their limited ability to aggro toward things outside of water.

**Comment by sp0nj** [comment]
It hasn't just been with piranhas. For the most part, it seems like it's working normally, but occasionally I'll see an enemy stay asleep unexpectedly. Let me do some more testing and I'll see if I can get some more details

**Comment by sp0nj** [comment]
I found another example. In this case, upon entering the room, I shot the rat at the top right. It was in the square directly above its current position. The other two mobs failed to alert in this instance, even though they should have been close enough.

Btw, is there a better place to contact you about possible beta issues? Is there another repo somewhere with beta code?

![Screenshot_20240510-135953](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118607635/abb0bc94-fba6-4694-93cf-bddc04aba295)
![Screenshot_20240510-135934](https://github.com/00-Evan/shattered-pixel-dungeon/assets/118607635/a468d4bc-e5c7-4810-8075-791a0c77cc6b)

**Comment by sp0nj** [comment]
Actually now that I'm looking at it, the aggroed rat also doesn't have the usual alerted symbol, even though the hero is in sight. Maybe this has something to do with it?

**Comment by 00-Evan** [comment]
This place is fine for reporting bugs in betas, there isn't an associated source release for betas.

So, from looking at that quickly and doing a bit of testing, it's possible the example you gave is because the rat didn't see you on the initial attack. Swarm intel triggers when an enemy changes from sleeping or wandering and they can see your position, so attacking from out of their FOV won't trigger the challenge effect. Of course, if you don't kill them quickly, the challenge effect will likely trigger anyway once they see you normally.

Apologies, but if you could provide more examples it would be easier to lock this down. Based on what I've seen so far I think you're unintentionally just barely attacking enemies from outside of their FOV.

**Comment by sp0nj** [comment]
That may be the case. If you can't think of a way this could have become an issue right away, there's no sense wasting any more time on it. If I notice something more concrete I can always open a new issue.

There's one more small thing, though. There's a typo in the description for Wondrous Resin. It says "alchemy post" instead of "alchemy pot".

**Comment by 00-Evan** [comment]
Okay then, I'll close this for now, but please do feel free to comment again if you run into more instances of this.
