### ISSUE TITLE
Sleeping enemies can only be woken by proximity to their target, even if another ally is closer.

### ISSUE THREAD

**Issue by Lyx0527** [00-Evan/shattered-pixel-dungeon#1706]
()

**Comment by 00-Evan** [comment]
This is because of enemy selection logic, which makes no distinction if the character is awake or asleep. If a sleeping enemy decides to focus the hero, only the hero will be able to wake it via proximity.

This can be changed of course, but has wider implications than just sleeping and silent steps.

**Comment by 00-Evan** [comment]
Going to defer this to 2.5.0 as it will require changes to sleeping AI behavior that may have side-effects

**Comment by 00-Evan** [comment]
fixed in commits 74eb6373967698161c6eca988911e6eb4bc3a250 and 49af7826ef2c98201a7033774bb7902a989f8471
