### ISSUE TITLE
Improvised Projectiles doesn't work against the Tengu

### ISSUE THREAD

**Issue by RealBamboolord** [00-Evan/shattered-pixel-dungeon#1725]
Throwing an item with the improvised Projectiles Talent at the Tengu during the second stage of the fight triggers the cooldown put doesn't blind the Tengu. Not only that, but the shattered Honeypot I threw at the Tengu also disappeared after the fight and wasn't transported back to the tengu cell after defeating the boss

**Comment by 00-Evan** [comment]
Tengu is immune to blinding effects, so the result of trying to use improvised projectiles on him is working correctly.

As for the honeypot, is there any other info you could provide about that? There isn't anything particular about the shattered honeypot itself, so if it did fail to be carried over it must be due to something like where it was positioned, if tengu threw a bomb onto it, etc.

**Comment by RealBamboolord** [comment]
I didn't take a screenshot, but I think it was  possibly still positioned underneath the Tengu when I defeated him

**Comment by 00-Evan** [comment]
I've run some tests and I'm not able to reproduce this. If you run into this again feel free to comment again and I'll re-open.
