### ISSUE TITLE
Suggestion: Make Wand of Warding auto-target the last targeted ward.

### ISSUE THREAD

**Issue by Glazed** [00-Evan/shattered-pixel-dungeon#1727]
It's such a fun wand. Especially when imbued into the staff, but upgrading or healing a ward can get pretty tedious. It'd be great if it would auto-target the ward you just created or the last one you targeted.

**Comment by 00-Evan** [comment]
This is something that a few people have suggested but that I'm hesitant to do because I prefer for these sort of rules to be simple.

Currently auto-target sticks to the previous target, and only targets enemies. If it were allowed to auto-target sentries with the wand of warding, then that's a specific exception with complicates the rules for how it works significantly. Also, should auto-target stay on the sentry when the player uses a different item? Probably not, so then that's another specific exception.

Generally I think these sorts of gameplay decision-making tools are best left as simple as possible, so that they're not trying to make assumptions as to how the player wants to use them. Autopathing is another example of this, some players want it to do things like take turns of levitation remaining into account, but I think it's better that it behaves the same way in all cases.
