### ISSUE TITLE
Eye of Newt needs an option so you only wake up from sleeping when you see an enemy with your natural vision.

### ISSUE THREAD

**Issue by Glazed** [00-Evan/shattered-pixel-dungeon#1737]
I love Eye of Newt, but it takes away a basic feature: the ability to sleep until an enemy opens to door you're hiding behind. 

Normal gameplay:

1. Open door, wake up distant enemy. Maybe throw weapons at it.
2. Walk back through the door and long-press the wait button to sleep until the enemy opens the door.
3. Surprise attack the enemy.

Problem:

With Eye of Newt you can't do that, so you have to tap, tap, tap, very carefully to ensure you get the surprise attack and it's quite tedious.

Suggestion:

Let players tap Eye of Newt to open a menu that let's them toggle whether the game pauses (pauses your movement or sleeping) when you see an enemy with your **newt** vision or only with your **natural** vision.

I would probably have it off most of the time because it's kind of annoying to move around the map when the game constantly pauses due to you seeing enemies through walls, and it prevents fast-forwarding to a surprise attack, but I can see many players preferring it as it is. Including me sometimes since it does let you reroute when you see an enemy approaching a door.

It's also annoying to pick up items and dew drops just because you see a sleeping enemy through the wall.

I feel like I would have it off (pausing only on nomal vision) when first exploring a level, and on when doubling back.

**Comment by 00-Evan** [comment]
I'm afraid that I don't plan to add a toggle for this behaviour. Interrupting the player when an enemy enters vision is a pretty universal feature of the game and I really don't think it's a good idea to complicate it by having this only trigger in some cases. In general I also try to avoid adding toggles to the game, as if I accepted even 1/10 requests for them the game would be filled with hundreds of toggles by this point.

The eye of newt is the first time the player's vision is mostly based on mind vision instead of normal vision though, and I do plan to keep listing to general complaints about QOL issues regarding that and making tweaks, such as the auto-aim changes in v2.4.2.
