### ISSUE TITLE
Multithreading support 

### ISSUE THREAD

**Issue by CORRUPTEDUSER404** [00-Evan/shattered-pixel-dungeon#1738]
I have noticed with my CPU watch widget that this seems to not have multithreading support.

Perhaps this could be added to an upcoming version because many devices have more than 1 thread

**Comment by 00-Evan** [comment]
The game actually does make use of two CPU cores already. The game's rendering loop occurs on one, and game logic occurs on another. This is mainly so that infrequent but more intensive game logic (e.g. when certain items are used or certain enemies act) wouldn't result in framerate hitching, especially at 120+ fps.

Parallelizing the game more than this would be a massive undertaking with little to not benefit, as the game's rendering is already more than lightweight enough to run on one CPU core.
