### ISSUE TITLE
Adding multi threading optimization

### ISSUE THREAD

**Issue by zay448345045** [00-Evan/shattered-pixel-dungeon#1741]
Hello developers.I would like to ask if the game has considered adding multi threading optimization. There are many monsters placed on the SPD based sandbox dungeon, but it runs very slow. Upon checking the CPU usage of the phone, it was found that only one core is in use, while the other cores are not.

**Comment by zay448345045** [comment]
The tower defense dungeons is even more severe, with thousands of monsters and items falling on the interface, causing fps to drop to single digits and severe lag. For large modules, parallel optimization is required.

**Comment by 00-Evan** [comment]
I actually replied to another issue recently that was similar to this (#1738), I'll copy-paste the reply here:

"The game actually does make use of two CPU cores already. The game's rendering loop occurs on one, and game logic occurs on another. This is mainly so that infrequent but more intensive game logic (e.g. when certain items are used or certain enemies act) wouldn't result in framerate hitching, especially at 120+ fps.

Parallelizing the game more than this would be a massive undertaking with little to not benefit, as the game's rendering is already more than lightweight enough to run on one CPU core."

I also have nothing to do with any projects that aren't Shattered Pixel Dungeon itself, and couldn't comment as to whether there are performance issues in any other Pixel Dungeon version.
