### ISSUE TITLE
add html web version support

### ISSUE THREAD

**Issue by zay448345045** [00-Evan/shattered-pixel-dungeon#1746]
Hello developer, have you ever considered porting SHPD to the web side so that you don't have to worry about installing it on iOS devices.

https://github.com/00-Evan/shattered-pixel-dungeon/assets/22346235/be6b9fdf-0120-4638-9df4-eb868e4bbd91

**Comment by konsthol** [comment]
Hey Evan, I know it's been almost a year since you mentioned you have no intentions to support a web-based port, so I gave it a shot. The results are actually really promising with minimal code changes. It basically works and is playable, but I would characterize it as a beta state web port. I currently host the repo at https://git.konsthol.eu/konsthol/shattered-pixel-dungeon-web-port where you could have a look at the extra commit I made. Also, I host the actual ported game at https://shario.konsthol.eu/ for testing purposes. Let me know what you think.

**Comment by 00-Evan** [comment]
@konsthol I think it's neat if someone else wants to explore the possibility but I already build and distribute about 11 variants of the game to several different places.  I'd rather not add more variants and locations without a good reason.

**Comment by konsthol** [comment]
Fair enough. In that case I will keep it up to date with your repo in case you ever decide to incorporate the changes needed for the extra variant. Keep up the good work.
