### ISSUE TITLE
The small gaps in the UI shouldn't be clickable

### ISSUE THREAD

**Issue by punk4eva** [00-Evan/shattered-pixel-dungeon#1749]
People with fat fingers trying to click the search/quickslot button might miss the button and end up tapping on a tile they didn't mean to click on. I can see people intentionally tapping the region between the search and quickslot buttons on mobile, but on landscape that area is so small that most taps there are probably unintentional. Maybe implement a small buffer zone to the left and right of these buttons to minimise unintentional mistaps?

Furthermore, I've heard of people spamming the attack button and then finding themselves running to a tile they accidentally tapped on because they continued tapping after the enemy died and the attack button disappears. Maybe make the region of the screen where the attack button used to be untappable until the player taps on a different location first.

**Comment by 00-Evan** [comment]
These UIs actually already have small buffer zones around them. I don't want to make the lower section a total dead area because the amount of space available there varied by device and zoom level. Obviously a highly zoomed phone in portrait won't have a lot of room, but a tablet that's zoomed less will, even if used in portrait.

The attack indicator also already has a 0.75s delay after disapeparing before its tap region is disabled, specifically to help reduce mistaps from frequently pressing it.
