### ISSUE TITLE
Strange behavior of enthralled cave spinner

### ISSUE THREAD

**Issue by j123123** [00-Evan/shattered-pixel-dungeon#1765]
Enthralled Cave Spinner has stopped in the corner of the room and does nothing. Maybe some bug in pathfinding? Here is save files
[game1.zip](https://github.com/user-attachments/files/16612538/game1.zip)

**Comment by 00-Evan** [comment]
Thanks for the save data, that makes debugging this issue much, much easier. It appears that the spinner is still caught in a retreating AI state (presumably because you enthralled it while it was running after poisoning you). In such a case it should recognize it's now fleeing from an ally and go back to wandering, will look into that logic.

**Comment by 00-Evan** [comment]
fixed in commit 0d5d5050388e6bbaed6392d361d4cfa5d6a31ad3
