### ISSUE TITLE
I wonder what's your intention for this changes.

### ISSUE THREAD

**Issue by YouIG** [00-Evan/shattered-pixel-dungeon#1778]
Hi evan, first of all thanks for the new update with SPD!

In SPD 2.5.0 beta 1 patch notes - misc changes /  'Bomb explosions no longer destroy any type of equipment, not just upgraded ones'

For years I used this tricks a lot to get better choice of equipment and to clear my fulled inventory as fast ways. Also it was one of my favorite trick for SPD. But now it's not possible anymore.. 

I just wonder is this your intended changes for those who using bomb to check upgraded equipments?

or is there another reason for this changes? 

Hope you reply. Thanks.

**Comment by 00-Evan** [comment]
Exploding bombs to identity equipment was always an exploit that I wanted to eventually fix. The initial intent of the change was to prevent explosions from screwing players out of important gear, but only a while later did I realize that players were using it to purposefully destroy everything but upgraded gear. It's also completely unintuitive behavior that players will only reasonable discover by reading the wiki.

I've been hesitant to fix it because I do know its one way experienced players have fought back against inventory congestion. So, seeing as I'm making some general inventory management improvements this update anyway (so carrying un-ided gear isn't as big of an issue) it felt like a good time.

**Comment by YouIG** [comment]
Thank you evan.

So that means there is no roll-back in the future for this change?

**Comment by 00-Evan** [comment]
Nope, I'm afraid not. If it creates lots of problems then I can try to compensate, but I suspect the average player already wasn't using this strategy.

**Comment by YouIG** [comment]
Thank you.
