### ISSUE TITLE
Make it possible to turn unidentified potions into elixirs

### ISSUE THREAD

**Issue by wismos-0rg** [00-Evan/shattered-pixel-dungeon#1785]
so let's take a situation for example

![Screenshot_20240828-230409_Shattered Pixel Dungeon.png](https://github.com/user-attachments/assets/48a0d1d9-34d4-480e-8a73-dde56215e0c3)

![Screenshot_20240828-230400_Shattered Pixel Dungeon.png](https://github.com/user-attachments/assets/fcd0e867-4a13-4456-825a-8ad195c6b319)

here i have identified every potion except potion of paralytic gas and thus i know that the remaining unidentified potion must be paralytic gas

![Screenshot_20240828-230432_Shattered Pixel Dungeon.png](https://github.com/user-attachments/assets/286ff935-c2dc-410f-bc08-b31901ec25c2)

and now i want to turn it into shocking brew without identifying it as identifying it would be a waste but it seems that is not possible to do as long as it is not identified and now that brings us to the current topic

in cases like these i would be glad if you made it possible to turn unidentified potions into elixirs, now i know not every potion can be turned their elixir variant without additional stuff but out of 12 potions 8 can be turned elixir/brew without stuff and i think that would be enough to revealing the identity of a potion

thank you in advance for giving your time to reading this, looking forward to hear back from you !

**Comment by 00-Evan** [comment]
Afraid I don't think it's a good idea for recipes that require specific items to be usable when that item isn't IDed.

In order to balance this there would need to be an option to spend an undefined amount of energy to try and convert any potions into an elixir, with the potion being destroyed if there isn't enough energy or no elixir exists. Such a function would be very awkward and I doubt many people would want to use it.

As for identification, it's mainly this way so as not to give a small advantage to players who have metagame knowledge or who have done previous runs, compared to a new player who doesn't know what all the potion types are yet.
