### ISSUE TITLE
Cursed wand of warding crash.

### ISSUE THREAD

**Issue by Insomnilax** [00-Evan/shattered-pixel-dungeon#1799]
I am not sure if it is this specific, but I will be specific for the sake of it. The wand of warding made my game crash when it was cursed, also had cursed sandals (not sure if it was affected by it) I had wondrous resin +0. Hope I was able to explained it well!

**Comment by TheYsconator** [comment]
A game crash is a pretty rare intended cursed-wand effect. Everything is saved before it closes the app (pretending to crash), so you can just launch the game again and continue where you left off. No harm done; enjoy the effect! ;-)

**Comment by 00-Evan** [comment]
As mentioned, this is an intentional rare cursed wand effect that actually just closes the game.

**Comment by spixi** [comment]
@00-Evan Is there any way to disable this effect or change it, so that you return to the main menu instead of closing the whole app? When you are streaming Shattered Pixel Dungeon on platforms like Twitch or Discord, this could potentially expose your desktop or other applications or even quit the stream (on Discord) when you are just streaming a window.The only quirk I found, is setting the language to another language than English.

**Comment by 00-Evan** [comment]
> @00-Evan Is there any way to disable this effect or change it, so that you return to the main menu instead of closing the whole app? When you are streaming Shattered Pixel Dungeon on platforms like Twitch or Discord, this could potentially expose your desktop or other applications or even quit the stream (on Discord) when you are just streaming a window.The only quirk I found, is setting the language to another language than English.

As far as I'm aware sharing your entire monitor, instead of a window, is considered a very bad practice while streaming. Given that this effect is a 1/800 chance I would rather not compromise it in the name of mild convenience.
