### ISSUE TITLE
[Bug/Feature] Pathing Quirks

### ISSUE THREAD

**Issue by larssorenson** [00-Evan/shattered-pixel-dungeon#186]
Hello again,  
  
While exploring the dungeon, there are a few situations that cause the player to path ridiculously and sprint across the dungeon inefficiently. One such case is when the ghost suddenly appears in your path, blocking it. This will cause your player to suddenly reverse direction and go in a roundabout path to get to the original destination. Mirror images will also produce a similar result. Intuitively, I would expect this to result in the auto-pathing to pause not unlike when an enemy enters the field of view.  
  
Another pathing quirk has to do with plants, specifically sungrass. If you click on a tile on the opposite side of the plant, given the right setup, the pathing will cause you to run onto and off the plant, immediately wasting it. It would be nice if the pathing would avoid the plant, not unlike a trap.  
  
Similarly, when in a room such as the garden with long strings of high grass and weird visibility/fog of war, it's possible to click on an explored tile on the opposite side of a tile covered by FoW. The player will begin to run along the optimal route, get to the tile that had FoW but is now visible, step to the side of it and step back before continuing along the route. Ideally, the player should run along the visible route, the new tile is then visible and determined to be safe to run along (in the case of it just being High Grass). The route should then effectively be a straight line, instead of an almost straight line with a 1 tile kink.  
  
The pause/resuming behaviour of the auto-pathing is a little counter-intuitive. There are some cases where the auto-pathing pauses, you can do things like fight a monster, then resume the pathing. There are other cases where the auto-pathing hard-stops, but you would think "why can't I resume from here?". Unfortunately I don't have any hard details/steps to reproduce these conditions, but I'm aware of them existing through casual play through. I'll try to keep my eye open for particular examples.  
  
  
Once again, thanks for your hard work on the game! I look forward to your thoughts on these pathing quirks!  
  
Thanks,  
Lars

**Comment by 00-Evan** [comment]
Hey, i'll go over each point you mention here:

NPCs generally don't interrupt you because most of the are stationary in a room, in the case of the sad ghost and mirror images though I think interrupting is more appropriate, they can definitely be changed.

I can agree with plants also interrupting motion, however I don't want to have them be auto-avoided like traps.

The one tile kink is odd but correct. This is due to a performance change I made in 0.4.2 which causes characters to pre-calculate their route and only re-calculate it circumstantially. that 1 tile kink shouldn't affect the overall time it would take to reach the object, so it is deemed to still be a perfect route and pathfinding is not re-run.

Pause/resume should be improved as of 0.6.0a, but if you have any specific situations where you still feel it doesn't work well i'll be happy to hear them.

So for now I think the following is actionable from this issue:
- change the sad ghost (not the ghost hero from the dried rose), and mirror images to interrupt the hero if they pop into the field of view
- change plants to always interrupt motion when stepped on.

**Comment by larssorenson** [comment]
Hey Evan,
  
I appreciate your response! I'll definitely keep an eye out for the pause/resume quirks in the latest release.    

As far as your actionable items, I think having the movable NPCs interrupt pathing is a suitable fix for that concern. However, I'm a little less sure about the plants interrupting motion.  
Since the plant could have negative effects much the same as traps, and your hero won't path onto a trap, I would assume the hero wouldn't do the same for the plant. Fireblossom and fire trap are essentially equal as far as undesirable to step on. I'm pushing for avoiding plants automatically. I'd like to hear your thoughts on why you think otherwise though, I'm not as in tune to the balancing to the game.  
  
The one tile kink I pointed out isn't a concern of efficiency getting from point A to point B, and your efficiency argument is sensible, but rather a concern of the side effects. For instance, it'll now take an extra turn if you intended to run across a whole line of tall grass but your hero skipped one (apparently for no reason). Additionally, there could be complications with tiles nearby, such as enemies, traps, or plants. Unfortunately I don't have a good solution that doesn't involve forcing pathing to recalculate at each step.  
  
Again I appreciate you taking the time to respond, and all the time you've put into this game!  
  
Keep up the good work,  
Lars

**Comment by 00-Evan** [comment]
I'm not going to make plants avoidable, at least not now. Currently there is no logic for the player to avoid something but enemies to not avoid that thing. Implementing that is certainly possible but I don't really want to break from that design unless there's a very good reason for it. Also while some plants are a bit trap-like they are overall nowhere near as harmful as traps, and are not considered harmful terrain by the game.

**Comment by 00-Evan** [comment]
As of 0.6.1 plants now interrupt the hero. Unfortunately the other changes (avoiding tiles or not being interrupted by none-enemies) are a bit more involved than I initially thought so I have delayed them.

Hero interruption was added in commit 5d4b0cbb2a216947da3baf6ec27886358e4796f5

**Comment by larssorenson** [comment]
I want to pop back in and discuss this a tad bit more, since you've made some changes that I like. Specifically, the fireblossom removed from the plant rooms (which was one of my biggest issues with the automatic pathing causing players to step onto plants). I have noticed that the pathing system does some wonky things when interacting with enemies and obstacles:  
 * When an enemy pops into sight and causes the player to pause, there are some scenarios where stepping and attacking do NOT clear the calculated path and the player can click the Play button to continue pathing as normal.  
* There ARE some scenarios (and I'm not sure what the difference is) where stepping or  attacking a monster DOES clear the calculated path and the player CANNOT click the Play button to resume auto-pathing.  
* If an NPC (such as the sad ghost) appears and moves around as the player is auto-pathing, the path is recalculated when the path is blocked (sad ghost is standing in the doorway). This can result in the auto-pathing rerouting along the opposite loop (say, to the down stairway), causing a dramatically extended path to be generated. This can be compounded by unfortunate circumstances with mirror images and/or the sad ghost that could cause the player to back-and-forth repeatedly or (theoretically) indefinitely.  
  
Let me know what you think about this issue. The pathing is definitely getting better but there are still some frustrations with the auto-pathing when it (due to no fault of its own) makes you run around like a madman and waste hunger ticks.

**Comment by 00-Evan** [comment]
I decided to remove fireblooms largely because of the recently increased fire damage. It created several problems, where enemies could trigger them and clear half a level, or the player could step on them and basically be guaranteed to die. I decided this was a bit too extreme and removed them.

Regarding NPC issues, my stance on that is unchanged. I would still like to improve some of the quirks but it isn't a large priority, and is unfortunately more complicated than it may immediately appear to be.

Regarding calculated path in particular, it will be lost when you take a movement action which deviates from the calculated path. This means that some movement actions may preserve the old path (if moving along it is suitable for reaching that destination), but if the old path cannot be preserved it is destroyed and the button is removed.

**Comment by anowlcalledjosh** [comment]
> Regarding calculated path in particular, it will be lost when you take a movement action which deviates from the calculated path.

This is definitely not working properly. An example: I tapped on a locked door on the other side of the map, and a gnoll scout came out of a door behind me (not blocking the path), which interrupted the movement. However the "continue" arrow didn't ever appear, even though I didn't take any action after movement was interrupted.

**Comment by 00-Evan** [comment]
@anowlcalledjosh 

This is because that was not a movement command, but an "open door" command. The way continue moving was original coded was to have the button only appear if "walk to a location" specifically was interrupted.

**Comment by ChristophHaag** [comment]
I'm not entirely sure but I think pools with piranhas are not avoided. You can accidentally lose a lot of HP at those...

**Comment by benzarr410** [comment]
Can confirm they are not.

**Comment by ChristophHaag** [comment]
Ok I found https://github.com/00-Evan/shattered-pixel-dungeon/issues/212. The thing is that piranhas are worse than most traps because they move fast and do a lot of damage. An easy but maybe not ideal fix would be to treat all tiles next to a piranha pool as traps.

**Comment by mjdv** [comment]
Somewhat similarly to these issues, I would greatly appreciate it if in a future patch, you automatically stop walking when hit by an enemy off-screen. I just lost a run that was going great, with the "Into Darkness" challenge, because I walked through a room with a Gnoll Shaman outside my LoS. It would have been trivial to survive there (I had a cloak of shadows/could have backed out of the room/had several healing potions) but I died (from four lightning attacks) before I could react and stop walking.

This has happened to me several times, although this is the first time I've very clearly lost a run to it.

**Comment by 00-Evan** [comment]
@mjdv this should only happen if you're using the 'continue moving' indicator, which assumes you want to force moment. Otherwise taking damage does interrupt you.

**Comment by SecT0uch** [comment]
I lost several runs when the levitating effect ends in a bridge or fissure room..

**Comment by mjdv** [comment]
@00-Evan, I am fairly certain that this is not the case for me, although your assertion has made me question my memory. If I have a moment I will try to recreate the behavior by doing only the Into Darkness challenge and getting to Tengu. To be clear, the "continue moving" indicator is the gray arrow button that automatically lets you continue your path?

**Comment by 00-Evan** [comment]
@mjdv that's correct. I've double checked the code and unless there's a specific bug taking damage should definitely interrupt you normally.

Anyway, this isn't a place to have a general discussion about various elements of levelgen/pathfinding. If you have a bug please report it as a separate issue, if it's design-related just email me: Evan@ShatteredPixel.com

**Comment by matematikaadit** [comment]
When my character suddenly revisit the already visited tile (backtracking it's path) for any reason whatsoever. I always pause/stop it from continuing. Do you think this is a good enough heuristic to pause the auto pathing?

The reasoning would be something like this: When a character decided to revisit already visited tile, most likely it's because of there's something blocking it's movement. Instead of continue backtracking, **pause** the current trajectory so that the player can inspect what's actually causing them to backtrack. If they decided that backtracking is really indeed waranted, they can **unpause** the auto pathing.

**Comment by spixi** [comment]
There are still issues where the autopathing is not interrupted, when hit by an enemy, which is specifically a problem with enemies which do massive ranged damage, namely Gnoll Trickster, Gnoll Shaman, Tengu, Dwarf Warlock and Yog’s fists.

**Comment by 00-Evan** [comment]
Update to this, as of 0.8.0 the hero now pauses when their path becomes invalid and a new path would be much longer. This is part of general pathfinding improvements in 0.8.0 which fix various issues.

I'm sure there are still possible improvements that could be made to movement/pathfinding (in particular I know lots of people find 'continue moving' to be counter intuitive), but I think the original issue here, as well as the bulk of comments, have been addressed, so I'm going to close this. If anyone has a particular improvement they would still like to see they're welcome to suggest it via email or a new issue.

**Comment by larssorenson** [comment]
Thanks for your continued commitment to developing this game!
