### ISSUE TITLE
projecting bow fails to hit

### ISSUE THREAD

**Issue by pescepalla** [00-Evan/shattered-pixel-dungeon#1882]
I have a projecting bow. I entered a room with a Gnoll Brute 4 tiles from the door, just out of Huntress mind vision range. I left the room and started shooting through the door.

When I shoot my projecting bow, I can see the arrow traveling along the path shown in red until just beside the door next to the puddle.

![signal-2024-10-25-14-10-46-306](https://github.com/user-attachments/assets/81f96137-481c-461f-be6d-01ce25973b67)

However it does not hit anything. The brute is here (now alert, it was sleeping earlier): 

![Screenshot_20241025-140615](https://github.com/user-attachments/assets/ce27d997-fcbb-42e9-b69c-ecaabc147dfd)

The arrow should have hit the brute.

**Comment by 00-Evan** [comment]
From your example screenshot it looks like you may have accidentally tapped on the cell behind the brute, causing the arrow to go through it and miss. Did you have any effect that would enhance the projecting enchantment (such as ring of arcana) which would allow a projectile to go 5 or more tiles instead of the normal projecting maximum of 4?

**Comment by 00-Evan** [comment]
That sounds like the reason for this then, I'll close the issue.
