### ISSUE TITLE
Stone of detect magic could ID regular items

### ISSUE THREAD

**Issue by llevrel** [00-Evan/shattered-pixel-dungeon#1924]
Hi,

When a stone of detect magic doesn't detect any magic on an item, the latter gets a status of "unidentified but safe" (blue background). However the type of a piece of weapon, armor, or wand is not something concealed (unlike unidentified ring types). So if the stone detected no magic, there is no more mystery about it, and this piece could turn plainly identified. This would be a tiny buff to stones of detect magic.

**Comment by llevrel** [comment]
Hi,

It looks like you understood the contrary of what I wanted to suggest, sorry for being unclear 😅 English is not my mother tongue.

So let me take an example. The hero is in the caves, beats a DM200 which drops plate armor. This armor has purple/mauve background in the inventory. With stone of detect magic there can be three results (approximate phrasing, I play in French):
- malevolent magic: still unidentified, but red background,
- positive magic: the armor may be enchanted and/or upgraded, still unidentified, but blue background,
- no magic whatsoever: the armor is unenchanted and unupgraded.
So, in this latter case, and only this one, the armor is fully known: it could get the identified status (grey background) without giving additional information to the player. This would be a tiny buff that allows handing the armor to the troll for upgrading or merging - a tiny comfort for not getting upgraded stuff 😆

**Comment by 00-Evan** [comment]
Right, but having the grey background, which means an item is identified, means that you also know things like the type of a ring, or the exact level of an armor. It is intentional that stones of detect magic don't reveal this information, even if players can infer that an item is +0. I'd rather not let stones of detect magic fully identify an item, or change the meaning of the grey background.
