### ISSUE TITLE
Two QoL improvements for the new Cleric class

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#1931]
Hi Evan,
I really appreciate your efforts and I enjoy playing with the new Cleric class. There are some thing, which could be improved: If you don't have enough charges, the quick cast button should be greyed-out or hidden until you have enough charges again, this would make it more visible, especially when the Tome is not in your quickslot menu. Also, the new illuminate debuff has no debuff symbol, when you use the magnifying glass on the enemy. Sometimes, the illuminated aura is difficult to spot, especially when the target is a champion or has multiple other debuffs, so an icon would be helpful.
Thank you and keep going!

**Comment by 00-Evan** [comment]
I decided against both of these earlier in development:
- for the quick-spell, the action indicator doesn't current support being enabled/disabled selectively like that. It's either visible or hidden, and decided removing and re-showing it would be too disruptive.
- For illuminated, I felt because the buff had a clear visual indicator it wasn't necessary to give it an icon. I'll reconsider this, but for now don't plan to add one.
