### ISSUE TITLE
Bless automatically prefers wrong target

### ISSUE THREAD

**Issue by Titanic472** [00-Evan/shattered-pixel-dungeon#1942]
When using cleric's bless ability, enemy is being auto-targeted instead of player. 

Not critical, but sometimes ends with enemy having shield when this ability used without looking at the target.

Version V3.0.0-BETA-1.1

**Comment by CaptainCrusher** [comment]
I concur. This is definitely the most annoying thing about the new update.

**Comment by 00-Evan** [comment]
Afraid I don't plan to put in other targeting behaviours for things like bless. The existing targeting behaviour is meant to be as simple as possible, and I don't want to have it make assumptions about what the player wants to do (e.g. what if you have an ally, what should bless suggest that you target?). The existing behaviour is nice because it piggybacks on the current target, which the player can change by attacking another enemy or using the danger indicator.

I do agree that targeting an enemy is wrong in the vast majority of cases for bless though, so I plan to turn off autotargeting for the bless spell in future.
