### ISSUE TITLE
Gnoll trickster AI bug?

### ISSUE THREAD

**Issue by nyuszika7h** [00-Evan/shattered-pixel-dungeon#20]
Sometimes the gnoll trickster keeps retreating behind the door next to me, allowing me to surprise-attack it every time.

Here's a screenshot (I already killed it):

[![Screenshot](https://i.imgur.com/PIOB9Xrl.jpg)](https://i.imgur.com/PIOB9Xr.jpg)

**Comment by 00-Evan** [comment]
While I agree that this seems unusual, it is infact intentional. The trickster is not supposed to be difficult to outwit, but rather to help teach the player about the importance of corners/doors against ranged opponents. If you understand how to counter the trickster is he supposed to be very easy. 

The AI demonstrated here is identical to the behaviour of the lategame mob scorpio, and also very similar to most ranged mobs. If ranged enemy AI ever gets changed to be more tricky, the trickster will be tweaked as well.
