### ISSUE TITLE
Wishlist: More functional artifacts

### ISSUE THREAD

**Issue by doctormo** [00-Evan/shattered-pixel-dungeon#204]
The artefacts in the game are interesting, but some of them could be better by blessing them and/or combining them with some other items, these are some ideas:

 * **Dried Rose** - Already OP with the latest upgrade, but a hell of a lot of fun. Gear disappears when the ghost dies. Blessing and combining with 5 health potions could enable to "don't loose heath over time" function, nerfing the default rose slightly.
 * **Chalice of Blood** - Combine with full dewvile at level 10, makes "Chalice of Life". Acts as dewvile with 10 drops but fills up over time when worn.
 * **Cape of Thorns** - A blessed cape could be applied to armour as a buff. Freeing up a slot.
 * **Cloak of Shadows** - blessed and combined with scrolls could allow levitation or insight.
 * **Ethereal Chains** - Blessed could allow you to set the target, so an enemy can be grabbed and then put down over a hole for wonderful falling instakilling.
 * **Horn of Plenty** - Blessed could act as a storage for food, so it can consume food, but also just put rations and meat in there freeing up slots. Could be "Horn of Satiation"
 * **Lloyd's Beacon** - Blessed and combined with 5 scrolls of teleportation could allow two selectable locations (allowing you to zap to a shop and then back again) Making it "Lloyd's Teleporter"
 * **Sandals of Nature** - Blessed and combined with armour could give you immunity to traps. Could be "Closed Greaves of Nature"
 * **Talisman of Foresight** - Blessed and combined with 5 map scrolls could actually reveal a trap two or three squares away making it a "Talisman of Knowing".
 * **Thieves' Armband** - Blessed combined with a ring of wealth could allow you the ring of wealth buff making it "Wealthy Thieves Armband"
 * **Timekeeper's Hourglass** - A blessed hourglass combined with a speed ring could give you a speed ring buff making it "Timetaker's Hourglass".
 * **Unstable Spellbook** - Blessed and combined with the scroll holder could make it a "Stable Spellbook", allowing scrolls to be stored in it (freeing up a slot) as well as generating scrolls at half the rate of the wand feature when activated and worn. Allowing the user to get a nerfed but more predictable output.

Many of these things should only be allowed once the artefact is at level 10, giving extra reason to push to getting to that level and limiting it's powerful effect during the start of the game.

Other ideas: who can't be boil the meat in the alchemy pot? Why can't we combine meats into a ration? Why can't the dewvile be stored in the potion holder?

**Comment by 00-Evan** [comment]
Hey Martin,

Firstly, this place is primarily for bug reports or technical issues/improvements. If you want to talk game design the best way is to email me: Evan@ShatteredPixel.com

Regarding your suggestions:

Most artifacts are actually in a really solid place balance-wise right now. I do appreciate that it would be neat to give them some sort of 'evolved form' at max level, but this would seriously skew their power budget, forcing me to make them quite weak until they reach +10. I'd much rather keep their power growth incremental, so they can be satisfying at lower levels. That response sort of covers most of your suggestions here, but here are a few more specific replies:

Dried Rose - The dried rose is actually in a pretty good place balance-wise right now. It feels extremely satisfying and powerful, but a lot of that is due to the gear you assign to the ghost. In terms of the raw numbers the rose is nicely keeping pace with other high-value artifacts. Either of these suggestions would massively over-nerf it.

Cape of Thorns - This would be extremely overpowered. Once of the major balancing forces on artifacts if that they eat up a slot which could be given to a ring or other artifact. Any sort of no slot required artifact would be overpowered because there would be no cost to using it.

Ethereal Chains - I'm already unhappy with how much of the chain's usefulness is tied into chasm dropping, this would provide so much power that I'd have to basically remove all the chain's other effects. 

Lloyd's Beacon - I'm actually considering using this mechanic elsewhere, but it would have to be very limited. Back and forth teleporting is extremely strong.

Sandals of Nature - I don't think it's a good idea to reward the player by letting them ignore a major game mechanic. I do agree with the underlying frustration with traps though. I'm actually going to be improving them very soon.

Thieves' Armband & Timekeeper's Hourglass - Similar to the cape of thorns, you'd be getting the power of two items in one.

Regarding boiling meat, I'm actually in the process of designing some improvements to the alchemy system. Some traditional cooking additions are likely to be a part of that.
