### ISSUE TITLE
why this repo does not reflect new version?

### ISSUE THREAD

**Issue by Sharku2011** [00-Evan/shattered-pixel-dungeon#209]
why this repo does not reflect new version(0.6.2)? Are there any problem?

**Comment by 00-Evan** [comment]
Source releases are staggered slightly from the google play release to give me some time to fix up bugs and make small improvements before people get the source and start basing work on it.

This particular release has been delayed longer than usual due to external work and the improvements in 0.6.2a being larger scale than is normal for an initial patch.

**Comment by Sharku2011** [comment]
Thanks for your kindly answer. And sorry for my impatience.
