### ISSUE TITLE
Idea for new room type: hidden treasure library

### ISSUE THREAD

**Issue by erikhuizinga** [00-Evan/shattered-pixel-dungeon#214]
As a new room type or variant, I'd like to see the following. Currently, I often burn down bookshelves in a library room only to find out there's just walls behind them. I always hope there's treasure or a treasure room behind any of them. Would it be possible to add such a room, or give library rooms a small chance that they contain secrets behind the shelves that can only found by teleporting there (e.g. using chains), or by burning down the shelves?

Another possibility would be to hide scrolls in the shelves: since there's loads of books, it would require a search (or spontaneous luck) to find a scroll between the books. A mage, of course, would more easily find scrolls (or find more of them) in a library than the other classes.

Combining the two ideas would make burning down the shelves a good idea, but only after spending some time studying the bookshelves. Otherwise you might burn valuable scrolls before having found them.

**Comment by 00-Evan** [comment]
Firstly, this place is for issues and suggested technical improvements, for game-design related stuff it's best to email me.

Regardless, I don't like this sort of change regarding bookshelves, because I don't want the player to feel compelled to search and burn every shelf they run across. 0.6.2 actually did add a book-shelf related secret, but it's a very specific one, so players should quickly learn that they only need to burn down bookshelves in that one case.
