### ISSUE TITLE
Skeleton death sets destination

### ISSUE THREAD

**Issue by ManaUser** [00-Evan/shattered-pixel-dungeon#23]
When you kill a skeleton and get caught in the shower of bones, it sets your destination to the space where the skeleton was standing. This happens whether you previously had another destination or not. To be clear, by destination, I mean the little blue continue interrupted movement button.

**Comment by 00-Evan** [comment]
Thanks for reporting, I'll investigate this.

**Comment by squigish** [comment]
I'm trying to debug this, (mostly as an exercise for myself in learning more about Java in general and Android programming in particular), and I think the problem may be that when the skeleton damages the hero, Skeleton.die() calls Hero.damage(), which calls Hero.interrupt() (because damageInterrupt is true), which overwrites lastAction.  I don't yet have a good enough handle on the code to know how to fix it, though. It's also entirely possible that I'm barking up the wrong tree.

**Comment by 00-Evan** [comment]
@squigish you are mostly correct, this seems to be an issue with damage interrupting, which was added in 0.2.3 and partially completed actions.

A stack seems unnecessary as we really only care about the current action and the most recent one, probably best would be for the damage interrupt to only trigger if the hero isn't in the middle of an action, which is as easy as checking if curAction == null. I'll run some tests on this and include in the next update.

**Comment by 00-Evan** [comment]
issue has been fixed indev, will close this ticket with a reference to the commit when the source for 0.2.4 is released.

**Comment by 00-Evan** [comment]
fixed in commit https://github.com/00-Evan/shattered-pixel-dungeon/commit/9c5d4facf513643ec60c025f1bb30d084fa47be4
