### ISSUE TITLE
[Enhancement] Are you sure you want to step on this trap?

### ISSUE THREAD

**Issue by larssorenson** [00-Evan/shattered-pixel-dungeon#241]
Hello!  
  
I had the thought that a nice feature to prevent fat-fingering with smaller screen devices, resolutions, or zooms would be to confirm that a player wants to step onto a trap or plant that is harmful. I don't see it as an enhancement to the game to have players punished for accidentally clicking one tile over from where they meant to, resulting with them stepping on a trap that may kill them (I've accidentally stepped on the doom traps in the final 4 levels because of this).  
  
Since you already have the confirmation dialog for throwing beneficial potions or jumping into chasms, I wonder if it would be too much trouble to have a confirmation dialog when a player clicks to step onto a plant or trap; in a turn-based game conceivably the player would never unintentionally step onto a malicious tile if it was visibly so and in my experience it's only ever been accidental, which feels punishing.  
  
I look forward to hearing your thoughts.

Thanks!

**Comment by 00-Evan** [comment]
I have no plans to add additional confirmations to the game unless they are absolutely necessary.

The beneficial potion drink/throw is leftover vanilla functionality that I would like to remove at some point actually. It is currently in place because all potions default to 'drink' in their quickslot function. I'd like identified harmful potions to default to throw, would would allow this prompt to be removed.

Chasms specifically are allowed a prompt because in some layouts they are ever-present and extremely easy to mistap. They are also considered to be neutral terrain, not harmful terrain. Thinking from a thematic perspective, accidentally triggering a trap is much easier than falling in a hole.

Removing accidental mistaps entirely seriously affects the feel of the game, some people have referred to this as "are you sure"-Dungeon, and I agree that there is a fine line between QOL and handholding. Some traps even exist in the game almost purely to keep players on their toes regarding mistaps, such as the grim trap.

**Comment by larssorenson** [comment]
I understand. I suppose I see the mistaps as frustrating and punishing rather than adding to the depth of gameplay and skill, but I also see your point regarding the "Are you sure"-Dungeon.
