### ISSUE TITLE
[Bug] LoS, collision, and projectiles

### ISSUE THREAD

**Issue by larssorenson** [00-Evan/shattered-pixel-dungeon#242]
Hello!

There are some quirks related to projectiles, specifically throwing weapons, wands and the boomerang, although items being thrown are likely also affected. There appears to be a disconnect between line of sight and the ability to target/hit something.
  
This is demonstrated by the Evil Eye. For instance, say you're standing in a hallway that runs left to right along the screen, a few tiles from the opening. An Evil Eye can be one tile on either side of the opening, charging a beam, and miss from one direction but hit you from the other. I believe this is a rounding or precision error. This quirk translates itself to attacking enemies with ranged weapons of any kind. Sometimes, you can see an enemy and click to attack it with a ranged weapon using the auto-attack, such as the boomerang or wand in a quick slot, and it will hit the wall one tile off, despite showing the targetting reticle.  
Additionally, this quirk can be bypassed with some effort that requires the player to calculate a 2:1 horizontal:vertical tile ratio along the diagonal of the path to the target, pressing a tile further behind the enemy to successfully hit them. It allows the player to also hit enemies that are around the corner, that don't register on the entity counter in the upper right, or those that don't appear in the auto-attack box on the lower right, which I believe introduces an inconsistency and subsequently a bug.  
  
To put it plainly, I feel that if the player can see an enemy and it appears in the target box, then it should be hit when clicking through an auto-attack feature. Conversely, an enemy out of line of sight (such as around a corner) should not be hit by some obscure and convoluted attack by taking advantage of the rounding error.  
  
  
I hope I did a good job of explaining this issue, let me know if you have any questions. If I had a dev setup, I would provide some logging/numbers to back up the issue however I don't. I imagine the issue resides in the build() function of Ballistica.java, since the pathing math is done by integer (I imagine due to array indices being integer only).

**Comment by 00-Evan** [comment]
I'm well aware of this and it's intentional. All of this stems from differences between line of sight and projectile calculation.

When targeting a cell, the game will trace a line from cell center to center, and if that line hits a blocking cell first, the projectile is interrupted.

For visibility, a region is considered visible if a line can be traced from the center of the source cell to any point on a given target cell. This is what allows limited visibility around corners. 

I have no intention to change the fundamentals of projectile targeting, as doing so would significantly hamper the ability for the player to seek shelter around corners. The currently quickslot autotarget is not perfect, but allows you to shoot enemies when they are visible in most cases. I'm undecided as to whether I should improve it further, as doing so would deepen the player's advantage over ranged enemies.
