### ISSUE TITLE
Enemies don't get hit by undiscovered traps

### ISSUE THREAD

**Issue by LuisMichaelis** [00-Evan/shattered-pixel-dungeon#251]
Occasionally some enemies will walk over traps that have not yet been discovered by the hero and won't take damage. I think that this behavior is unfair towards the players and may confuse them when they get hit by the trap the enemy just walked over, especially because enemies generally get hit by already discovered traps

**Comment by 00-Evan** [comment]
This is intentional, of enemies triggered traps a large number of them would be triggered offscreen, which reduces their player interaction.

The most I may do is have enemies avoid hidden traps, but currently there is no functionality for that in the game engine. Additionally I worry that doing that would frequently tip the player off to trap locations, or result in odd enemy pathfinding.
