### ISSUE TITLE
Gladiator's combo gets interrupted in the middle of the turn

### ISSUE THREAD

**Issue by meltdown95** [00-Evan/shattered-pixel-dungeon#273]
Gladiator's combo gets interrupted the moment player chooses to use an item, but before the effect of using that item is resolved. 
Some of the items require player to make an additional choice/confirmation, usually allowing to cancel that item's use. However, the combo will break before player gets their chance to cancel item's use, thus making them lose the combo without doing anything.

The described behavior can be reproduced with the following scenario:

**Scenario:**
*Requirements:*
Gladiator with any harmful potion in inventory.

*Steps to reproduce:*
1. Hit an enemy to start the combo.
2. Open inventory, select the potion.
3. Select the "Drink" option.
4. Cancel the action by choosing "No, I changed my mind".

**Expected behavior:**
Gladiator is affected by "Combo" buff after all steps are completed; Consecutive hits increment combo counter normally.

**Actual behavior:**
After step 3 "Combo" buff disappears; Hitting enemy with an attack starts a new combo.

**Notes:**
The same behavior was reproduced with wands and Timekeeper's Hourglass.

**Comment by 00-Evan** [comment]
This is intended functionality.

Rather than having every item specifically report when it performs an action, which results in new gladiator-specific logic in every item, I opted instead to cancel a combo whenever an item is used, even if that usage may result in no action being performed, such as a throw command being cancelled.
