### ISSUE TITLE
Curse of Multiplicity: Set loot to null

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#287]
When you create mobs for the Curse of Multiplicity, you should set their loot to null to avoid endless item farming (e. g. Mystery Meat from Piranhas in floor 1 or 2). Because Piranhas give no experience and Mystery Meat (in combination with Wand of Fireblast or Frost) fills hunger, you can endlessly repeat farming. You already remove the robbed item of the Thief (and Bandit, because it's a subclass of Thief), but not the loot of any mobs.

**Comment by 00-Evan** [comment]
This is intended behavior, most curses are supposed to have specific circumstantial upsides if used correctly. I do this specifically for thieves because it resulted in easy inventory item duplication of any item the player wants (e.g. scrolls of upgrade), not duplication of that enemies specific loot.
