### ISSUE TITLE
Elixir of Might shattered by Freeze blob

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#290]
The Elixir of Might is shattered by Frost Traps, Potions of Frost and so on. In Heap.java there is a specific exception for Potion of Strength. Because Elixir of Might is the upgraded version of Potion of Strength and you often save a couple of them for later (to use them on a Plate Armor or Tier 4 / 5 weapon and for the higher HP boost), they should also be immune to freezing.

**Comment by 00-Evan** [comment]
To be honest I've always disliked the specific exception for potions of strength and scrolls of upgrade. Obviously it's overly-punishing to destroy those items but it ends up feeling very artificial that those items specifically don't break. I've also make burning and freezing more fair since then, where the player always has at least a turn or two to react before something is destroyed. I'd rather re-evaluate the system as a whole instead of slapping more band-aids on it.

Regardless, this is a place to report technical issues with the game, if you'd like to discuss game design please email me.

**Comment by vi** [comment]
> at least a turn or two to react before something is destroyed.

> This wand of prismatic light is cursed!
> elixir of might freezes!
> The flask shatters and the liquid splashes harmlessly

No turns to react.
