### ISSUE TITLE
Dropping an items consumes a whole turn

### ISSUE THREAD

**Issue by spixi** [00-Evan/shattered-pixel-dungeon#296]
If you have an unblessed Ankh and low HP or if you have too many items, but no Merchant's Beacon, you usually want to drop multiple items to get them back after revival or after obtaining a new bag or selling some items. In earlier versions you could drop two items in one turn, but in 0.72-RC-1 only one. This makes it hard to play with unblessed Ankhs.

**Comment by 00-Evan** [comment]
This was changed in 0.7.1, I standardized the time it took to drop items to be one turn as it made no sense to me that it took half a turn. This became really noticeable with the turn indicator that was added in 0.7.1.

I'm not going to outright remove it atm as I'm aware unblessed ankhs are otherwise useless, But I do consider dropping everything before dieing with one to be an exploit, and I'm not going to balance with it in mind. At some point I would like to adjust unblessed ankhs so that using an exploit isn't necessary to make them useful.

If you'd like to talk game design though it's best to email me, this is a place to report technical issues with the game, or suggest technical improvements.
