### ISSUE TITLE
Feature Request: Transfer active game between phone/android and desktop/gdx

### ISSUE THREAD

**Issue by prurigro** [00-Evan/shattered-pixel-dungeon#300]
Android needs to be rooted to transfer the active game to and from the desktop/gdx version, and even with root it's not exactly quick and simple. A feature that allows you to move the active game from one device to another would be really handy, and to avoid cheating the sending device could delete its copy once the receiving device verifies it's arrived. That way you could play on your phone when you're out and about and then switch to a larger screen when it's available.

I realize this might be a big ask considering the amount of networking code is probably pretty minimal at the moment so feel free to close this if it seems like too much work or you're not interested.

Either way, thanks for all the hard work you have and continue to put into Shattered! I would have stopped playing PD years ago if your fork didn't exist :)

**Comment by 00-Evan** [comment]
Hey Prurigro, Thanks again for you help with the original Shattered GDX port, glad to hear you're still enjoying the game!

You guessed right that this would be a lot of work, currently the game doesn't do any networking code at all on its own aside from grabbing a text document from a URL on the desktop version for the update notifier. The google play version does so some additional stuff, but it's all handled by google's libraries.

I have absolutely no idea how I would program an ad-hoc network connection between two devices so that data is exchanged effectively and securely, and all the various networking edge-cases are accounted for.

This is the sort of thing I would like to look into at some point though, as in the future (later this year at the earliest) I want to transition shattered to a multiplatform codebase and start working on more officially releasing on other platforms. It would be really nice if there was a way to efficiently sync runs between devices without enabling easy cheating. Ideally I might like for it to tie into a cloud platform, as that handles a large amount of work on my end and also means runs could be shared between more than two devices.

I'm going to close this as it's really just an idea at this point with no real plan for action, but feel free to reply if you'd like to discuss it at all.
