### ISSUE TITLE
Needs a save game / checkpoints

### ISSUE THREAD

**Issue by a-raccoon** [00-Evan/shattered-pixel-dungeon#304]
Omg this game is so frustrating, it's not even fun anymore. I had my fill of non-saving games in the 1980's... please allow players to restart at checkpoints and saves.  Make those unidentified + symbols on the floor a checkpoint.

Thanks.

**Comment by TheYsconator** [comment]
I think that not having checkpoints and saves is a major part of the gameplay experience. Also, implementing such a significant change in one go would probably require balancing changes everywhere, so it might not even be feasible to implement something like that in the near future (even if Evan wanted to). 

Though the game does have Anks! If you haven't encountered those yet: you can buy them and they'll basically revive you when you die.

(I also predict a bright future. One in which I'm getting breakfast, and Evan will tell you that, in the future, you should use Github for bugs and errors in the game, and that you should email him with any gameplay suggestions.)

**Comment by a-raccoon** [comment]
Then maybe checkpoints and continues up to level 5 so new players can actually press forward, and figure the game out without having to give birth to themselves over and over. :)   Sorry if this isn't the appropriate forum.

**Comment by TheYsconator** [comment]
No worries. Perhaps Evan can add a contributing file which mentions that Github is for bugs and what people should do when they have suggestions regarding balancing/ gameplay.

@00-Evan More info on that can be found [here](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors). It'll give people who want to create a new issue a nice banner which redirects them to that markdown doc.

**Comment by a-raccoon** [comment]
By the by, I did discover a way to `save game`.  Just home out of the game, terminate the game, and then return to the game...  you'll be given the option to continue where you left off.  If you die, you can terminate the game (ie, dev options, long-press-back to kill).  Launch the game and you can continue again as you did previously.

Truth be told, I honestly don't believe this feature suggestion necessarily constitutes as `game balance` as much as a bonafide engine issue.  It certainly isn't a little tweak or nudge.  But, I'm happy for now as long as I can cheat with one restore point. :rofl: :dagger:

**Comment by 00-Evan** [comment]
@TheYsconator I'm not interested in setting up a contributions guideline as that would imply I accept contributions, which I do not. While I do accept bug reports here because some more technical-minded users prefer it (which means reports tend to be of a higher quality), wmail is always my preferred option, why is why I always include a mention of that whenever I ask people to contact me ingame or on my website. I'm not really interested in making this an official channel to message me about the game.

@a-raccoon As has been explained, perma-death is a part of the game and I don't have any intention of putting in a checkpoint function. Improving the accessibility of the game is something I would like to continue doing but I don't intent to accomplish it by changing the genre if the game (look up roguelike games if you want more detail on that).

That exploit is odd though, seeing as the game is programmed to automatically save whenever it loses focus (such as when you minimize it), and instantly deletes the save file when the hero dies.

**Comment by a-raccoon** [comment]
This is not fun. Sorry.  I understand artistic vision, but I'm not a fan.

Hope someone will fork this project with save game and checkpoints, and host it on f-droid.

**Comment by lele92007** [comment]
On linux, you can save the game by doing these following steps :

open your "files" app,
see hidden files by pressing ctrl+H,
search for shattered-pixel-dungeon in the username file,
copy the game(number) file,
paste it somewhere,
re-copy/paste in the shattered-pixel-dungeon file
re-open the game.

/!\ you can export when you are in-game but close the game to paste the saved file.
