### ISSUE TITLE
Plate armor at armor-less challenge 

### ISSUE THREAD

**Issue by ShalokShalom** [00-Evan/shattered-pixel-dungeon#309]
Hi Evan. 

I just got an plate armor in an armor-less challenge run. It happened under the skeleton where I got the corpse dust and I guess its because I wear a ring of wealth +1.

Might be worth checking if the ring can cause such a drop in this challenge.

**Comment by 00-Evan** [comment]
Such drops are specifically hard-coded as disabled if they are disallowed by a challenge. Rather than checking when the item is potentially generated, the game checks whenever an item is placed on the ground, for any reason, and deletes it if it is blocked by an active challenge. There should be no way for plate armor to ever drop on the ground.

Are you sure you had the challenge enabled?

**Comment by ShalokShalom** [comment]
I can show you some screenshots, yeah.

**Comment by 00-Evan** [comment]
Please do, might help me track it down if there is an issue. Likely something is causing the challenge to not register as enabled.

**Comment by ShalokShalom** [comment]
Well, it works well besides of this. I have it running since days, the first time any armor has dropped.

**Comment by ShalokShalom** [comment]
![picture]( https://funkyimg.com/i/2TSsB.png)
![picture2](https://funkyimg.com/i/2TSsC.png)

**Comment by 00-Evan** [comment]
fixed in commit 1c259b789ab1644070b671d69dd98e55093b9f86
