### ISSUE TITLE
Avoid wasting dewdrops

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#31]
Stepping on a dewdrop when at full health and a full (or not yet found) dew vial wastes the drop.  Rather than that, what about just not picking it up?  (Dewdrops can always go to the bottom of any pile of items on the floor, to not block picking up other items.)

**Comment by 00-Evan** [comment]
I agree that it's a shame that dew drops are wasted, but perhaps instead of not picking them up they could have a use outside of healing.

How about, if a player is full HP with a full vial(or no vial) they will eat the drop and restore a small amount of fullness. I want to make hunger less harsh, but not in boring ways like just reducing it's speed, this seems like a nice opportunity to give a little help through new gameplay, plus it's dead easy to code.

**Comment by joshtriplett** [comment]
Nice!  Rather than making it only refill hunger when you're at full health, how about always making it refill a tiny bit of hunger?  (Enough to make you non-starving for a dozen or so turns, perhaps.)

**Comment by 00-Evan** [comment]
That would have a much heavier implication on game balance. To be clear, i'm not talking about a lot of hunger here, just a little extra so that it's a reasonable choice to use dew when at full HP, so you don't feel like it's being wasted.

**Comment by joshtriplett** [comment]
I mostly suggested it for simplicity; "dewdrops always give you a very tiny amount of food" seems easier to work with than "dewdrops give you a bit of health, unless you're full, in which case they give you a tiny amount of food".  I'm not suggesting making them a more substantial source of food.

(In any case, much like using a dewdrop for healing, it still almost always seems like a waste to use one when not fill the vial.  Refilling a tiny bit of hunger doesn't necessarily make a significant difference by itself; it's the fact that several other things depend on being non-starving to work.)

**Comment by 00-Evan** [comment]
I agree that it's less clear that using a drop when healed would restore hunger, but the point of the change, rather than to give dew drops an overall increase in power, is to give a little compensation for what would otherwise be a totally wasted drop. This means that drops as a whole aren't really stronger, whereas reducing some hunger every time would make them universally better.

Using drops with the dew vial is always going to be the most effective, I don't think there's a way to change that without making dew drops too powerful.

**Comment by joshtriplett** [comment]
Fair enough; I do still like the idea of the change.  There are a number of cases where I have a full dew vial and several ankhs, but desperately need a moment of non-starving time.  I could imagine using a drop in such cases.

**Comment by 00-Evan** [comment]
Ended up not putting this one in 0.3.0

Having dew restore hunger isn't that intuitive and is much less interesting than the current interactions with the dew vial. I think the better approach may be to add more interaction with the vial to encourage the player to empty it more often. We'll see about that, but for now I'm deferring this as it's an improvement I want to make but I'm unsure on the direction.

**Comment by joshtriplett** [comment]
How bad would it be to just 1) make sure dewdrops are always on the bottom of piles on the floor (which I think is already true) and 2) only pick up a dewdrop if it'll have an effect?  Then you don't lose a drop by touching the wrong destination square.

**Comment by 00-Evan** [comment]
certainly not difficult from a technical perspective. My issue though is that initially I was thinking about ways to increase dew drop interaction and saw this as an opportunity to pursue that. 

After thinking on it more it seems unnecessary to stick in a mechanic which requires both your health and vial to be full. I still have plans for more dew interaction but this won't be a factor for them, so yeah, I'll just make it so that you won't pick up dew if it would be wasted.

**Comment by 00-Evan** [comment]
Fix implemented indev, dew drops now refuse to be picked up if you can't do anything with them.

will close ticket and reference commit once 0.3.1 source is released.

**Comment by joshtriplett** [comment]
@00-Evan: Thanks!

**Comment by 00-Evan** [comment]
just as a note, a couple followup changes in the latest beta for clarity and balance:

dew drops now reference healing in their description and note that the player is already at fully health if they can't be picked up.

Dew drops now cannot stack past 1 drop, to prevent stacking many drops for large heals using the wand of regrowth.

**Comment by joshtriplett** [comment]
> Dew drops now cannot stack past 1, to prevent stacking many dew drops for large heals using the wand of regrowth.

Does that actually fix the issue? That just means you'd have to either use a larger area or collect the drops in the interim. I've managed a live-forever game a couple of times using a wand of regrowth (where the healing reliably outpaces starvation damage), and having to collect the drops one by one wouldn't have made that any less possible, just more annoying.

**Comment by 00-Evan** [comment]
The problem here is that not picking up drops at max HP makes it very easy to stack a great number in one tile, which players could essentially use for an instant full heal. The one thing infinite farming doesn't allow for is on-demand full healing and I don't want to change that. I'm not fixing the greater problem of infinite farming here, just counteracting the problem this specific improvement created.

There will be future balance changes to make infinite farming less powerful or feasible.

**Comment by joshtriplett** [comment]
It was already possible to step on a tile with a drop without picking up the drop, though, just by touching a square "past" the grass you want to step on. This just makes it easier.

**Comment by 00-Evan** [comment]
True, perhaps a better phrasing would be that this enhancement makes that issue much more prominent.

**Comment by 00-Evan** [comment]
Initial implementation in commit: 8334332d0fb3f97efc06f0b2228de2947c7dddd1
tweaks in commit: 432f9ee4409dd309412086ff8a2b09e36044f1a6
