### ISSUE TITLE
Character stereotypes

### ISSUE THREAD

**Issue by fjir3rq** [00-Evan/shattered-pixel-dungeon#310]
Technology has not and never had (even though this was a misunderstanding for a long time) a mere technical dimension.

It has cultural and social inscriptions, that is meanings, ideologies, expectations, perspectives etc.

By that technology is a product where the social and the technological goes together. These two nowadays cannot be thought as seperate.

The definition given above perfectly includes software and code as part of our techno-social developments.

So, bugs in that regard are not only those who explicitly represent functional misbehavior but also inappropriate representations of social values and norms.

As it happens, Shattered Pixel Dungeon keep reproducing (I understand that it's coming from the original game) some old stereotypes in terms of gender. 
A) I higly dislike that only one out of 4 characters in the game is supposedly female. 
B) This female character is presented in clothings that are following common stereotypes of how women should be dressed (plus showing bodily attributes while the supposed male characters do not).

I see that as a bug (in the cultural and social understandings of the year 2019) and would kindly ask you to address these issues in a subsequent update.

If you disagree - totally or partly - I am happy to make an even more precice line of argumentation. In any case please feel free to make counter arguments if you feel the need to do so.

Thanks for your great work and the consideration of the proposed changes to some of the graphics and balances of the game.

**Comment by 00-Evan** [comment]
To address your point, I agree that the diversity of the game's cast isn't the best at the moment, and the existing female character thematically ends up feeling a lot like "the girl character", especially given that she's basically wearing a bikini top.

I don't intend to make any drastic changes to the existing roster, as they are established characters with existing visual identities, but I do intent to add at least one new female character when I (hopefully) add new heroes. I don't expect that the diversity of shattered's cast will ever be exceptional, but I would like to get it out of 'obviously bad' territory.

Additionally, as mentioned in [this blog post](https://shatteredpixel.com/blog/shattered-pixel-dungeon-in-2019.html), I intend to eventually add splash arts for each of the heroes. The splash arts will allow for much more fine detail, and so exaggerated breasts won't be necessary to show that the huntress is female. I also intend to make her outfit more realistic for an adventurer and less revealing overall, though I will be keeping many elements of the existing design so as to preserve her visual identity.

Regarding this github issue itself, this place is for reporting technical issues with the game, or suggesting technical or mechanical enhancements. I generally prefer that more design-related suggestions go to my email. Seeing as this isn't a game functionality request, nor a bug report, I am closing this issue.

You are of course welcome to use whatever definition you like for the term 'bug' but the majority of people aren't going to agree with you. You can certainly argue that a lack of diversity is a problem for a game, and I agree with that, but it isn't a programming error. There's no reason for you to feel the need to argue for a change in how a word is defined in order to get me to listen to you, with the obvious exception of hatemail I never ignore messages sent to me.

**Comment by zetta102** [comment]
> 2019

> Getting triggered by a game

**Comment by 00-Evan** [comment]
@zetta102 that is absolutely not helpful. If you have anything of value to add please do but if all you want to do is fling insults you will be blocked.

**Comment by zetta102** [comment]
Ehhh... Who's flinging insults? Is it wrong to simply point out someone
being triggered by a game?

**Comment by 00-Evan** [comment]
@zetta102 Yes, calling them out as being 'triggered' completely dismisses their argument and only serves to belittle them. Don't try to play dumb, your message was obviously meant as an insult.

**Comment by zetta102** [comment]
Eehhh... Ok, I do understand. Have a nice one.
