### ISSUE TITLE
0.7.4b don't started

### ISSUE THREAD

**Issue by psydvl** [00-Evan/shattered-pixel-dungeon#335]
0.7.4b don't started on Android 8.1
64 bit ARMv8-A (MT6739WA)
Oukitel C11 Pro

**Comment by 00-Evan** [comment]
The latest version is 0.7.4c (the source code for this will be released shortly)

0.7.4b is likely crashing because you're attempting to sideload the google play version rather that downloading it directly from Google Play. You should either use a non-Google Play version or download the app through Google Play. This crashing is happening because 0.7.4b on Google Play is using Google's new "app bundle" publishing format, which doesn't work correctly if the APK is sideloaded. I reverted back to regular APK publishing in 0.7.4c, and intend to make the app more gracefully handle being installed incorrectly before switching back to the app bundle format in the future.
