### ISSUE TITLE
[Feature] Identify potions when they're brewed from the 3 right seeds

### ISSUE THREAD

**Issue by vahnrr** [00-Evan/shattered-pixel-dungeon#337]
I got the idea from [this](https://old.reddit.com/r/PixelDungeon/comments/cg5vh4/a_shattered_suggestion/euex7cb/) reddit comment.

I've implemented this little feature on my local build, but since you don't accept PRs I'm just gonna give you a [link to my commit](https://github.com/vahnrr/shattered-pixel-dungeon/commit/6411055ca75234875dec6e8ba7bdac5625db8066).

Hoping this commit or something similar will get implemented in the original build.

**Comment by 00-Evan** [comment]
As you are already aware, I don't accept pull requests. That includes pull requests that are a pull request in all but name.

I am aware this is a QOL feature that players want, but in future if you'd like to give support for it please just email me rather than trying to make a 'not a pull request' in the hopes that I'll accept it.

**Comment by vahnrr** [comment]
Duly noted. I'll use email instead, sorry for the inconvenience.

**Comment by 00-Evan** [comment]
No problem, I do think its a valid suggestion.
