### ISSUE TITLE
Specify more ways not to take damage

### ISSUE THREAD

**Issue by Wilker-a** [00-Evan/shattered-pixel-dungeon#339]
i believe that it would make more sense to add texts like "missed" to the reasons why one does not take damage. examples include a dodging asleep pirana, or the player not taking damage from an otherwise very accurate attack — did they miss or did i dodge? — that would also give an idea to the player about how good is the accuracy of various kinds of attacks too.

what do you think? :3

**Comment by 00-Evan** [comment]
You missing and them dodging are the same thing. In order to determine whether you hit or not the game rolls a random value between 0 and your accuracy score, and 0 and the enemy's defence score. If your accuracy roll is higher you hit, otherwise you miss. Sleeping piranha can dodge attacks if you're not eligible to surprise attack (e.g. if you're using a weapon too heavy for you), and therefore they get to roll their defence as normal. The only meaningful way you might distinguish between missing or dodging is if you got a relatively low accuracy roll, versus the enemy getting a relatively high defence roll (relative to something like the current depth), but I feel adding something like that would just cause confusion.

**Comment by Wilker-a** [comment]
i figured, but i don't think it would be confusing or distracting. if anyrhing, the visual response would be the same as 'missed' and 'paired' (i.e a yellow text followed by the same or similar sound effect).

**Comment by 00-Evan** [comment]
People already get confused when some enemies show 'blocked' and others 'dodged', as they assume those texts are representing totally different behaviors. Adding "missed" to the mix would only increase this, especially as it would seem to show up randomly in most cases.

**Comment by Wilker-a** [comment]
understandable.

btw, are 'dodged' and 'paired' calculated in the same way / are they affected all by the same criteria? what i can think of right now to lower the confusion would be to make these different texts a visual setting (i.e an opt-in setting to differentiate the causes for 'missed'), or add a sound effect for 'paired', or add something to make this difference more obvious. at this moment, i think it would be easier to tell the difference between a miss and a dodge than between a dodge and a pairing.

**Comment by 00-Evan** [comment]
See that's a perfect example of what I was talking about. All of the defense verbs (dodged, parried, evaded, blocked, absorbed) relate to the exact same functionality that I described above. I do like having the words vary a bit, but I might standardize them to either 'dodged' or 'blocked' at some point to reduce confusion.

**Comment by Wilker-a** [comment]
i understood. i just suggested 'missed' because i figured it would make it clear which side exactly made the attack fail, but that one makes sense too i guess.
