### ISSUE TITLE
Cost reworks for rare items

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#34]
Right now, if you offer a shop a Potion of Strength, Potion of Experience, Scroll of Upgrade, or other rare item, you get offered a fairly small amount of money (in the case of the potions/scrolls, the same as any other item of that type).  It'd be pretty unusual to ever sell such an item, but on the rare chance it makes sense, it seems like the shops should offer a huge amount of money for it (as in, more than the purchase price of several other items combined, making it *occasionally* worthwhile if there's something amazing in the shop or you desperately need a particular item or two).

**Comment by 00-Evan** [comment]
These items actually do have a shop value higher than other items of their type, but usually not enough so that you would consider selling them.

I'm not really eager to more heavily incentivize selling an item to the shop. With a few exceptions, like duplicates of weapons/armor, selling an item to the shop means you have just nullified potential gameplay relating to that item, hence why I have buffed and repriced many items that were commonly sold. High value potions and scrolls are the sort of item you should sell in a pinch if you really need something from a shop, and given that situation I feel like the current prices are appropriate.
