### ISSUE TITLE
[v0.7.5-beta-3] Smooth camera panning as an option? 

### ISSUE THREAD

**Issue by pierredadt** [00-Evan/shattered-pixel-dungeon#342]
I've been trying the new beta versions and felt weird in a minute and needed to close the game. 

I suppose motion sickness is relative, and when I was totally fine with the old camera I'm feeling really weird with the new one.

Would it be possible to give the option to switch from one to another?

**Comment by 00-Evan** [comment]
Please do not report beta issues or make game design suggestions here. This place is for reporting issues or making technical suggestions relating to the game's open source.

I sped up the camera significantly in beta-3, it should be almost the exact same as in 0.7.4. Are you still getting the same level of motion sickness?

**Comment by pierredadt** [comment]
Sorry about the bad issue.

Yes, that's in the beta-3 version I felt it.

That's just having a moving smoothed focus when I'm used to see linear transitions and following camera.  
That's true for a lot of topdown/isometric games I play, and is true for Shattered as well.

I'd it's not too costly to implement/maintain the two modes, I'd really love to see the option. 

That's a "deal-breaker" for me, and would stop playing further releases if not corrected.

Nice update overall otherwise!

**Comment by pierredadt** [comment]
Just so you know, I've played a bit more and revised my opinion.

The new cam is definitely less comfortable to me than the old one, but its still playable after some adaptation period. 

I'd still love to see the old cam stay as an option, but it's not as alarming as I first though it was. 

What's your preferred channel for beta feedback? As a programmer I instinctively went to your repo, sorry!

**Comment by 00-Evan** [comment]
Glad to hear the new camera is working better for you after a bit of time. I got significant complaints relating to it initially but it now seems they were a combination of the cameras low speed on early betas and change resistance. I'm afraid I don't plan to put in a toggle as almost everyone who initially reported usability issues now either prefer the new camera or are indifferent.

The best way to contact me is always via email: Evan@ShatteredPixel.com . Generally GitHub issues work well for anything technical, but in the case of the betas it's a bit awkward because there isn't any released source code for them yet.
