### ISSUE TITLE
Stylus: add the glype name in game log 

### ISSUE THREAD

**Issue by timendum** [00-Evan/shattered-pixel-dungeon#343]
Hi,
a small suggestion for Quality of life improvement: after inscribing an armor all I can read in the game log is:

_You inscribed your armor with the stylus_

It would be nice to read at least the glyph name, es:

_You inscribed your armor with the stylus with the glyph of viscosity_

**Comment by 00-Evan** [comment]
The game actually used to feature variable text there, but I have been steadily removing unnecessary variable text like this because it is problematic for translations. Because of variable grammar rules its often difficult to translate "You inscribed your armor with a glyph of X" into different languages, unless I give translators the ability to change the sentence structure for every type of glyph.
