### ISSUE TITLE
Alchemical Energy: No mentions of ways to increase

### ISSUE THREAD

**Issue by Draika** [00-Evan/shattered-pixel-dungeon#359]
I noticed there aren't any ways to increase alchemical energy  mentioned in the guide book or torn pages. Perhaps this should be mentioned in the first page?
![Screenshot_20191123_125606](https://user-images.githubusercontent.com/12569560/69472690-af257080-0df0-11ea-8202-4855d934082a.jpg)

**Comment by Draika** [comment]
On a side note, how does alchemical energy actually increase?

**Comment by 00-Evan** [comment]
Currently there are no ways to increase alchemical energy in an alchemy pot. It is created as a part of levelgen and is spent when creating more complex recipes. The alchemist's toolkit artifact is capable of generating energy, but this functionality is described in that item directly.

The guidebook doesn't mention increasing energy because there is no way to do so. The guidebook does mention energy on page 3 though, which is when recipes which use energy start showing up.
