### ISSUE TITLE
Another infinite turn bug

### ISSUE THREAD

**Issue by MiroslavR** [00-Evan/shattered-pixel-dungeon#390]
Version: 0.8.0

The following screenshot was taken after restarting the game, but the situation during the infinite turn looked the same except the Gnoll Brute was one tile above (restarting moved him down):
![infinite_turn](https://user-images.githubusercontent.com/7346770/80289732-d6d28900-8740-11ea-8256-8fa9a567c6b6.png)
I had just moved to the grass tile where I'm standing in the screenshot before the bug occurred. Maybe it's related to the fact spinners also spawn MagicMissile...

**Comment by 00-Evan** [comment]
I'll need more information to go on, was your game able to close normally (via the menu) or did it crash/require you to force close it. Is there any relevant log output (especially if there was a crash)?

**Comment by MiroslavR** [comment]
> I'll also need more information to go on, was your game able to close normally (via the menu) or did it crash/require you to force close it. Is there any relevant log output (especially if there was a crash)?

I didn't try closing it via the menu. I wanted to find out how to make a screenshot on my phone so I put Shattered in the background via the Home button to run Chrome. When I returned to Shattered, it did not resume and put me in the main menu (that may be due to my crapphone having low memory).

**Comment by MiroslavR** [comment]
Just a shot in the dark but could it be caused by `webPos()` returning `-1` here? https://github.com/00-Evan/shattered-pixel-dungeon/blob/1daea3acb7b9bcfd62e9d6426281da888bd6cc74/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/actors/mobs/Spinner.java#L136

**Comment by 00-Evan** [comment]
So there are two things to do.

Firstly, for the logs, the easiest thing to do is to enable sharing gameplay data if you're on the Google Play build of the game, which automatically sends reports. Otherwise look into apps which record the Android logcat (it's a bit verbose so you'll probably want to do a search to find Shattered's output)

As for what to do ingame, try to quit the game via the menu. If the game sends you to the menu then it's a case of the actor and graphics threads both incorrectly waiting for each other, which is trickier to debug unfortunately. If the game pauses for a few seconds then crashes, it's because the actor thread is caught in an infinite loop. That crash will show up in the logs and get sent to me if collecting gameplay data is enabled.

**Comment by 00-Evan** [comment]
Closing this as there has not been any followup and no other reports have come in relating to turn freezing for spinners or otherwise. Feel free to re-open if you get this problem again.

**Comment by MiroslavR** [comment]
So it happened again, this time in the Dwarven Metropolis. I had just defeated a Chaos Elemental when it somehow paralyzed me and an endless turn began. At the same time a different mob was being paralyzed by a shock trap in the bottom room (which may or may not have anything to do with it).

![infinite_turn2](https://user-images.githubusercontent.com/7346770/85227461-f81cc200-b3dd-11ea-8980-4b2abb7f3bd7.png)


I tried exiting via the in-game menu and the game appears to have exited normally; I was not taken to the main menu and there was no pause. No logs, sorry (these logcat apps seem to require having a rooted phone, which I don't have).

Anyway, I just wanted to let this issue be known. It's rare and seems harmless so not a big deal.
