### ISSUE TITLE
How about PC version

### ISSUE THREAD

**Issue by KOLANICH** [00-Evan/shattered-pixel-dungeon#4]

**Comment by nyuszika7h** [comment]
@00-Evan Is this still updated?

**Comment by 00-Evan** [comment]
@nyuszika7h yes, both versions are kept up-to-date with eachother, though the desktop version isn't currently widely distributed like the mobile version.

**Comment by nyuszika7h** [comment]
I can't find 0.2.3e of the desktop version, where is it?

**Comment by nyuszika7h** [comment]
Never mind, I found 0.2.3f on reddit.

**Comment by 00-Evan** [comment]
Going to work on better ways of distribution in the future (even having more links and a proper website) but for now you can always find the latest copy on Shattered's page of the PD subreddit wiki: http://www.reddit.com/r/PixelDungeon/wiki/shattered

Note that the latest version is 0.2.3f, and that due to there being two quickslots the quickslot hotkey is currently not functioning. I'm going to address this in the next update.

**Comment by vn971** [comment]
I launch the desktop version via gradle :D oO

**Comment by nyuszika7h** [comment]
*smashes refresh button in F-Droid* (yes, I know you don't control when they do builds)

**Comment by Fixer-007** [comment]
Why don't you put a link for https://github.com/00-Evan/shattered-pixel-dungeon-gdx releases on official site? BTW, PC version works to me too, thanks for that!

**Comment by 00-Evan** [comment]
@Fixer-007 The current desktop release is perpetually in pre-release form. It was made by copying lots of code from vanilla PD's own libgdx port, and I'm unsure what its future is.

I see a lot of value in a unified codebase for shattered, rather than having to port code between versions, so likely at some point I will completely ditch the existing desktop codebase and make a new unified codebase using the existing android code. That codebase will then be used to distribute builds of shattered for all platforms. Naturally some of the desktop-specific improvements i've made will be ported over, or re-implement entirely.

In the meantime the desktop version stays as limited release, its there if people dig for it, but I won't want it to get popular.

**Comment by kaleb187** [comment]
hey evan what's the link for the multi platform download and also I love what u did with the game I was wondering if there would ever be more types of enemys also I was wondering if u could do like a turtial video of how u edit some the things in the game for people who don't know thx

**Comment by 00-Evan** [comment]
@kaleb187 libgdx build releases are here (requires java): https://github.com/00-Evan/shattered-pixel-dungeon-gdx/releases

if you have general questions please email me: Evan@Shatteredpixel.com

this is a place to report technical issues with the game.

**Comment by TheYsconator** [comment]
@kaleb187 I'm going to give a three hour lecture at my university about modding Shattered Pixel Dungeon. I might be able to host the files etc... online for ya. If you want that, please remind me the 15th of May. :)

**Comment by 00-Evan** [comment]
@TheYsconator I would also be very interested in taking a look at that. Please do share it =).

**Comment by TheYsconator** [comment]
I'll put all the files on here: potteredpixeldungeon.com/cognixel

**Comment by TheYsconator** [comment]
Sadly, I didn't have the time to make beautiful slides/ documentation. However, I've put all the files regarding the mini-lecture I gave for my study association here: 
http://www.potteredpixeldungeon.com/cognixel

Basically, it is a stripped down version of Shattered that people got to add things to, just so they could get comfortable with the codebase of Shattered. If you want to follow that procedure, than you should start with 02-tutorial/00-cognixel-dungeon.tar (you can download everything in one go by downloading 02-tutorial/everything.tar instead). Then, using either git diff or manually, you can apply the other folders in order to get a playable game.

If you don't want to follow steps, or want something more advanced, I advice you to download 03-post-tutorial/cognixel-dungeon-expanded.tar, which is a stripped down version of Shattered, but still has a lot more than you'll make following the steps in 02-tutorial.

I will be removing the files in a week or so, so if you want to keep them, you should download them. This can be done easily using the Google Drive hosted version, found at http://bit.ly/cognixelGD

Best of luck, and one can always contact me if they need any help with their mod (although I'm not going to do your work ;) ). Contact info is on that site.
