### ISSUE TITLE
App does not show up in Android battery usage screen

### ISSUE THREAD

**Issue by foresto** [00-Evan/shattered-pixel-dungeon#407]
I played Shattered Pixel Dungeon for several hours, consuming about 20% of my phone's battery charge, yet the app does not show up in the Android battery usage screen. Every other app that I used or was syncing data in the background shows up on that screen, but this one is completely absent despite using more battery than all the others combined. Any idea why?

I'm running version 0.8.0b from F-Droid on Android 10.

**Comment by 00-Evan** [comment]
Shattered Pixel Dungeon is veryu lightweight in terms of processing power, so it may be possible (depending on how your device reports power usage) that the screen is showing as taking up battery instead of the app.

Shattered does not perform any special logic that may interfere with battery monitoring, so this is likely a device issue. It also shows up normally in battery usage on my test devices.

**Comment by foresto** [comment]
Thanks. I suppose I'll have to dig deeper to figure this out.
