### ISSUE TITLE
piranha don't immediately "die"

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#408]
v:0.8.0b android

If you bump a piranha on to a non-water surface, they are still "alive" for a turn until the turn in to meat. I think this is pretty consistent.

**Comment by 00-Evan** [comment]
This is due to how piranha's process not being on water. They check what cell they are on when they act, and then die appropriately if not on water. This means that when piranhas get pushed they take a moment to notice they aren't on water.

Currently the game has no functionality for a character to declare special logic when they occupy a location, only when they move of their own volition. Addressing this properly would require adding that functionality, and as this is a largely cosmetic issue it's not a priority at the moment. I'll keep this open as I would like to address it at some point though.

**Comment by whitel** [comment]
Interesting, the wya you are describing the problem seems like it has been there a long time. I just noticed it and thought it was new. Weird.

**Comment by Leajian** [comment]
I mean why not? Fishes don't die immediately out of the water in real life.

**Comment by joshtriplett** [comment]
> I mean why not? Fishes don't die immediately out of the water in real life.

Exactly. This seems perfectly reasonable to me.

**Comment by Khalarii** [comment]
The best bugs are those that are, in fact, features ;p

**Comment by brooksambrose** [comment]
They are shadows on land though, heavily implying that they are, and always have been, fish shades.

**Comment by 00-Evan** [comment]
Fixed in commit 59341628bc299dd68e6d05be3e422f495a236846
