### ISSUE TITLE
RFE: Wand of Regrowth "bonus"

### ISSUE THREAD

**Issue by whitel** [00-Evan/shattered-pixel-dungeon#409]
I think it would be cool if the wand of regrowth bumped up in power when used in a garden. Like maybe a +1. Gardens seem to be places of growth and I would think they could be "connected."

**Comment by 00-Evan** [comment]
Regrowth does need to be stronger when invested in, and this is something I'm looking into for 0.8.1 as the wand is planned to get a soft-rework. I appreciate that letting it be stronger in gardens would be thematically appropriate, but I'd rather make the wand more useful generally instead of adding specific niche benefits to it. Gardens, being rooms where hunger advances more slowly, also already naturally synergize with regrowth if you're looking to farm with it.
