### ISSUE TITLE
Corruption Wand performs too weak

### ISSUE THREAD

**Issue by Aristurtlez** [00-Evan/shattered-pixel-dungeon#411]
I miss how strong the corruption wand was in 0.7.5. I noticed that the probability to corrupt an enemy now is a lot dependent on its health, but it's a bit frustrating when it takes up to five attempts for a +6 wand to corrupt a full-health prison guard when the total charge is 8. That almost killed me in the 11th floor, which could never happen before, though corruption wand has been buffed and nerfed for many times thoughout v.0.7. I hope for some adjustment in the next update.

**Comment by 00-Evan** [comment]
Corruption is currently the highest winrate wand by a fair margin, and was even more powerful in prior updates before its most recent nerfs over 0.7.X.

It's odd that you bring up 0.7.5 though, as it was actually unintentionally weak in that update because two significant bugs were affecting its balance. From 0.7.5 to 0.8.0 it was purely buffed (bugs fixed, wand can now inflict vulnerable and hex), and is now in line to get another nerf in 0.8.1.
