### ISSUE TITLE
Brute not losing shield after 2 transfusion zaps special case

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#436]
When a Brute's _HP_ reaches 0 or below, it gets a _ShieldBuff_. If you zap it with a wand of transfusion, first, it tries to inflict damage to it, because it's considered alive, because of the overridden _isAlive_ method, but the damage is calculated based on it's _HP_, so it becomes a negative value. On second zap, it's charmed, so it's considered an _ally_ and the wand tries to give a _ShieldBuff_ with this formula `shielding = (ch.HP + healing) - ch.HT`, but this **COULD** result to a **negative** number sometimes, so no shield is given, but healing is given `ch.HP += healing`. This results to a Brute with _HP_ > 0 with _RageBuff_. On a later _act()_ tick, if _target.HP > 0_ is checked, and because that's **true**, the _ShieldBuff_ is **detached** (_or something like that, I'm not a java expert yet_), which finally results to scary Raged Brute that doesn't lose shielding overtime.

I admit it's hard to reproduce, even when it happened, after a while the shield started ticking again, probably because I damaged it and made it's HP value <= 0 again. It's a very special scary case. Maybe I misunderstood something and that scenario could not happen, but what really happened was a Brute which didn't lose shield points without being attacked first and a zapping it with the wand didn't give extra shield.
You can try is yourself if you edit a savefile correctly and create this scenario with these conditions. I would test this again myself since I'm working on savefile/editor for the PC version, but it's not finished yet.

Version 0.8.1

**Comment by 00-Evan** [comment]
Transfusion doesn't damage non-undead enemies, so the brute is not able to reach negative health on the first zap. Even if the were considered undead, the damage() method is not capable of reducing health below 0.

The second zap does not purely grant a shield. It heals first and then grants shielding if the enemy has full health but there is still healing left to give. Seeing as the brute is at 0 HP, it would just heal them.

What's happening here is the brute is getting healed out of its death rage, which is intended functionality. The brute is no longer enraged once this happens (which is why the shield detaches, which also removes any remaining shielding), and so does not get any extra damage. Brutes can only enrage once, so it dies immediately once its health hits 0 again.
