### ISSUE TITLE
Conflicting sprites for chilled vs powering-up Goo?

### ISSUE THREAD

**Issue by Oblomov** [00-Evan/shattered-pixel-dungeon#447]
Sorry I didn't get screenshots. I recently ended up facing Goo with a chilling weapon, and I discovered that the powering-up animation (before the explosion) isn't “persistent” when the Goo is chilled: you see the expanding black mist, but it quickly disappears, replaced by the “chilled” one. This requires extra attention, since the black mist expansion can be as short as a barely noticeable very quick flash.

**Comment by 00-Evan** [comment]
This isn't due to the particles competing with eachother specifically, but rather happens because the charge up particles are coded in a very brittle way, and tend to break like this when Goo isn't taking whole turns. Reworking the particles to fix this is something I intend to do, but isn't a priority atm.

**Comment by 00-Evan** [comment]
fixed in commit eb65e2b3568f207113436c0312adf043a038af06. Goo's particle effects have been completely recoded and now are triggered by Goo itself,
