### ISSUE TITLE
Save game fail to load

### ISSUE THREAD

**Issue by langdon** [00-Evan/shattered-pixel-dungeon#468]
I have a saved game that reports "Cannot read save file..." and won't load. Is getting you a copy of this bad save file useful to you for debugging purposes? (Android Samsung S20). Not a consistent problem (might be the first in fact) but kept it in case it was worthwhile.

**Comment by TheYsconator** [comment]
Could it be an old(er) save? In InterLevelScene, line 319, the message for "old save" is also "io_error".

**Comment by langdon** [comment]
No. Definitely post v0.8.

**Comment by 00-Evan** [comment]
The game only gives this error when the save file has been corrupted in storage, which is almost always a device error. This usually happens when a device is low on storage, or the app is unexpectedly killed while it is trying to save data. If a crash caused this I can fix that (infact v0.8.2a has a crash that being fixed in v0.8.2b, which is rolling out atm), but there's nothing I can do about this error in particular.

**Comment by langdon** [comment]
I figured there was no "fix" I just wondered if the "materials" would be useful to you at all. If not (which doesn't surprise me), Ill just kill the save.
