### ISSUE TITLE
Scroll of lullaby: all restored health is lost when attacked.

### ISSUE THREAD

**Issue by misterbeebee** [00-Evan/shattered-pixel-dungeon#478]
Hero read a scroll of lullaby and fell asleep. Health bar filled up near to max, while an enemy gnoll appeared and approached about 6 steps and then attacked.

When the enemy gnoll attacked, nearly all the restored health was lost (70%).

I don't know precisely how full health bar was before the attack, but I think it was over 95%.

**Comment by 00-Evan** [comment]
This shouldn't be possible, as the restored health isn't coded in any way that's distinct from regular health. Each turn your health is incremented by 1 and that can't be taken away if you're awoken. It's much more likely that the gnoll got a really good hit in on you, and you overestimated how much you had healed before that.

**Comment by misterbeebee** [comment]
Fair enough. The whole thing was a quick animation is maybe I misread it.

On a related note, it's quite jarring to watch when hero is sleeping (lullaby or just holding down the Wait button), and at first there's nothing happening on the screen (except health bar slowly growing)
and then an enemy appears and approached and attacks very quickly because there is no pause for the player to act until the hero wakes up.

On the one hand, it certain is exciting, but on the other hand, it's very hard to see what's happening.

You see similar effects when hero is paralyzed during a fight, where many attached happens quickly and it's not clear how many turns passed. (Another example is when both hero and enemy at paralyzed, the turns zoom by).

(An overall effect, and hint that the UX is weaker in these cases, is that even after playing the game a lot and winning  a few times, and learning a lot of habits, I still don't have a good intuition for the mechanics of paralysis and sleep.)

Perhaps it would the help to slow down (more real-clock seconds per turn) when hero is incapacitated (sleeping or paralyzed), at least when enemies are present, or do something in the UI so the player can see all of what happened in the past several turns that happened very quickly.

**Comment by 00-Evan** [comment]
I have experimented with slowdown behavior like this in the past and decided against it:

- the game already interrupts resting when a new enemy becomes visible, if the player has any control over their resting state. Because of this motor skill isn't a factor.
- Creating a universal time slowdown makes resting without enemies or double stuns very tedious
- It is possible to slow down the movement animation when the player is resting/paralyzed (the fastest animation otherwise), but this generally looks more weird than anything else, as if enemies are purposefully slowing down to accommodate the stunned hero.

**Comment by misterbeebee** [comment]
OK. Thanks for investigating.
