### ISSUE TITLE
immunity to succubus charm

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#484]
I played a game recently where I was immune to the charm of succubus.  I would get the message that I was charmed, but it would not take effect - I did not receive the charmed status. Is there some path in the game where you can become immune to charm?  I hesitate to report this but because it made the later levels so much easier ;p
If it matters, I think I was using a stone gauntlet as a weapon.

**Comment by 00-Evan** [comment]
charm's duration can be shortened with a ring of elements, and it can be resisted when the player has the magic immune status. Were you using either of those?

**Comment by protective1** [comment]
Not magic immune but I might have had an upgraded ring of elements +2 or +3.  If that's what was happening then it always shortened the duration of charm to 0 because I was never unable to swing at the succubi.

**Comment by 00-Evan** [comment]
Hmm, yeah that would do it but probably shouldn't. The reason that it's so effective is because charm duration is reduced by 5 turns whenever the player is hit, so succubi start by applying it at 10 turns, which then gets reduced by 5. The resistance from elements would stack with that oddly though, leading to it being effectively twice as strong as it should be. I'll get that fixed.

**Comment by 00-Evan** [comment]
Fixed in commit a53a90bba9f547e34ec381a7c3fb8b0badba9c04
