### ISSUE TITLE
Leaving alchemy pots = leaving game?

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#486]
When I leave an alchemy pot page by using my phone's back key, I return to the starting screen instead of returning to the current game I'm playing. This happened most frequently in the sewer stages, and when I did not brew anything before I left.

It's kinda confusing because everything else, including the alchemy toolkit doesn't do that.

**Comment by 00-Evan** [comment]
The alchemy scene correctly handles the back key press and attempts to switch back to the game scene. The alchemy toolkit also uses the exact same scene, with no difference in logic

Generally when this happens its because your device is doing something to force-close and/or reset the game. There isn't a lot Shattered Pixel Dungeon can do about this.

**Comment by N8fall** [comment]
Thank you for answering :D
