### ISSUE TITLE
Ring of furor doesn't apply on first melee strike

### ISSUE THREAD

**Issue by N8fall** [00-Evan/shattered-pixel-dungeon#514]
It happens when you enter a game file, descend/ascend to another floor, and when the boss' phase changes. 

For example, if you have a damage enhanced glaive(4/9 attack speed) and a +8 ring of furor(*2.45 attack speed, which makes it sub-1turn AS), getting to a new floor in demon halls causes you to get hit 5 times by a ripper demon when the battle engages whereas at other times it hits you just twice.

I started in July 2020 and have been constantly experiencing this.

**Comment by 00-Evan** [comment]
I can't reproduce this, there is no difference between the first and later melee strikes when using furor.

Your math is also wrong with regards to attack speed. A damage-augmented glaive has a 0.4x attack speed, and so a +8 furor would bring it up to about 0.98x attack speed. You're probably seeing extra damage on the first swing because the glaive is so close to being 1x that it takes many hits before you lose another turn.

**Comment by N8fall** [comment]
Ty for correcting me, guess it was my problem

**Comment by N8fall** [comment]
Sorry to keep bothering you, but could you please check the case of slow weapons and +4 furor too? I'm pretty sure it works as 0.66*1.64 but it got a lot of hits on me against gnolls and stuff

**Comment by 00-Evan** [comment]
slow as in augmented for damage, a glaive, or both?

Math would be:
Glaive: 0.67 * 1.647 = ~1.1x
Dmg: 0.6 * 1.647 = ~0.99x
Both: 0.67 * 0.6 * 1.647 = ~0.66x

**Comment by N8fall** [comment]
It happened with just a plain spear or glaive
