### ISSUE TITLE
Transmutation of upgraded artifact into sandals of nature discards upgrades

### ISSUE THREAD

**Issue by joshtriplett** [00-Evan/shattered-pixel-dungeon#530]
I transmuted an upgraded hourglass of time (+2), and got the sandals of nature (+0). I realize the sandals of nature have only three internal "upgrade" levels, and I'm not asking for the sandals to have more nuanced levels of power, but it seems like the sandals could "remember" upgrades (e.g. +2 hourglass becomes +2 sandals, upgrading turns them into +5 shoes) to avoid making transmute feel like it's just throwing upgrades away.

**Comment by 00-Evan** [comment]
As you mention the footwear of nature only have three levels internally, one for each evolution of the footwear. It isn't possibly to have a '+2' sandals because internally that would be level 0.67, which is not possible. This means upgrades have to be discarded.

However, the transfer logic is supposed to round levels (in this case 0.67 should round up to 1), and it appears that it's not doing that currently. I'll look into that.

**Comment by joshtriplett** [comment]
On Sun, Nov 08, 2020 at 08:15:17AM -0800, Evan Debenham wrote:
> However, the transfer logic is supposed to round levels (in this case 0.67 should round up to 1), and it appears that it's not doing that currently. I'll look into that.

That would have addressed my concern; thank you.
