### ISSUE TITLE
(beta) Tengu's smokebomb disappears before it blows up 

### ISSUE THREAD

**Issue by MrCocoNuat** [00-Evan/shattered-pixel-dungeon#547]
While moving at a nonstandard speed (swift armor and haste ring +0) after counting down 3 2 1, somehow Tengu's smokebombs disappeared before the smoke, leaving the smoke to explode one step later.

This happened multiple times in one fight

V0.9.1 beta but probably not originated there?

**Comment by 00-Evan** [comment]
There are a few edge-cases like this due to mistakes when programming boss abilities. The simple explanation is that the gas and bomb ticking are separate effects and don't perfectly sync up in all cases. I would like to improve it but it's a low priority as the error is purely cosmetic and only triggers in specific cases.

**Comment by 00-Evan** [comment]
fixed in commit 9a27edf1e4ae6173c4ccad97324b59ee4793eeda
