### ISSUE TITLE
[Feature Request] Add zoom buttons to the UI

### ISSUE THREAD

**Issue by theFireProjet** [00-Evan/shattered-pixel-dungeon#585]
### Description
Add an option to the settings to hide/display a group of two buttons: One button to zoom in and the other button to zoom out.

### Why? User Benefit
Zooming in and out is an important tool while playing the game.
* (Often it's neccesarry to zoom out to get an overview of the current floor and decide where to go next.
* On the other side players need to zoom in so they can precisly tap a field they want to move their character to and have the game at a comfotable size to view with their eyes.)

Currently this makes a **one-handed navigation** very unconfortable within the game, because it is only possible to zoom in and out using a gesture with two fingers.

Adding two zoom buttons to the user interface would allow an **easier and much more comfortable user interaction**. It would be possible to hold the phone and controll the game with just one hand while playing.

**Comment by 00-Evan** [comment]
zooming buttons were removed from the settings interface in a previous update as they were almost never used. I don't think they're worth the settings menu complexity. Even when playing with one hand it is easier to pinch to zoom rather than opening up menus to rapid-tap on a zoom button.

Additionally there is currently no space to add two additional buttons to the main interface. There may be room on your device, but on the game's minimum supported resolutions the interface is currently about maxed out.
