### ISSUE TITLE
Start with a dew vial

### ISSUE THREAD

**Issue by davekeogh** [00-Evan/shattered-pixel-dungeon#592]
You are guaranteed to find it on floor 1 anyway. Why force the player to backtrack to pick up the dew or waste it?

It seems like a pointless mechanic.

**Comment by schumaml** [comment]
It serves to teach that both the dew vial and the dew drops are something special - at least that's what it did for me in my first runs.

**Comment by 00-Evan** [comment]
The dew vial spawns on the floor partly for tutorialization, and parts as theming-wise it wouldn't make much sense for the hero to enter the dungeon with such a specific tool. I'm actually planning to change it to a flask or waterskin soon so that it would make more sense for the heroes to bring one.
