### ISSUE TITLE
Item renaming does not worked as expected

### ISSUE THREAD

**Issue by ElantrianRaoden** [00-Evan/shattered-pixel-dungeon#600]
Found that the enchantment name (Blazing, chilling etc. ) and enhancement level (+xxx) is still there after I renamed an item.  
For instance, a chilling runic blade +8, given a name, let's say, Frostmourne, will be a Chilling Frostmourne +8 instead. 
Hope you can have it fixed in future versions.

**Comment by 00-Evan** [comment]
As of when this decision was made, this is working as intended. Enchantment names and upgrade levels are appended to item names and important for clarity. Since this decision was made though, enchantments had their name and description text added to the item's description. I would still like to keep the upgrade number, but allowing custom names to override enchantments / glyphs is more reasonable now.

I'll consider this as an enhancement.

**Comment by 00-Evan** [comment]
Added in v0.9.2.
