### ISSUE TITLE
[Feature Request] Corrupted Heroes

### ISSUE THREAD

**Issue by issu-shooter** [00-Evan/shattered-pixel-dungeon#605]
If the dark magic can corrupt natives in the dungeon, why can't it corrupt heroes too?

Wearing multiple (not weakened) cursed items for a really long time (like, 3000 turns?) will result in a deadly count-down debuff that will kill the hero once the debuff time comes to zero.

 The debuff will only gets expelled if all the cursed items equipped by the hero are removed  After the debuff taken effect, the dead hero will become a mindless corpse like those wardens, replacing the Hero's remains but gives more loot.

Optional expansion: Being low in health accelerates the count-down
Stepping on to a curse trap while holding the debuff leads to immediate kill.

If this idea damages the overall balance then can it become a challenge?

**Comment by 00-Evan** [comment]
I would like to make more interesting curse effects in the future (currently some curses are interesting and most are boring), but I think something like this wouldn't work very well. As you've suggested it this idea would never trigger unless the player is intentionally wearing lots of cursed items, and making it more common would just turn cursed items into an instant-loss mechanic again (similar to what they were like prior to v0.4.0).

I also don't want to expand hero's remains mechanics as passing items from one run to another shouldn't be something the player is able to build a strategy around. In a roguelike game one rune shouldn't really affect another, as it is I've already nerfed remains plenty of times so that they don't significantly affect a future run.
