### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by boxleytw** [00-Evan/shattered-pixel-dungeon#609]
On Linux (via a snap), and my Android phone (via an app), Shattered PD runs great

I assume it runs on Windows but have not tried.

Would you mind updating the README with instructions for each thought-to-work platform?

The README says:
```
Shattered Pixel Dungeon currently compiles for Android and desktop platforms. It is available from GitHub, Google Play, Amazon, and F-Droid.
```
However, that does not help much for a naive user to install and play.   I found this, https://www.techwikies.com/apps-for-pc/shattered-pixel-dungeon-for-pc-windows-mac/, but again, not helpful to just get up an running without some previous tech know-how.

Love the game!  The talents system is brilliant.

**Comment by TheYsconator** [comment]
If you want to _build the game yourself_, you should have some basic Java-development knowledge, and therefore be able to follow the instructions on [this page](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/docs/getting-started-desktop.md).

If you just want to _play_ the game on desktop, every [release](https://github.com/00-Evan/shattered-pixel-dungeon/releases/tag/v0.9.1d) has a '...-Desktop.jar'. You should be able to download that .jar file, and (assuming you have Java installed) either double-click it, or (if that doesn't work) run `java -jar ./<filename>.jar` from your command-line.

The above process should be the same on Windows, Linux and macOS. (Evan does not appear to be the maintainer of the snap package, but I don't know if he endorses/ is collaborating with that maintainer.)

An official binary installer/ launcher is not a thing at the moment, to the best of my knowledge.

**Comment by 00-Evan** [comment]
Currently Shattered just has a generic desktop build (as Ysconator mentioned), this build works on all desktop platforms as long as Java is installed. I beleive Apple makes this process slightly more akward on macOS because of recently added security features, but there isn't much I can do about that atm.

The guide you linked is very old and comes from when Shattered did not have a proper desktop version. The Snap is an unofficial build of the game maintained by a separate person, it is not required to play Shattered on Linux.
