### ISSUE TITLE
Talisman of Foresight getting negative charges

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#648]
I've came across a special case where scrying a random room happened to have the rotberry fruit. That resulted me getting -1% total charge on that artifact. I'm not quite sure if they are correlated, but that's what I was doing when I noticed it.

![Screenshot_2021-03-13-06-12-31-52_6f3fe77889fbecf862f7061166760abf](https://user-images.githubusercontent.com/1816060/111019369-6ddf1880-83c7-11eb-8297-9554280e0e54.jpg)

**Comment by 00-Evan** [comment]
This is due to the talisman using the 'true' distance toward it the targeted position, not the tile grid distance. Because of this the talisman can sometimes have enough charge to go slightly less far than expected. In these cases the talisman 'cheats' and lets the shot go a little farther for better usability, but I hadn't expected there were cases that the cheat was big enough to put the talisman at -1%. I've tweaked this to keep the overall behavior but have current charge show up at 0%, not -1%.

**Comment by 00-Evan** [comment]
fixed in commit 4e4c1618ba3722c53f722c8b60d4dda73dfc132e
