### ISSUE TITLE
Discreprancy between the described damage of a LIGHT weapon and its real value

### ISSUE THREAD

**Issue by brunal** [00-Evan/shattered-pixel-dungeon#65]
`items/weapons/Weapon.java:163`: `Math.round(damage * (imbue == Imbue.LIGHT ? 0.7f : (imbue == Imbue.HEAVY ? 1.5f : 1f)));`

`items/weapon/melee/MeleeWeapon.java:98`: `Math.round((MIN + (MAX - MIN) / 2)*(imbue == Imbue.LIGHT ? 0.75f : (imbue == Imbue.HEAVY ? 1.5f : 1)))`

I believe the right value would be `0.7f` in the description. Though I like lightened weapons so I'd vote in favor on `0.75f ` :-)

**Comment by 00-Evan** [comment]
This is probably a leftover, initially the multiplier was 0.75f but i reduced it for balance reasons.

Will fix this as part of 0.3.2, thanks for mentioning it.

**Comment by 00-Evan** [comment]
This is now fixed in development and will be part of the next release of shattered (very soon, sorry for the holdup).

Will close this ticket and reference the commit when the source for 0.3.2 is released.

Also, as an aside, i'm aware that lots of the code involving weapons is messy in places (this being a good example), i'm planning on doing a refactor of weapon code when I rework that category of equipment.

**Comment by 00-Evan** [comment]
Source for 0.3.2b has been released.

fixed in commit 03848b6b32ae6117690d977831b6b542e4c32b1a
