### ISSUE TITLE
fair-weather friends

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#653]
The definitions of "ally" for Wand of Transfusion and "Ally Warp" is not consistent.

The first zap from Wand of Transfusion charms an enemy, making them temporarily your "ally".  A second zap of Wand of Transfusion even saps your life and heals an enemy because they are your "ally".  However, you cannot use Ally Warp talent to switch places with this temporary ally.

I was expecting a really interesting synergy between Wand of Transfusion and Ally Warp, but that synergy doesn't seem to exist.

![AllyWarp](https://user-images.githubusercontent.com/8593007/111077653-28eedb00-84c8-11eb-8eb6-f014649f11b3.jpg)
![WandOfTransfusion](https://user-images.githubusercontent.com/8593007/111077654-29877180-84c8-11eb-8473-fea8969306a7.jpg)

**Comment by 00-Evan** [comment]
Charmed enemies are not considered allies, all other ally-exclusive behaviors (e.g. regular position swapping) also don't work on them. I understand your points regarding synergies here, but consider that allowing this behavior would also make it impossible to attack charmed enemies with melee weapons.

The main reason why the wand heals in these cases is so that you can't use one enemy as a shield battery, and so that you can situationally heal enemies that are turned against eachother (e.g. via amok). I do agree that the wand's description isn't clear about this behavior though, perhaps it should start with "when used on allies or charmed enemies ..."

**Comment by protective1** [comment]
I agree that changing the wand's description as you specified would remove the inconsistent use of the terminology.
But if you did want synergy between the wand and ally warp, an interface adjustment could help.  Perhaps the ally warp could be implemented with a button that pops up (similar to the new gladiator combo button) whenever an ally is in view.  You click on the warp button, then click on the ally you wan to swap places with.  Then you could still do a melee attack on charmed enemies.
