### ISSUE TITLE
[Feature] Choose difficulty / leveling speed

### ISSUE THREAD

**Issue by eleius** [00-Evan/shattered-pixel-dungeon#661]
I really love the random level generation, like playing a new game every time. It's great when I have time to kill somewhere.

I'm not much of a gamer though, and I find the levels after the Goo boss *very* hard (killer robots, really?)

It would be nice if difficulty could be selected (e.g. have weaker stats for enemies, or higher stats or regen speed for player), or if leveling speed could be changed (e.g. go throught the same kind of "floor" twice before progressing to the next one, or something like that).

**Comment by TheYsconator** [comment]
This has been addressed before (See #118). Also, a bit of reasoning (albeit an incomplete one) as to why having everyone on the same difficulty level is important, is described by my comment [here (second paragraph)](https://github.com/00-Evan/shattered-pixel-dungeon/issues/583#issuecomment-755602029).

Evan has also stated [in his blog](https://shatteredpixel.com/blog/shattered-pixel-dungeon-in-2021.html#improved-new-player-experience) that 'improved new player experience' is basically on his to-do list.

Basically; rogue-likes (including Shattered) are not easy games. At first, it seems as though everything is based on luck. However, after playing more and more, you learn these [little tricks](https://github.com/00-Evan/shattered-pixel-dungeon/issues/146#issuecomment-623955754) that allow you to get further, consistently.

Making the game more easy in general (or by allowing you to choose an easier difficulty) is not going to help you in discovering these tricks. Of course you can try to snowball your way down the dungeon (that's not a sarcastic suggestion, but actually a valid strategy), I recommend you to learn the game by getting further in steps. In other words: aim for the first boss (and just the first boss!) first. Allow yourself to use up all resources that you have, _just_ to get past that first boss.

Once you can do that consistently (say, three times in a row), aim for the same (still; _just the first boss_), but now with certain requirements. As you'll discover: not everything is random in this game (though most things are), and would like those requirements to those not random things. For example: finish the first boss, _but without_ using any healing potion, _whilst_ having the dew vial, _whilst_ having found at least x potions of strength, and (possibly) _whilst_ having completed the quest. (Tweak to your heart's content.)

After being able to defeat the first boss with these requirements, try to defeat the second boss by using everything up just to defeat him. Then set additional goals for the second boss. Then use everything for the third again, etc.

I'm sure there's a different way of learning this game for each and every player, but this used to be my method (and it worked quite well). Though, if you do not want to get better in the game by learning those tricks I wrote about earlier, and you basically want to get your wins thrown at you from the moment you pick up the game; then this is not the game for you.

(Ah and Evan, I must admit that I really hope that you find a neat way to not give away those little tricks, whilst still being able to guide new players, in whatever new way of teaching new players you're brewing up. I thought about a solution for a bit (though probably not as long as you have), and I must admit that there were always caveats popping up when I thought about my ideas a bit longer.)

**Comment by 00-Evan** [comment]
As mentioned by @TheYsconator , I don't intent to add difficulty selection to the game, but do want to keep working on improving the new player experience. Here are some ideas I'm current considering for that:

- A guided tutorial, which explains basic gameplay concepts to the player and **strongly** encourages use of the examine button. This tutorial would likely directly explain surprise attacks (they're just so important), but wouldn't go much further than the guidebook otherwise.
- Visual/mechanics tweaks to the early stages of the game to better point players toward the right strategies. I've already done lots of these in the past, such as adding snakes, giving surprise attacks a visual indicator, or adding the current sewers minibosses.
- Improvements to the guidebook to better prioritize info that the player needs currently, perhaps adjusting it to be a bit more of a dynamic tip system. The goal would be to improve the timeliness and relevancy of info, not to make that info more direct than it is atm.
- Possibly adding a 'starter' mode to the game, with reduced difficulty/complexity and a limited number of floors. This mode would specifically be to give players an easier introduction to the game's mechanics. Mechanics tweaks would exist here to both make the game easier and to more strongly encourage gameplay patterns that are useful in the main game.
