### ISSUE TITLE
No blacksmith upgrade with broken seal attached to armor

### ISSUE THREAD

**Issue by karoshi42** [00-Evan/shattered-pixel-dungeon#666]
Hey :)

I think I found a small bug with the troll blacksmith: I used the troll blacksmith with an scale armor +2 with a Warrior's broken seal +1 attached to it (so effectively a scale armor +3)  and another scale armor +3. The resulting armor was a scale armor +4 with the seal still attached. This would probably be correct without the seal, but this way i got no upgrade, since I would have had the same effect by just switching the seal to the other armor.

**Comment by karoshi42** [comment]
Oh, I saw too late that you don't accept PRs, so I didn't open one. But I think that the code in the fork should fix this by using the item with the seal as item2, if the levels are the same.

**Comment by 00-Evan** [comment]
So let me be sure on the sequence of events here:
- you had a +2 armor with the seal and another +3 armor
- the resulting armor was +4 with the seal
If so then that is impossible.

When the lower level armor has the seal, the seal is removed from it and dropped when that lower level armor is destroyed. If the higher level armor has the seal then the upgrading occurs normally.

The only way for the result to occur is if the +3 armor had the seal, which which case everything is working correctly.

**Comment by lele92007** [comment]
i think he have 2 +3 armor, 1 with te seal and 1 wthout, and the blacksmith forged a +4 armor Without any seal this is correct, but, because the seal can move another +1 to the second armor, it's not correct
situation :
Armor 1 : +2; +1 due to seal, total : +4
Armor 2 :  +3, total : +3
Final armor : +3; +1 due to seal, total : +4

**Comment by 00-Evan** [comment]
@lele92007 I see, that makes more sense.

I can see how two equal level armors (one with the seal) would cause the seal's +1 to be lost. Probably the answer is to have the game prefer the armor without the seal in these cases.

**Comment by 00-Evan** [comment]
I've been thinking on this one a bit more and ultimately think the functionality should remain as-is. Currently the blacksmith has the following logic:
- highest level item is kept
- if items have the same level, item on the left is kept

I can see how two +3 items, one with the seal, can result in one total upgrade being lost if the seal-ed armor is on the left, but adjusting the logic to prefer the right armor in this case is extremely unintuitive and can lead to other problems. For example, the player may have a glyph on the left armor they wand to keep, but would be unknowingly losing it in this case.

Ultimately I eventually plan to rework the blacksmith's reward, and so for now I'm going to leave this as-is because fixing it would produce issues elsewhere.
