### ISSUE TITLE
Google play with microg

### ISSUE THREAD

**Issue by UltraBlackLinux** [00-Evan/shattered-pixel-dungeon#668]
Hey there,

I am using the aurora store with microg and i recently updated shatteredpixel. Now it can't find the gdx library - is there a way to make it work together, or is too much of a hassle?

Thanks!

**Comment by 00-Evan** [comment]
Likely that's happening because you're not getting the native libraries that Google Play normally dynamically includes with the app as part of their newer app bundle format.

I have no idea what may need changing on your end so that aurora downloads the right natives.

You can also just use the APK files hosted here on GitHub.

**Comment by UltraBlackLinux** [comment]
Ok, I guessed so.
Thank you.
