### ISSUE TITLE
Sad Ghost locked out of dwarf king's lair

### ISSUE THREAD

**Issue by protective1** [00-Evan/shattered-pixel-dungeon#692]
Summoned Sad Ghost using Dried Rose.  Used mirror image (as cast from Unstable Spellbook).  Entered dwarf king's lair - and the Sad Ghost got locked out (because the mirror image was faster)!  It feels like this shouldn't happen, but I don't know how you could fix it.
![Screenshot_20210508-191022](https://user-images.githubusercontent.com/8593007/117560341-fcd08000-b05a-11eb-9bea-2b32b3188b85.jpg)

**Comment by 00-Evan** [comment]
This is because when the hero passes that door, only a single ally is brought with them, with no preference given to stronger allies. This is old logic originally written for when there were far fewer allies, so probably it should either be extended to more than 1 ally, or adjusted to prefer stronger ones.

Only real balance consideration here is that I don't want to encourage reading 1 or 2 mirror image strolls before the fight as a strategy.

**Comment by 00-Evan** [comment]
I've decided on the design for this. Moving allies into closed boss arenas now uses the same logic as allies moving with you between floors: infinite numbers, only intelligent allies, non-ghost allies also need to be near you.

**Comment by 00-Evan** [comment]
fixed in commit 9412eb81f4f1c933666288154c3ac5072c89e49f
