### ISSUE TITLE
Odal rune

### ISSUE THREAD

**Issue by jimr1603** [00-Evan/shattered-pixel-dungeon#698]
At least in my experience, "odal" tends to be the name of the rune when attached to Nazis, and Pagans/Scholars tend to use "othala". Is it worth relabelling?

**Comment by 00-Evan** [comment]
From taking a look it seems the troubling association is if the rune contains wings at the bottom, which the rune in the game obviously does not. I'm not able to find any sources which tie one wording or another to Nazi ideology, even articles which discuss the rune in a Nazi context use either term, or even both.

Obviously I don't want to include Nazi symbolism in Shattered, but this doesn't seem to be the case with the Odal rune as the game doesn't include the wings. Just like with the Swastika, Odal wasn't originally a hate symbol as well. The Swastika is unfortunately lost because the association is so strong, but Odal with no feet seems to be salvageable, so I'd rather not treat it as a hate symbol.
