### ISSUE TITLE
Scroll of Retribution is more powerful at high HP

### ISSUE THREAD

**Issue by AddisonG** [00-Evan/shattered-pixel-dungeon#701]
I was reading your entire codebase like a book, as I do, and noticed a problem in the [Scroll of Retribution](https://github.com/00-Evan/shattered-pixel-dungeon/blob/master/core/src/main/java/com/shatteredpixel/shatteredpixeldungeon/items/scrolls/ScrollOfRetribution.java).

I can see that when you refactored the code in [this commit](https://github.com/00-Evan/shattered-pixel-dungeon/commit/644e6543ad841b2c475cf9ef64400f472b05fef7) you accidentally made the scroll MORE powerful when you're full HP.

![image](https://user-images.githubusercontent.com/5109532/118926101-1fc83180-b983-11eb-861b-7efe37bcb4d6.png)

In the past, before this change, it used to be divided by 5. But since this change, it's the opposite! You made it multiply instead of divide, which you would think is correct, given the name of the variable, but it's not.

I would recommend either renaming the variable, or dividing when it's initialised, and then using that later as a flat value:

```
float power = Math.min( 4f, 4.45f*hpPercent) / 4.45;
...
mob.damage(Math.round(mob.HT/10f + (mob.HP * power)), this);
```

inb4 you edit the post for having code suggestions.

I do **amazing** code review, and you know it.

**Comment by 00-Evan** [comment]
> I do amazing code review, and you know it.

I didn't ask for code review, you're also incorrect.

the power variables scales from 0 to 4, depending on how low the hero's HP is (capping at 4 when hero is at ~10% HP)
at 0 power, the scaling part of the damage is: HP*0*0.225 = 0
at 4 power: HP*4*0.225 = HP*0.9
This is exactly in line with the comment I added

Power/5 is equivalent to power*0.2f, which is why this commit is not changing the logic other than shuffling the power balance slightly.

I tested this in game to confirm and retribution is absolutely stronger at low hero HP.

in the future, please just report a suspected issue when you see it. I don't need nor want someone to analytics my code, both because it often just generates more work, and because accepting 'code review' style issues risks giving that person partial copyright over the codebase.
