### ISSUE TITLE
Zooming in/out with mouse wheel is inconsistent

### ISSUE THREAD

**Issue by Block-Vader** [00-Evan/shattered-pixel-dungeon#706]
When playing on desktop I sometimes have to turn the mousewheel multiple times in order to zoom just once, other times a single turn results in maximal zoom. Zooming with +/- keys works as intended.

**Comment by 00-Evan** [comment]
This is intended for the moment. The zoom snaps to specific multiples of the game's base size to avoid visual artifacting. This means that between 1x and 2x, or 2x and 3x, there is a fairly large jump. Rather than each ratchet of the scroll wheel moving from one zoom level to another (which would be a huge jump), each ratchet counts as about a 10% increase/decrease.

**Comment by Block-Vader** [comment]
Oh, I get it. But I still think there is an issue. After zooming in multiple times in a row with the keyboard, turning the wheel just once zooms out multiple times and vice versa.

**Comment by 00-Evan** [comment]
Ah, that should be corrected, ty.

**Comment by 00-Evan** [comment]
fixed in commit 6e324d7d0b2ef4a0d0aa98196277cf65b5435804
