### ISSUE TITLE
Book afklter killing 2nd boss not permanent

### ISSUE THREAD

**Issue by eeyrjmr** [00-Evan/shattered-pixel-dungeon#71]
After you defeat the 2nd boss you get the book to tailor your skill. This use to be kept.

However... Recently starting from scratch (new phone and no way to backup pixel) meant starting from scratch.  None of the classes are able to keep their book

**Comment by 00-Evan** [comment]
This is an intentional change. Presumably because you had your save data wiped the game didn't show you the popup informing existing users about this change.

Basically it's a change made for better earlygame balance (early enemies were made weaker to compensate, and are actually going to be softened up a bit again soon), and  to make room for more subclasses, which are more niche in design.

**Comment by eeyrjmr** [comment]
ahh right yes never saw that...
Sort of makes sense as it did give a bit of an adv for the 1st levels.
