### ISSUE TITLE
Feature suggestion: Steam + Workshop integration

### ISSUE THREAD

**Issue by logicminimal** [00-Evan/shattered-pixel-dungeon#720]
This is a huge huge suggestion so i doubt if it would  be integrated even in a few years but there it goes: 

- Add the game to Steam:
    i think it would be good for this game to be sold on steam, i would buy it personally

- Steam Workshop integration ( the extremely hard part ):
    The game should be fully integrated into the steam workshop, and i have a few ideas on how it could be integrated on it
    > Normal Content mods: These mods add computationally easy stuff into the game, for instance new mechanics, new scenarios, new weapons, classes and etc.. Now these mods would be made in Lua + Xml ( I dont know if those are exceptionally easier to implement, it just means that it should use some kind of simple and interpreted language as the base for simple mods. ) These mods would be simply hosted on steam workshop, you could compare these to Terraria mods, just in lua or py. also these games should be up to date with the game, or it could choose a version to be in, i honestly have no idea.

    > Forks and different base mechanics: These mods are basically just forks of the shattered pixel dungeon. These mods are just forks of this game, like summoning pd and lot others. Those games will choose a version of the original game that they will base their fork on ( it is already this way on github but i doubt if steam workshop would allow this ), those would be hosted as plain JAR's(?) of the game in the steam workshop, and the game would just switch to these executables upon loading the game, or they could coexist through something i dont currently know. the one problem is that those are extremely prone to having malware to it

**Comment by 00-Evan** [comment]
I do intend to release on Steam in the future, although I plan to release on iOS first (more info coming on that soon)

Unfortunately I don't have any plans to add workshop support. The amount of code changes that the game would need to be able to properly expose a modding API would be massive, especially for an API that would be comprehensive enough to let modders do even just some of what they can do with the open source. The game would basically need to be reprogrammed from scratch. Simply relying on code modification isn't possible due to security concerns, as you mention.

Fundamentally I want to spend the bulk of my time expanding Shattered, not making it easier for others to make their own mods. Though of course the source is always there and I have no plans to change that.
