### ISSUE TITLE
User-identified potions/scrolls

### ISSUE THREAD

**Issue by markmliu** [00-Evan/shattered-pixel-dungeon#74]
It'd be nice if there was a way for users to mark a scroll or potion with what they "think" that item is.  Sometimes I figure out what an item is by process of elimination, then come back to the game later and don't remember what it is.

**Comment by 00-Evan** [comment]
Most people handle this using an external note-taking app. Probably if I do end up supporting user-entered information like this i'll just develop a note-taking system that you could tap into from the main game UI. This way any info the user wants to remember can be entered, rather than having to develop a solution for each specific case. Language used to be a big issue for this, but with the new text system that's no longer a problem.

**Comment by markmliu** [comment]
I was picturing maybe adding a "self-identify" addition to the dropdown menu with "drop, throw, use", bringing up a dropdown menu with each possible symbol, which would then be what that potion is identified as, except with some visual cue that it's not truly identified.  I think that might be a little more convenient and easy to use than a separate note-taking app.  What do you think?

**Comment by 00-Evan** [comment]
It would be, but it also only specifically supports potions and scrolls.

Say the player also wants to record that they want to return to the floor 6 shop when they have 500 gold to buy an ankh, or they left a scroll of upgrade on floor 7 because they accidentally lost a levitation potion and need one to get to the scroll, etc.

The note-taking, while less convenient in some cases, acts as a catch-all for anything a player wants to remember.

**Comment by TheCanadianAlligator** [comment]
Weapons, armours, and misc items too! This is really only a cursed/not cursed sort of thing, but it really helps. Scroll of Remove Curse isn't very precise unless you make it precise.

For example, when you have 2 plates - one you know is curse-free because risk taking earlier on, and one you just picked up that you found out was cursed from a scroll of remove curse. If you had a note applied to the plate earlier on, you would know which one was the good one.

**Comment by 00-Evan** [comment]
Closing this as the suggestion, as given, won't be implemented. However, custom notes are something I have on my list of stuff I'd like to do.
