### ISSUE TITLE
QoL suggestions

### ISSUE THREAD

**Issue by Leajian** [00-Evan/shattered-pixel-dungeon#742]
1. **Ignore projectile throw** when there are no targets. Exceptions exist, like wand of warding, bombs, seeds, huntress bow when she has Seer Shot talent and other throwables that don't involve immediate attack.
2. **Quick-use popup**: Use the very same item for targeting, instead of the Magical Holster in the quickslot. Reduces misfires and makes it easier and faster to use.
3. **Long-pressing the attack button** fights to death (either the hero's or the enemy's).
4. **SnapTap**: Move commands attach near to commonly preferred locations. For example tapping near (locked or not) doors, ladders, items, etc will change hero's move tile to them instead. In addition, ignore multiple taps on the void. This could reset per floor entrance, because you may want once or twice per floor to jump down for some reason. This could reduce the annoyance of the jumping confirmation dialogue popping all the time from mistaps. Also when giving move commands, attach to the closest moveable path when tapping on the void instead. Double tap confirms the jump and ignores SnapTap. SnapTap could be a togglable option in the settings or in-game while playing.
5. **Deadzone** for taps around a certain "cubic" radius around the hero. Double tap cancels the deadzone effect. Reduces mistaps. The "cubic" radius could be relative to the current zoom and the the screen's dimensions. For example, tapping near your quickslot, bag or near hero status box, could lead to such mistap.
6. **Book of Practical Applications of Alchemy**: Include information about with seed leads to which Potion. Could be useful for new players or it could be knowledge acquired through experimentation and should not be included.

**Comment by 00-Evan** [comment]
I'll reply to each your suggestions. In future, please don't open an issue with a whole bunch of different ideas as once, it's better to email me with such things.

1. I have no idea what you mean by this. "ignore projectile throw" makes no sense. Do you mean that it should be impossible to throw items when no enemies are around?
2. I'm assuming you mean that the auto target would occur by opening the quick use window a second time and tapping the same item? This would be substantially slower than just ignoring auto-target and tapping on the target you want to attack.
3. I'm not interested in adding anything that significantly automates gameplay.
4&5. It is extremely dangerous to assume what sort of input the player wants to give, as the game will invariably be wrong in a bunch of cases. Adding a snap-to function near a door sounds good when you want to walk into it, but it would be extremely frustrating if you want to walk next to it. I would rather have the game trust that the player has given the correct input, instead of assuming they meant something different than the input they gave. There can be exceptions when the input is extremely likely to be a mistap though, for example the click regions for most interface buttons are actually already slightly larger than the buttons appearance.
6. The game already does this when you place 3 of the same seed in the alchemy interface. Placing anything less than 3 of the same seed results in a random potion, with a chance to relate to one the seeds used.
