### ISSUE TITLE
Save/Load function (Badge Disabled, no record)

### ISSUE THREAD

**Issue by KOIAUR** [00-Evan/shattered-pixel-dungeon#743]
It would be nice to add a function to write and load a save file. It is provided in the form of a checkbox and can be set in the options, and will be applied from the next game. When I try to use this feature and start the game, I get the following warning message: "Are you sure you want to save? If you save, you will not be able to earn badges. Also, no records will left. Confirm or cancel." This warning only appears once and is saved immediately thereafter. Clicking Cancel immediately clears the option. Once a save file is created, the badge earning ability is permanently removed from that file. The save file is saved in a separate directory without being hidden. It can be backed up or shared via a USB connection.

I wish it would be compatible with the PC version, but I don't think it's necessary.

After all, The badge will prove your skills, so I don't think it's completely against the spirit of roguelike.

**Comment by Leajian** [comment]
This defeats the whole purpose of the rogue-like game theme. Are you sure you know what this means?
> Roguelike (or rogue-like) is a subgenre of role-playing video games characterized by a dungeon crawl through procedurally generated levels, turn-based gameplay, grid-based movement, and permanent death of the player character.

Taken from wikipedia : https://en.wikipedia.org/wiki/Roguelike

**Comment by KOIAUR** [comment]
Dying is not the purpose of a roguelike. The goal is to go to the end and win. These actions are meaningful only when records remain, and if the records are deprived, it will be meaningless, so it will be a waste of time for those who want a challenge.
But it will be helpful for those new to the game, or those who aren't taking it too seriously.

**Comment by TheYsconator** [comment]
I can see how your suggested feature could be useful, and generic saving and loading has been requested multiple times by now (e.g; #1 and #304) - showing the idea appeals to more players. However, those players may not be in the target audience for such a modern-day-but-classic-roguelike that Shattered is. Dying may not be the purpose of roguelikes, but permadeath definitely is an important trait of them.

I hope you can see it there's also quite some downsides/reasons not to implement the functionality you've suggested:

* It doesn't feel very roguelike-y (as mentioned)
* It could give a not-so-fully-earned feeling of accomplishment to the player
  * As in: finishing the game (as it currently is) gives you a nice amount of bragging rights, whereas I would give none to players who used a save/load system - even more so when challenges are involved
* It sounds a bit dark-pattern-like to have players waste their time in such a way
  *  As in: being allowed to spend hours on a run (all those restarts included), just for it to never be recorded anywhere
* It makes comparing achievements more difficult (see my first comment on #583)
  * So a different/no victory scene would have to be shown, and there would have to be some indicator on-screen during a run
* It takes additional design and development time

So in my opinion; you gotta work to finish this game, especially with (multiple) challenges. So 'just wanting to finish the game' is something I'd consider a non-argument.

I also can not really see if this is what you're suggesting, but: are you suggesting that challenges should be unlocked in the normal version of the game, once you've cleared them in the with-saves version? Because I can not see how that would make sense. If one can not even complete the normal game without challenges, how are they then going from saves+challenges directly to the even more difficult normal+challenges?

In my opinion, your 'helping beginners learn' is your strongest point. However; I think there's many ways for players to learn this game - one of which is simply by ~dying~playing a lot. Assuming this is the type of game for you: what are you exactly missing as a new player, and how would this feature help in filling that gap?

**Comment by 00-Evan** [comment]
There's been a fair bit of discussion here already, so I'll try not to repeat it. Here are my main points:

- Permanent death is a core part of Roguelike games. I'm not as stuffy as some, and I think the definition should be a little flexible, but the permanent death is pretty non-negotiable. If the game has saves, it's not a roguelike.
- I agree that the game could do with being more approachable, but I don't think this is the right way to do it. Giving new players saves will cheapen the regular game and encourage bad strategies, as they'll be learning the game in a context where death doesn't carry a penalty.

If i were to ever implement an alternate easy game mode with the goal of helping players learn, I would be very careful to have it not encourage gameplay that isn't useful in the main game, and I would restrict how far the player can go (e.g. they could maybe get up to Tengu), so that the full regular game isn't cheapened.
