### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by Hoto-Mocha** [00-Evan/shattered-pixel-dungeon#748]
When I freeze time, then step on some traps, and try to escape with fadeleaf(warden's ability), the game displays an error and deletes the save.

You will be able to understand what I'm saying if you see this video.
https://youtu.be/wLTb31LlmVA

**Comment by PixelMonkeyPro** [comment]
Wow. It's a wonderful phenomenon, I've never come across such a situation, such a way of death is really great! May I venture to ask what the error is? I don't understand Korean.Thanks. (· ω ·)ノ

**Comment by Hoto-Mocha** [comment]
@PixelMonkeyPro You mean this?
![Screenshot_20210630-155214.jpg](https://user-images.githubusercontent.com/76470428/123915149-26eb5200-d9bb-11eb-83ec-cc785a1075c3.jpg)
Killed by: rockfall trap

**Comment by Hoto-Mocha** [comment]
@PixelMonkeyPro Or this?
![Screenshot_20210630-155430.jpg](https://user-images.githubusercontent.com/76470428/123915473-821d4480-d9bb-11eb-96eb-a4e9f3d73d8c.jpg)
Error
Unable to read saved game. If the same error occurs after restarting, the game you saved is damaged. I'm sorry.

**Comment by PixelMonkeyPro** [comment]
> @PixelMonkeyPro还是这个？ 错误 无法读取保存的游戏。如果重新启动后出现同样的错误，则您保存的游戏已损坏。抱歉。
> ![截图_20210630-155430.jpg](https://user-images.githubusercontent.com/76470428/123915473-821d4480-d9bb-11eb-96eb-a4e9f3d73d8c.jpg)

this,Thanks.

**Comment by PixelMonkeyPro** [comment]
I think the reason for this error may be that your death triggered a bug that caused the archive file to be lost. I would like to ask if there was a program flash back or a program close operation at the time of death.

**Comment by Hoto-Mocha** [comment]
Anyways, it's an error, so I reported this.

**Comment by 00-Evan** [comment]
The reason this is happening is because the player dies from the traps and is then teleported away. Player death deletes the game save, which causes the loading error to appear. Normally the plant's effect would resolve before the time freeze ends, but because the player is moving between depths the time freeze is cancelled first.

This is a really interesting case of multiple game mechanics stacking on each other, probably time freeze should be adjusted to simply cancel out trap effects when it is broken by moving between depths, instead of triggering them.

**Comment by 00-Evan** [comment]
fixed in commit 74762c158f52e14665d4b7fc8aac80d38c1d1bf8
