### ISSUE TITLE
Runaway FPS in Fullscreen Mode Java edition, aka. missing FPS cap for Fullscreen mode. 

### ISSUE THREAD

**Issue by Burn1ngShad0w** [00-Evan/shattered-pixel-dungeon#761]
Surely you heard of the new Amazon Game "New World" [frying high-end GPUs](https://www.forbes.com/sites/paultassi/2021/07/21/warning-amazons-new-world-is-bricking-a-specific-type-of-gpu/) sometimes just by rending the ingame menu.
Well it seems the java version of this game behaves very similarly At least with my setup (2080Ti). Luckily the high-pitch vibration of the GPUs power delivery, discouraged me to play the game in Fullscreen more than a few minutes, before switching back to windowed mode. But with the "New World" bricking GPUs in in the back of my mind, I decided to go back to shatterd PD fullscreen mode and do some troubleshooting: First thing I did was running GPU-Z on a second Monitor and what I found was, turning on fullscreen, my graphics card immediately jumped to the max. boost clock and power draw ( +110 Watt!). So I tried setting the max FPS for Java, in Nvidia control panel, to 120 FPS. First thing I noticed was that the anoying high pitch vibration sound was gone! I checked GPU-Z again and now my GPU clock was as expected at the minimum clock speed, and power draw only went up 2 Watts. A huge difference! I understand that my case might not be a common one, but it shows how the fullscreen mode is putting a unnecessery load on the gpu an therefore drawing way too much power, which again it does not need to. So maybe add a fps cap to the fullscreen mode so PC players don't get high electricity bills at best and brick their GPUs at worst.

Here some GPU-Z screenshots showing how running fullscreen uncapped is drawing 167 Watt, while capped at 120 fps only 57 Watt.
Idle:
>![GPU-Z_idle](https://user-images.githubusercontent.com/2158585/128775153-a209a503-0425-4d1c-be6f-31a9f71c78ab.gif)
4K windowed:
![GPU-Z_4K_windowed](https://user-images.githubusercontent.com/2158585/128775235-5eebecfb-3774-4587-b428-9e6865968af7.gif)
4K fullscreen uncapped:
![GPU-Z_4K_fullscreen_uncapped](https://user-images.githubusercontent.com/2158585/128775451-3ad99aea-c524-41f3-9235-26332e43e462.gif)
4K fullscreen 120FPS:
![GPU-Z_4K_fullscreen_120fps](https://user-images.githubusercontent.com/2158585/128775479-79cb5108-5f6a-47d2-8b5a-463acb035424.gif)

**Comment by 00-Evan** [comment]
Firstly, please understand that the recent GPU frying situation is caused by hardware defects. If a game ever kills a GPU by running high FPS in a menu that is a fault of the GPU, not the game. That high pitched sound you heard is coil whine, and while it's annoying it is not indicative of an impending hardware failure.

Shattered Pixel Dungeon uses the libGDX game library on desktop, which in turn uses LWJGL3 for its graphics, which in turn uses GLFW for its windowing system. The game does request that vertical sync is enabled at all times (which caps fps to the display refresh rate), but this is sometimes not respected due to either GPU driver errors or library errors.

Try using the beta for v0.9.4 that just released, which uses the most modern version of libGDX. If the issue persists try updating drivers, and after that I would suggest opening an issue for the game's libraries.

**Comment by Burn1ngShad0w** [comment]
Thank you for the explanation. The beta works greate for me! No coil whine and almost no energy consumption. Seems like it was a bug in the games library then...
