### ISSUE TITLE
Enchantment Scroll is wasted if the game closes before selecting

### ISSUE THREAD

**Issue by 50m31-AW** [00-Evan/shattered-pixel-dungeon#777]
I'm playing v0.9.3c on Android 10 and I had just made and read a Scroll of Enchantment. Before selecting my enchant, I checked the wiki in chrome to read about the options. When switching back, I accidentally hit the "close all apps" button. When I returned to game, I found that it had used the scroll and my weapon had no enchantment (to my great frustration)

This issue could also potentially arise from Android's default behavior of restarting apps to save resources, or if a game was interrupted by a phone call

I don't know how feasible this would be, but I think an ideal solution would be to save whether or not an option was selected, and then prompt the selection when returning to game

**Comment by 00-Evan** [comment]
This is intentional to prevent an exploit where people could close the app to keep their scroll if they didn't like the options. Android generally does not close very background apps unless you have an aggressive battery manager installed.

That being said I am planning to add a bit more info to the window at some point, which should reduce the need to swap to a wiki page.

**Comment by 50m31-AW** [comment]
The app reloading also occurs to conserve other resources, such as RAM, which means it happens rather frequently on lower end devices. Something like a phone call interruption could easily trigger it, meaning switching back to Pixel Dungeon would load at the main menu, rather than in game

Would it not be possible to solve the exploit by saving what item was selected, the options presented, and then automatically opening the enchantment GUI upon returning to game?
