### ISSUE TITLE
I cannot install the APK for 1.0.0 at all.

### ISSUE THREAD

**Issue by BlueManedHawk** [00-Evan/shattered-pixel-dungeon#784]
When I try to, the "Staging app..." bar appears and completes, I click "install", the bar gets to the end, and a screen pops up saying "App not installed.".

**Comment by QuasiStellar** [comment]
You need to enable "Install apps from external sources" on your device.

**Comment by nerdydude1111** [comment]
that does not work

**Comment by nerdydude1111** [comment]
just put the update on f droid please

**Comment by 00-Evan** [comment]
@BlueManedHawk Can you tell me where you had the game installed from? The F-Droid version in particular uses a different signing key than the Github version and so you have to uninstall first.

@nerdydude1111 I have no control over when F-Droid releases updates, they are totally independent from me. I actually dropped them as an official distribution of the game specifically because they often lag by a week or more and there's nothing I can reasonably do about it.

**Comment by nerdydude1111** [comment]
@00-Evan oh ok well I hope it gets updated soon for now ill play the new update on pc. Is there a way to donate that isnt patreon?

**Comment by 00-Evan** [comment]
Closing this as it's not an issue with Shattered. Sorry about F-Droid's update delay.
