### ISSUE TITLE
Add ability to explore the map with two fingers sliding on iPad’s keyboards

### ISSUE THREAD

**Issue by built2spill69** [00-Evan/shattered-pixel-dungeon#810]
At the moment, you have to hold click to explore the map. This feels way less unresponsive than usually using two fingers to scroll, explore Maps, etc. Although, zooming by pinching the track works. Please, add the ability to scroll through the map according to the usual iPad’s touchpad controls.
Thank you.

**Comment by 00-Evan** [comment]
I'm not sure what you mean by this. Ipad's do not have a touchpad as far as I'm aware, and scrolling the map is already possible by just using one finger (just like scrolling through a feed in a social media app).

**Comment by built2spill69** [comment]
By touchpad, I mean « iPad connected to a keyboard such as Magic keyboard » ; you may understand me when you’ve seen this : https://www.apple.com/ipad-keyboards/ 
Anyway, I understand that it is complicated since you don’t have the hardware to test it !

**Comment by 00-Evan** [comment]
Sorry for the delay on getting around to this.

From taking a quick look into magic keyboard gestures, it seems as though two finger swiping is used to scroll up or left-right. On macOS/Desktop Shattered this already has the established functionality of zooming in/out (same as pinch) or scrolling lists up/down.

If that is the case I'd rather leave the functionality as-is, so that its consistent with the macOS version of Shattered.

**Comment by 00-Evan** [comment]
Closing this under the assumptions made in my above comment, will be happy to re-open and discuss further if that's not the case.
