### ISSUE TITLE
Tengu maze exit misaligned

### ISSUE THREAD

**Issue by jimbo1qaz** [00-Evan/shattered-pixel-dungeon#82]
In the Tengu battle, the "exit maze" zone is slightly misaligned (one square below and right of intended location), allowing the player to avoid exiting the maze by remaining on the top row of the exit cell.
* The left-most column has no exit tiles at all, due to off-by-one.
* Stepping on the right side tile does not display a walking animation.

**Comment by 00-Evan** [comment]
Amusingly I actually found this one myself a couple days ago, it's fixed indev and will be rolled out to live with 0.4.0

**Comment by jimbo1qaz** [comment]
Why don't you publish development commits on Github, along the way?

* Most collaborative FOSS projects do that.
* Whis allows people to participate in development and fix bugs more easily.
* This will eliminate delays between Google Play and source code availability.

**Comment by 00-Evan** [comment]
Firstly, if you're concerned with the long turnaround, i'm currently absolutely swamped with the end of university term. 0.3.5 will be coming out very soon and I'm going to be a lot more free to work on shattered after that.

I primarily do not release commits as I make them because I want some control over the release of information, both for the purposes of other modders using my work, and for player's knowledge of upcoming updates. In the past other modders who derived work from shattered took features that were in development and incorporated them into their works because they were released to shattered. I'm certainly fine with derivative works, but wanted to take a pretty firm stance of "if it's not actually in shattered yet, you can't have it." Secondly, I want to be able to keep upcoming updates secret until just before a release them, rather than when I start implementing them.

The delay in source release is mostly artificial, as I would rather release code that others can use once I know its free of and major issues, which means the update will have to be live for a couple days to be sure.

Ultimately, shattered is a solo project, not a collaborative one, though I am of course happy to receive bug reports or suggestions/feedback.

**Comment by 00-Evan** [comment]
fixed in commit 751f11c502e5a3224be6a317f98748828f94032f
