### ISSUE TITLE
FreeBSD support? (libgdx)

### ISSUE THREAD

**Issue by ThatGeekyWeeb** [00-Evan/shattered-pixel-dungeon#840]
I recently moved to FreeBSD before noticing that, shattered pixel dungeon seems to be lacking support; running the jar with `java -jar` causes a crash with  `Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"`, I've seen this crash before with my Tegra k1 system, and am pretty sure it's an issue related to libgdx support.

Any chance you have bsd support planned? Or could work on FreeBSD support? 

From looking at the actual libgdx repo, is seems it does support FreeBSD, but a check for it needs to be done... but I don't know java so idk what really needs to be done here ...

~ Mia

**Comment by 00-Evan** [comment]
fixed in commit 740127b89d01d9822778e742ddc1e3ac94a8e69b

**Comment by Mia-Rain** [comment]
Sorry to necrobump but while these changes do work, libgdx and LWJGL3 have their own issues as the library's which are pulled from github are dynamically linked against glibc, which ofc is not present on FreeBSD.

**Comment by 00-Evan** [comment]
Well that's unfortunate. I assume that means the game does not actually run regardless of the adjustments in v1.1.0?

**Comment by Mia-Rain** [comment]
Yes unfortunately, however your changes did help with debugging!

**Comment by Mia-Rain** [comment]
Adding to this again; Recently submitted libgdx/libgdx#6976 which should fix the issues with libgdx, however spd may need to be manually compiled as libraries are fetched and replacing them doesn't seem easy. I'll see what I can figure out, if you have any ideas that would help tho.

**Comment by Mia-Rain** [comment]
Compiling doesn't seem to be as easy as I thought it would be, first it has issues with FreeBSD not being understood platform with android build, but if you simply yank out ./android it passes that however it then has an issue with `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:compileJava'.`

perhaps theres a way to set a custom location for `libgdx64.so`? since copying a custom native to the /tmp folder only causes it to be replaced

**Comment by Mia-Rain** [comment]
I'm working on seeing if I can get libgdx to introduce a feature that allows a variable to be set to the location of manually compiled natives, until then this should be reopened.  

If that isn't introduced at some point there is likely no other fix to this due to the system of library fetching libgdx uses.
