### ISSUE TITLE
Question from another dev

### ISSUE THREAD

**Issue by Beanzilla** [00-Evan/shattered-pixel-dungeon#896]
> First of all I want to say thank you for such a cool game. (I've been playing it for many years and just loved every minute of it)

Is the save supposed to contain invalid hjson keys?

According to the [hjson](https://hjson.github.io/syntax.html) syntax:

* You only need to add quotes if the key name includes whitespace or any of the punctuators ({}[],:).

Yet at least in v1.1.1 it does in fact have keys which do not have quotes around them (thus invalid).

My uncompressed save: [game1.txt](https://github.com/00-Evan/shattered-pixel-dungeon/files/7825989/game1.txt)

Starting at line 235 all the way down to line 304.

> TL;DR: The lines all resemble `class com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfUpgrade_label: KAUNAN` (With each line varying to some degree of course)

If it is not supposed to contain invalid hjson keys then simply adding quotes would solve the problem. (As I have read from at least one other issue that saves are corrupt, not sure if this could be an issue or not)

> Again, I'm not trying to sound mean, just wanted to ask the dev if this could be the reason (rather, why is it this way, or is this a mistake)

I have found that if I edited my save file to add the quotes then compressed it the game still reads it properly.

**Comment by 00-Evan** [comment]
As it happens I'm actually changing this in v1.1.2.

As of v1.1.0 Shattered stopped using org.json and switched to libGDX's own JSON handling code. This code seems to default to writing a 'minimal' JSON output, that is:

> Like JSON, but:
> 		 <ul><li>Names only require double quotes if they start with <code>space</code> or any of <code>":,}/</code> or they contain
> 		 <code>//</code> or <code>/*</code> or <code>:</code>.
> 		 <li>Values only require double quotes if they start with <code>space</code> or any of <code>":,{[]/</code> or they
> 		 contain <code>//</code> or <code>/*</code> or any of <code>}],</code> or they are equal to <code>true</code>,
> 		 <code>false</code> , or <code>null</code>.
> 		 <li>Newlines are treated as commas, making commas optional in many cases.
> 		 <li>C style comments may be used: <code>//...</code> or <code>/*...*<b></b>/</code></ul>

I'm making a change in v1.1.2 to improve performance (writing straight to the buffered writer instead of storing the entire save data as a string first, yikes), and this also is letting me specify whether I want regular JSON or this 'minimal' version. I'm not considering HJSON in particular, but the lack of double quotes is unusual for JSON in general, and the minification seems to lead to negligible space savings, so I'm disabling it. Once v1.1.2 is released the game's uncompressed saves should look a lot more like they did in 1.0.3 and earlier, with the addition of newlines and indenting for better readability.

I'm pretty sure this is unrelated to the save file corruption issues,
