### ISSUE TITLE
Non English text rendering issues on Android N

### ISSUE THREAD

**Issue by ndossougbete** [00-Evan/shattered-pixel-dungeon#90]
I just selected Russian in the language screen, on Android N preview.

![screenshot](https://cloud.githubusercontent.com/assets/15674243/14600324/dcce7e9a-0553-11e6-9873-824b1a8d1343.png)

**Comment by 00-Evan** [comment]
hmm, interesting, Looks like android N isn't reading the string resource files in as UTF-8, but rather as ISO-8859-1 instead. They've been read as UTF-8 since android gingerbread so i'm curious as to why this might be changed.

Will defer this until N's official release and will fix if it's still present then.

**Comment by narayank** [comment]
What APIs are you using for loading these String resources ? 

Somebody suggested that you were using java.util.ResourceBundle (or java.util.Properties), but that API has always used ISO-8859-1 (even on Android M and below). It's possible that there's a subtler issue at play.

Context: I work on the Android Platform team and want to fix this problem.

**Comment by narayank** [comment]
Well, never mind - it did use ISO-8859-1 for a while but then was (inadvertently) switched to UTF-8. I'll see what I can do for N.

**Comment by 00-Evan** [comment]
> Context: I work on the Android Platform team and want to fix this problem.

Awesome! Yes I do use resource bundles, for better portability to none-android code, such as the LibGDX port.

Assuming N is predictable in which format it reads in this can always be fixed by re-encoding the string. I already have a check for android 2.2 that does this. I imagine other applications aren't considering android 2.2 anymore though, and might be assuming the utf-8 format.

**Comment by narayank** [comment]
I switched N back to UTF-8 : https://android-review.googlesource.com/#/c/219785/ . No further action is needed on your part (at least wrt. Android).

Thanks :)

**Comment by 00-Evan** [comment]
Sounds good, closing this ticket.
