### ISSUE TITLE
[Beta 1.2.0] Feature: More Display Scale Steps

### ISSUE THREAD

**Issue by gitter-me** [00-Evan/shattered-pixel-dungeon#921]
I like the idea to see the inventory, while playing (desktop-version).
But right now (with the middle option in the settings) it overlaps too much of the game area on the screen.
And the left option is too small for me.

So one or two scale steps in between would be great

**Comment by 00-Evan** [comment]
The game already have several options for this:
- You can select mobile UI, full UI, or mixed UI (mobile inventory window with full UI otherwise)
- You can select the inventory button in the full UI mobile to hide/show the inventory
- You can reduce the display scale in the game's settings to make the UI smaller overall

I do agree though that the current layout of the settings window is not ideal as these settings are split over two tabs. I intend to improve that in the future.
