### ISSUE TITLE
Desktop UI still feels like mobile UI

### ISSUE THREAD

**Issue by ryuukk** [00-Evan/shattered-pixel-dungeon#952]
Hello

I have some issues with the UI, the new version while making it a little bit better still have many flaws

- Tooltips are basically useless, showing the name of the item is not helpful, and they have some delays, having to click to read what items do what is a pain
- Equipment stats should be on the tooltip
- Sometimes moving on items/gold doesn't automatically pick up (when enemies are revealed)

Thanks

**Comment by 00-Evan** [comment]
Having a slight delay for tooltips to appear is pretty standard, they would be very intrusive if they immediately appeared the second you moused over a UI element, or were absolutely massive and included the item's description or stats. Not that I think the new UI is perfect, but I don't really see how having to select UI elements makes the desktop UI feel like mobile.

As for picking up items, I will likely be merging the 'wait a turn' and 'pickup item' buttons in the next update, which should make things more streamlined, but not automatically picking up items when enemies are present is intended. This is so that the player doesn't accidentally spend turns picking up items during combat.

**Comment by ryuukk** [comment]
>  I don't really see how having to select UI elements makes the desktop UI feel like mobile.

Because on mobile they can't hover on elements, so they have to tap first, that's a sign of mobile UX

On PC games it is common for tooltips to show more information since we have a mouse and we can hover on things

So when you compare 2 items to see what to equip/use, it makes the experience much smoother and less clunky

![image](https://user-images.githubusercontent.com/44361234/161438826-214a16a5-ab02-4ed7-83ad-7ff043551546.png)

![image](https://user-images.githubusercontent.com/44361234/161438830-a7d4e9db-0f51-43c1-8bbc-603f7a505df4.png)


![image](https://user-images.githubusercontent.com/44361234/161438703-376e280f-a340-4c8e-9dca-6aaee2582dd7.png)

![image](https://user-images.githubusercontent.com/44361234/161438771-9efd07eb-18d6-4045-99f6-14deefbdcc62.png)

**Comment by 00-Evan** [comment]
I will consider adding some more details to item tooltips in the future, but I really don't want to have massive ugly tooltips like many ARPG games do. I also don't see how providing more information directly in the item icon is somehow inferior to making the player mouse over the item. It sounds to me like some of your concern is from expecting this game to have a similar UI layout to an ARPG.

Afraid I don't accept pull requests due to licensing issues.

**Comment by ryuukk** [comment]
> I will consider adding some more details to item tooltips in the future, but I really don't want to have massive ugly tooltips like many ARPG games do

Yeah i can understand that

> I also don't see how providing more information directly in the item icon is somehow inferior to making the player mouse over the item

It's not inferior, it is actually quite nice to have that information on the icon, i was just comparing UX differences, and maybe expectations when playing on a PC

People on steam didn't complain, maybe it's not worth it to change the experience
