### ISSUE TITLE
Enhancement: Auto-target nearest enemy setting

### ISSUE THREAD

**Issue by fregkos** [00-Evan/shattered-pixel-dungeon#973]
Most of the time, I need to target my closest enemy target with a projectile rather than my last. However, both options are useful. It would be awesome to have a "targeting strategy" selection in settings. Perhaps auto-targetting should ignore allies. I'm just pointing out that, yes, ally targeting has other incentives, thus different targeting strategy or none should apply.

**Comment by 00-Evan** [comment]
I'd rather keep auto targeting logic as simple and straightforward as possible. Making it more complex just leads to confusion, as the system will often be wrong when it tries to guess what the player wants, or will need constant configuring. In your case it's probably easier to just tap on what you want to hit instead of having to keep changing a setting between 'last hit' and 'closest'. This logic is also used for things like the attack button, which might behave unintuitively if it always swapped to the closest enemy. It's worth noting though that the system does default to the closest enemy if you don't have a target already.
